// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/web/issueconnect (interfaces: BoardReaderFactory,BoardPinsFactory)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package issueconnect -typed -write_package_comment=false . BoardReaderFactory,BoardPinsFactory
//

package issueconnect

import (
	reflect "reflect"

	board "go.abhg.dev/cardamom/internal/board"
	gomock "go.uber.org/mock/gomock"
)

// MockBoardReaderFactory is a mock of BoardReaderFactory interface.
type MockBoardReaderFactory struct {
	ctrl     *gomock.Controller
	recorder *MockBoardReaderFactoryMockRecorder
	isgomock struct{}
}

// MockBoardReaderFactoryMockRecorder is the mock recorder for MockBoardReaderFactory.
type MockBoardReaderFactoryMockRecorder struct {
	mock *MockBoardReaderFactory
}

// NewMockBoardReaderFactory creates a new mock instance.
func NewMockBoardReaderFactory(ctrl *gomock.Controller) *MockBoardReaderFactory {
	mock := &MockBoardReaderFactory{ctrl: ctrl}
	mock.recorder = &MockBoardReaderFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardReaderFactory) EXPECT() *MockBoardReaderFactoryMockRecorder {
	return m.recorder
}

// Reader mocks base method.
func (m *MockBoardReaderFactory) Reader(arg0 board.ID) (BoardReader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reader", arg0)
	ret0, _ := ret[0].(BoardReader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reader indicates an expected call of Reader.
func (mr *MockBoardReaderFactoryMockRecorder) Reader(arg0 any) *MockBoardReaderFactoryReaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reader", reflect.TypeOf((*MockBoardReaderFactory)(nil).Reader), arg0)
	return &MockBoardReaderFactoryReaderCall{Call: call}
}

// MockBoardReaderFactoryReaderCall wrap *gomock.Call
type MockBoardReaderFactoryReaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardReaderFactoryReaderCall) Return(arg0 BoardReader, arg1 error) *MockBoardReaderFactoryReaderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardReaderFactoryReaderCall) Do(f func(board.ID) (BoardReader, error)) *MockBoardReaderFactoryReaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardReaderFactoryReaderCall) DoAndReturn(f func(board.ID) (BoardReader, error)) *MockBoardReaderFactoryReaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockBoardPinsFactory is a mock of BoardPinsFactory interface.
type MockBoardPinsFactory struct {
	ctrl     *gomock.Controller
	recorder *MockBoardPinsFactoryMockRecorder
	isgomock struct{}
}

// MockBoardPinsFactoryMockRecorder is the mock recorder for MockBoardPinsFactory.
type MockBoardPinsFactoryMockRecorder struct {
	mock *MockBoardPinsFactory
}

// NewMockBoardPinsFactory creates a new mock instance.
func NewMockBoardPinsFactory(ctrl *gomock.Controller) *MockBoardPinsFactory {
	mock := &MockBoardPinsFactory{ctrl: ctrl}
	mock.recorder = &MockBoardPinsFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardPinsFactory) EXPECT() *MockBoardPinsFactoryMockRecorder {
	return m.recorder
}

// Pins mocks base method.
func (m *MockBoardPinsFactory) Pins(arg0 board.ID) (BoardPins, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pins", arg0)
	ret0, _ := ret[0].(BoardPins)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pins indicates an expected call of Pins.
func (mr *MockBoardPinsFactoryMockRecorder) Pins(arg0 any) *MockBoardPinsFactoryPinsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pins", reflect.TypeOf((*MockBoardPinsFactory)(nil).Pins), arg0)
	return &MockBoardPinsFactoryPinsCall{Call: call}
}

// MockBoardPinsFactoryPinsCall wrap *gomock.Call
type MockBoardPinsFactoryPinsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardPinsFactoryPinsCall) Return(arg0 BoardPins, arg1 error) *MockBoardPinsFactoryPinsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardPinsFactoryPinsCall) Do(f func(board.ID) (BoardPins, error)) *MockBoardPinsFactoryPinsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardPinsFactoryPinsCall) DoAndReturn(f func(board.ID) (BoardPins, error)) *MockBoardPinsFactoryPinsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
