// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/board (interfaces: Catalog,Changes)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package board -typed -write_package_comment=false . Catalog,Changes
//

package board

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCatalog is a mock of Catalog interface.
type MockCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogMockRecorder
	isgomock struct{}
}

// MockCatalogMockRecorder is the mock recorder for MockCatalog.
type MockCatalogMockRecorder struct {
	mock *MockCatalog
}

// NewMockCatalog creates a new mock instance.
func NewMockCatalog(ctrl *gomock.Controller) *MockCatalog {
	mock := &MockCatalog{ctrl: ctrl}
	mock.recorder = &MockCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalog) EXPECT() *MockCatalogMockRecorder {
	return m.recorder
}

// Board mocks base method.
func (m *MockCatalog) Board(arg0 context.Context, arg1 ID) (*State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Board", arg0, arg1)
	ret0, _ := ret[0].(*State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Board indicates an expected call of Board.
func (mr *MockCatalogMockRecorder) Board(arg0, arg1 any) *MockCatalogBoardCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Board", reflect.TypeOf((*MockCatalog)(nil).Board), arg0, arg1)
	return &MockCatalogBoardCall{Call: call}
}

// MockCatalogBoardCall wrap *gomock.Call
type MockCatalogBoardCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCatalogBoardCall) Return(arg0 *State, arg1 error) *MockCatalogBoardCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCatalogBoardCall) Do(f func(context.Context, ID) (*State, error)) *MockCatalogBoardCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCatalogBoardCall) DoAndReturn(f func(context.Context, ID) (*State, error)) *MockCatalogBoardCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListAllBoards mocks base method.
func (m *MockCatalog) ListAllBoards(arg0 context.Context) ([]*State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAllBoards", arg0)
	ret0, _ := ret[0].([]*State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAllBoards indicates an expected call of ListAllBoards.
func (mr *MockCatalogMockRecorder) ListAllBoards(arg0 any) *MockCatalogListAllBoardsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAllBoards", reflect.TypeOf((*MockCatalog)(nil).ListAllBoards), arg0)
	return &MockCatalogListAllBoardsCall{Call: call}
}

// MockCatalogListAllBoardsCall wrap *gomock.Call
type MockCatalogListAllBoardsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCatalogListAllBoardsCall) Return(arg0 []*State, arg1 error) *MockCatalogListAllBoardsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCatalogListAllBoardsCall) Do(f func(context.Context) ([]*State, error)) *MockCatalogListAllBoardsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCatalogListAllBoardsCall) DoAndReturn(f func(context.Context) ([]*State, error)) *MockCatalogListAllBoardsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SoleBoard mocks base method.
func (m *MockCatalog) SoleBoard(arg0 context.Context) (*State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoleBoard", arg0)
	ret0, _ := ret[0].(*State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoleBoard indicates an expected call of SoleBoard.
func (mr *MockCatalogMockRecorder) SoleBoard(arg0 any) *MockCatalogSoleBoardCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoleBoard", reflect.TypeOf((*MockCatalog)(nil).SoleBoard), arg0)
	return &MockCatalogSoleBoardCall{Call: call}
}

// MockCatalogSoleBoardCall wrap *gomock.Call
type MockCatalogSoleBoardCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCatalogSoleBoardCall) Return(arg0 *State, arg1 error) *MockCatalogSoleBoardCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCatalogSoleBoardCall) Do(f func(context.Context) (*State, error)) *MockCatalogSoleBoardCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCatalogSoleBoardCall) DoAndReturn(f func(context.Context) (*State, error)) *MockCatalogSoleBoardCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockChanges is a mock of Changes interface.
type MockChanges struct {
	ctrl     *gomock.Controller
	recorder *MockChangesMockRecorder
	isgomock struct{}
}

// MockChangesMockRecorder is the mock recorder for MockChanges.
type MockChangesMockRecorder struct {
	mock *MockChanges
}

// NewMockChanges creates a new mock instance.
func NewMockChanges(ctrl *gomock.Controller) *MockChanges {
	mock := &MockChanges{ctrl: ctrl}
	mock.recorder = &MockChangesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChanges) EXPECT() *MockChangesMockRecorder {
	return m.recorder
}

// CreateBoard mocks base method.
func (m *MockChanges) CreateBoard(arg0 context.Context, arg1 CreateRequest) (*State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBoard", arg0, arg1)
	ret0, _ := ret[0].(*State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBoard indicates an expected call of CreateBoard.
func (mr *MockChangesMockRecorder) CreateBoard(arg0, arg1 any) *MockChangesCreateBoardCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBoard", reflect.TypeOf((*MockChanges)(nil).CreateBoard), arg0, arg1)
	return &MockChangesCreateBoardCall{Call: call}
}

// MockChangesCreateBoardCall wrap *gomock.Call
type MockChangesCreateBoardCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangesCreateBoardCall) Return(arg0 *State, arg1 error) *MockChangesCreateBoardCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangesCreateBoardCall) Do(f func(context.Context, CreateRequest) (*State, error)) *MockChangesCreateBoardCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangesCreateBoardCall) DoAndReturn(f func(context.Context, CreateRequest) (*State, error)) *MockChangesCreateBoardCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EditBoardSettings mocks base method.
func (m *MockChanges) EditBoardSettings(arg0 context.Context, arg1 EditRequest) (*State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditBoardSettings", arg0, arg1)
	ret0, _ := ret[0].(*State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditBoardSettings indicates an expected call of EditBoardSettings.
func (mr *MockChangesMockRecorder) EditBoardSettings(arg0, arg1 any) *MockChangesEditBoardSettingsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditBoardSettings", reflect.TypeOf((*MockChanges)(nil).EditBoardSettings), arg0, arg1)
	return &MockChangesEditBoardSettingsCall{Call: call}
}

// MockChangesEditBoardSettingsCall wrap *gomock.Call
type MockChangesEditBoardSettingsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangesEditBoardSettingsCall) Return(arg0 *State, arg1 error) *MockChangesEditBoardSettingsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangesEditBoardSettingsCall) Do(f func(context.Context, EditRequest) (*State, error)) *MockChangesEditBoardSettingsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangesEditBoardSettingsCall) DoAndReturn(f func(context.Context, EditRequest) (*State, error)) *MockChangesEditBoardSettingsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
