// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/web/informationconnect (interfaces: Reader)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package informationconnect -typed -write_package_comment=false . Reader
//

package informationconnect

import (
	context "context"
	reflect "reflect"

	information "go.abhg.dev/cardamom/internal/information"
	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockReader) Read(arg0 context.Context, arg1 information.Request) (information.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(information.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockReaderMockRecorder) Read(arg0, arg1 any) *MockReaderReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReader)(nil).Read), arg0, arg1)
	return &MockReaderReadCall{Call: call}
}

// MockReaderReadCall wrap *gomock.Call
type MockReaderReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReaderReadCall) Return(arg0 information.Report, arg1 error) *MockReaderReadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReaderReadCall) Do(f func(context.Context, information.Request) (information.Report, error)) *MockReaderReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReaderReadCall) DoAndReturn(f func(context.Context, information.Request) (information.Report, error)) *MockReaderReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
