// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/web/checkpointconnect (interfaces: BoardReader,BoardReaderFactory,BoardCommands,BoardCommandFactory)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package checkpointconnect -typed -write_package_comment=false . BoardReader,BoardReaderFactory,BoardCommands,BoardCommandFactory
//

package checkpointconnect

import (
	context "context"
	reflect "reflect"

	board "go.abhg.dev/cardamom/internal/board"
	issue "go.abhg.dev/cardamom/internal/issue"
	execution "go.abhg.dev/cardamom/internal/issue/execution"
	gomock "go.uber.org/mock/gomock"
)

// MockBoardReader is a mock of BoardReader interface.
type MockBoardReader struct {
	ctrl     *gomock.Controller
	recorder *MockBoardReaderMockRecorder
	isgomock struct{}
}

// MockBoardReaderMockRecorder is the mock recorder for MockBoardReader.
type MockBoardReaderMockRecorder struct {
	mock *MockBoardReader
}

// NewMockBoardReader creates a new mock instance.
func NewMockBoardReader(ctrl *gomock.Controller) *MockBoardReader {
	mock := &MockBoardReader{ctrl: ctrl}
	mock.recorder = &MockBoardReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardReader) EXPECT() *MockBoardReaderMockRecorder {
	return m.recorder
}

// ListActionableCheckpoints mocks base method.
func (m *MockBoardReader) ListActionableCheckpoints(arg0 context.Context) ([]issue.CheckpointView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActionableCheckpoints", arg0)
	ret0, _ := ret[0].([]issue.CheckpointView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActionableCheckpoints indicates an expected call of ListActionableCheckpoints.
func (mr *MockBoardReaderMockRecorder) ListActionableCheckpoints(arg0 any) *MockBoardReaderListActionableCheckpointsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActionableCheckpoints", reflect.TypeOf((*MockBoardReader)(nil).ListActionableCheckpoints), arg0)
	return &MockBoardReaderListActionableCheckpointsCall{Call: call}
}

// MockBoardReaderListActionableCheckpointsCall wrap *gomock.Call
type MockBoardReaderListActionableCheckpointsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardReaderListActionableCheckpointsCall) Return(arg0 []issue.CheckpointView, arg1 error) *MockBoardReaderListActionableCheckpointsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardReaderListActionableCheckpointsCall) Do(f func(context.Context) ([]issue.CheckpointView, error)) *MockBoardReaderListActionableCheckpointsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardReaderListActionableCheckpointsCall) DoAndReturn(f func(context.Context) ([]issue.CheckpointView, error)) *MockBoardReaderListActionableCheckpointsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadIssue mocks base method.
func (m *MockBoardReader) ReadIssue(arg0 context.Context, arg1 issue.ReadRequest) (issue.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadIssue", arg0, arg1)
	ret0, _ := ret[0].(issue.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadIssue indicates an expected call of ReadIssue.
func (mr *MockBoardReaderMockRecorder) ReadIssue(arg0, arg1 any) *MockBoardReaderReadIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadIssue", reflect.TypeOf((*MockBoardReader)(nil).ReadIssue), arg0, arg1)
	return &MockBoardReaderReadIssueCall{Call: call}
}

// MockBoardReaderReadIssueCall wrap *gomock.Call
type MockBoardReaderReadIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardReaderReadIssueCall) Return(arg0 issue.View, arg1 error) *MockBoardReaderReadIssueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardReaderReadIssueCall) Do(f func(context.Context, issue.ReadRequest) (issue.View, error)) *MockBoardReaderReadIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardReaderReadIssueCall) DoAndReturn(f func(context.Context, issue.ReadRequest) (issue.View, error)) *MockBoardReaderReadIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockBoardReaderFactory is a mock of BoardReaderFactory interface.
type MockBoardReaderFactory struct {
	ctrl     *gomock.Controller
	recorder *MockBoardReaderFactoryMockRecorder
	isgomock struct{}
}

// MockBoardReaderFactoryMockRecorder is the mock recorder for MockBoardReaderFactory.
type MockBoardReaderFactoryMockRecorder struct {
	mock *MockBoardReaderFactory
}

// NewMockBoardReaderFactory creates a new mock instance.
func NewMockBoardReaderFactory(ctrl *gomock.Controller) *MockBoardReaderFactory {
	mock := &MockBoardReaderFactory{ctrl: ctrl}
	mock.recorder = &MockBoardReaderFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardReaderFactory) EXPECT() *MockBoardReaderFactoryMockRecorder {
	return m.recorder
}

// Reader mocks base method.
func (m *MockBoardReaderFactory) Reader(arg0 board.ID) (BoardReader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reader", arg0)
	ret0, _ := ret[0].(BoardReader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reader indicates an expected call of Reader.
func (mr *MockBoardReaderFactoryMockRecorder) Reader(arg0 any) *MockBoardReaderFactoryReaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reader", reflect.TypeOf((*MockBoardReaderFactory)(nil).Reader), arg0)
	return &MockBoardReaderFactoryReaderCall{Call: call}
}

// MockBoardReaderFactoryReaderCall wrap *gomock.Call
type MockBoardReaderFactoryReaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardReaderFactoryReaderCall) Return(arg0 BoardReader, arg1 error) *MockBoardReaderFactoryReaderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardReaderFactoryReaderCall) Do(f func(board.ID) (BoardReader, error)) *MockBoardReaderFactoryReaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardReaderFactoryReaderCall) DoAndReturn(f func(board.ID) (BoardReader, error)) *MockBoardReaderFactoryReaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockBoardCommands is a mock of BoardCommands interface.
type MockBoardCommands struct {
	ctrl     *gomock.Controller
	recorder *MockBoardCommandsMockRecorder
	isgomock struct{}
}

// MockBoardCommandsMockRecorder is the mock recorder for MockBoardCommands.
type MockBoardCommandsMockRecorder struct {
	mock *MockBoardCommands
}

// NewMockBoardCommands creates a new mock instance.
func NewMockBoardCommands(ctrl *gomock.Controller) *MockBoardCommands {
	mock := &MockBoardCommands{ctrl: ctrl}
	mock.recorder = &MockBoardCommandsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardCommands) EXPECT() *MockBoardCommandsMockRecorder {
	return m.recorder
}

// ApproveCheckpoint mocks base method.
func (m *MockBoardCommands) ApproveCheckpoint(arg0 context.Context, arg1 issue.Invocation, arg2 execution.CheckpointRequest) (execution.ResolveCheckpointResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveCheckpoint", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.ResolveCheckpointResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveCheckpoint indicates an expected call of ApproveCheckpoint.
func (mr *MockBoardCommandsMockRecorder) ApproveCheckpoint(arg0, arg1, arg2 any) *MockBoardCommandsApproveCheckpointCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveCheckpoint", reflect.TypeOf((*MockBoardCommands)(nil).ApproveCheckpoint), arg0, arg1, arg2)
	return &MockBoardCommandsApproveCheckpointCall{Call: call}
}

// MockBoardCommandsApproveCheckpointCall wrap *gomock.Call
type MockBoardCommandsApproveCheckpointCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardCommandsApproveCheckpointCall) Return(arg0 execution.ResolveCheckpointResult, arg1 error) *MockBoardCommandsApproveCheckpointCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardCommandsApproveCheckpointCall) Do(f func(context.Context, issue.Invocation, execution.CheckpointRequest) (execution.ResolveCheckpointResult, error)) *MockBoardCommandsApproveCheckpointCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardCommandsApproveCheckpointCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.CheckpointRequest) (execution.ResolveCheckpointResult, error)) *MockBoardCommandsApproveCheckpointCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DenyCheckpoint mocks base method.
func (m *MockBoardCommands) DenyCheckpoint(arg0 context.Context, arg1 issue.Invocation, arg2 execution.CheckpointRequest) (execution.ResolveCheckpointResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DenyCheckpoint", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.ResolveCheckpointResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DenyCheckpoint indicates an expected call of DenyCheckpoint.
func (mr *MockBoardCommandsMockRecorder) DenyCheckpoint(arg0, arg1, arg2 any) *MockBoardCommandsDenyCheckpointCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DenyCheckpoint", reflect.TypeOf((*MockBoardCommands)(nil).DenyCheckpoint), arg0, arg1, arg2)
	return &MockBoardCommandsDenyCheckpointCall{Call: call}
}

// MockBoardCommandsDenyCheckpointCall wrap *gomock.Call
type MockBoardCommandsDenyCheckpointCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardCommandsDenyCheckpointCall) Return(arg0 execution.ResolveCheckpointResult, arg1 error) *MockBoardCommandsDenyCheckpointCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardCommandsDenyCheckpointCall) Do(f func(context.Context, issue.Invocation, execution.CheckpointRequest) (execution.ResolveCheckpointResult, error)) *MockBoardCommandsDenyCheckpointCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardCommandsDenyCheckpointCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.CheckpointRequest) (execution.ResolveCheckpointResult, error)) *MockBoardCommandsDenyCheckpointCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockBoardCommandFactory is a mock of BoardCommandFactory interface.
type MockBoardCommandFactory struct {
	ctrl     *gomock.Controller
	recorder *MockBoardCommandFactoryMockRecorder
	isgomock struct{}
}

// MockBoardCommandFactoryMockRecorder is the mock recorder for MockBoardCommandFactory.
type MockBoardCommandFactoryMockRecorder struct {
	mock *MockBoardCommandFactory
}

// NewMockBoardCommandFactory creates a new mock instance.
func NewMockBoardCommandFactory(ctrl *gomock.Controller) *MockBoardCommandFactory {
	mock := &MockBoardCommandFactory{ctrl: ctrl}
	mock.recorder = &MockBoardCommandFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardCommandFactory) EXPECT() *MockBoardCommandFactoryMockRecorder {
	return m.recorder
}

// Commands mocks base method.
func (m *MockBoardCommandFactory) Commands(arg0 board.ID) (BoardCommands, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commands", arg0)
	ret0, _ := ret[0].(BoardCommands)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Commands indicates an expected call of Commands.
func (mr *MockBoardCommandFactoryMockRecorder) Commands(arg0 any) *MockBoardCommandFactoryCommandsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commands", reflect.TypeOf((*MockBoardCommandFactory)(nil).Commands), arg0)
	return &MockBoardCommandFactoryCommandsCall{Call: call}
}

// MockBoardCommandFactoryCommandsCall wrap *gomock.Call
type MockBoardCommandFactoryCommandsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardCommandFactoryCommandsCall) Return(arg0 BoardCommands, arg1 error) *MockBoardCommandFactoryCommandsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardCommandFactoryCommandsCall) Do(f func(board.ID) (BoardCommands, error)) *MockBoardCommandFactoryCommandsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardCommandFactoryCommandsCall) DoAndReturn(f func(board.ID) (BoardCommands, error)) *MockBoardCommandFactoryCommandsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
