// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/web/configurationconnect (interfaces: Configurations)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package configurationconnect -typed -write_package_comment=false . Configurations
//

package configurationconnect

import (
	context "context"
	reflect "reflect"

	board "go.abhg.dev/cardamom/internal/board"
	configuration "go.abhg.dev/cardamom/internal/configuration"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigurations is a mock of Configurations interface.
type MockConfigurations struct {
	ctrl     *gomock.Controller
	recorder *MockConfigurationsMockRecorder
	isgomock struct{}
}

// MockConfigurationsMockRecorder is the mock recorder for MockConfigurations.
type MockConfigurationsMockRecorder struct {
	mock *MockConfigurations
}

// NewMockConfigurations creates a new mock instance.
func NewMockConfigurations(ctrl *gomock.Controller) *MockConfigurations {
	mock := &MockConfigurations{ctrl: ctrl}
	mock.recorder = &MockConfigurationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigurations) EXPECT() *MockConfigurationsMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockConfigurations) Resolve(arg0 context.Context, arg1 board.ID) (configuration.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", arg0, arg1)
	ret0, _ := ret[0].(configuration.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockConfigurationsMockRecorder) Resolve(arg0, arg1 any) *MockConfigurationsResolveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockConfigurations)(nil).Resolve), arg0, arg1)
	return &MockConfigurationsResolveCall{Call: call}
}

// MockConfigurationsResolveCall wrap *gomock.Call
type MockConfigurationsResolveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfigurationsResolveCall) Return(arg0 configuration.View, arg1 error) *MockConfigurationsResolveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfigurationsResolveCall) Do(f func(context.Context, board.ID) (configuration.View, error)) *MockConfigurationsResolveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfigurationsResolveCall) DoAndReturn(f func(context.Context, board.ID) (configuration.View, error)) *MockConfigurationsResolveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockConfigurations) Update(arg0 context.Context, arg1 configuration.Invocation, arg2 configuration.UpdateRequest) (configuration.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(configuration.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockConfigurationsMockRecorder) Update(arg0, arg1, arg2 any) *MockConfigurationsUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockConfigurations)(nil).Update), arg0, arg1, arg2)
	return &MockConfigurationsUpdateCall{Call: call}
}

// MockConfigurationsUpdateCall wrap *gomock.Call
type MockConfigurationsUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfigurationsUpdateCall) Return(arg0 configuration.View, arg1 error) *MockConfigurationsUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfigurationsUpdateCall) Do(f func(context.Context, configuration.Invocation, configuration.UpdateRequest) (configuration.View, error)) *MockConfigurationsUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfigurationsUpdateCall) DoAndReturn(f func(context.Context, configuration.Invocation, configuration.UpdateRequest) (configuration.View, error)) *MockConfigurationsUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
