// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/web/issueview (interfaces: MarkdownRenderer)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package issueview -typed -write_package_comment=false . MarkdownRenderer
//

package issueview

import (
	context "context"
	reflect "reflect"

	board "go.abhg.dev/cardamom/internal/board"
	gomock "go.uber.org/mock/gomock"
)

// MockMarkdownRenderer is a mock of MarkdownRenderer interface.
type MockMarkdownRenderer struct {
	ctrl     *gomock.Controller
	recorder *MockMarkdownRendererMockRecorder
	isgomock struct{}
}

// MockMarkdownRendererMockRecorder is the mock recorder for MockMarkdownRenderer.
type MockMarkdownRendererMockRecorder struct {
	mock *MockMarkdownRenderer
}

// NewMockMarkdownRenderer creates a new mock instance.
func NewMockMarkdownRenderer(ctrl *gomock.Controller) *MockMarkdownRenderer {
	mock := &MockMarkdownRenderer{ctrl: ctrl}
	mock.recorder = &MockMarkdownRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMarkdownRenderer) EXPECT() *MockMarkdownRendererMockRecorder {
	return m.recorder
}

// RenderBoard mocks base method.
func (m *MockMarkdownRenderer) RenderBoard(arg0 context.Context, arg1 board.ID, arg2 string, arg3 []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderBoard", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderBoard indicates an expected call of RenderBoard.
func (mr *MockMarkdownRendererMockRecorder) RenderBoard(arg0, arg1, arg2, arg3 any) *MockMarkdownRendererRenderBoardCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderBoard", reflect.TypeOf((*MockMarkdownRenderer)(nil).RenderBoard), arg0, arg1, arg2, arg3)
	return &MockMarkdownRendererRenderBoardCall{Call: call}
}

// MockMarkdownRendererRenderBoardCall wrap *gomock.Call
type MockMarkdownRendererRenderBoardCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMarkdownRendererRenderBoardCall) Return(arg0 []string, arg1 error) *MockMarkdownRendererRenderBoardCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMarkdownRendererRenderBoardCall) Do(f func(context.Context, board.ID, string, []string) ([]string, error)) *MockMarkdownRendererRenderBoardCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMarkdownRendererRenderBoardCall) DoAndReturn(f func(context.Context, board.ID, string, []string) ([]string, error)) *MockMarkdownRendererRenderBoardCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
