// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment_upload_terminal.sql

package query

import (
	"context"
	"time"
)

const attachmentAbortUploadReceipt = `-- name: AttachmentAbortUploadReceipt :exec
UPDATE attachment_uploads
SET state = 'aborted',
    expires_at = ?1
WHERE id = ?2
    AND state = 'active'
`

type AttachmentAbortUploadReceiptParams struct {
	ExpiresAt time.Time
	ID        string
}

func (q *Queries) AttachmentAbortUploadReceipt(ctx context.Context, arg AttachmentAbortUploadReceiptParams) error {
	_, err := q.db.ExecContext(ctx, attachmentAbortUploadReceipt, arg.ExpiresAt, arg.ID)
	return err
}

const attachmentCommitUploadReceipt = `-- name: AttachmentCommitUploadReceipt :exec
UPDATE attachment_uploads
SET state = 'committed',
    expires_at = ?1,
    attachment_id = ?2
WHERE id = ?3
    AND state = 'active'
`

type AttachmentCommitUploadReceiptParams struct {
	ExpiresAt    time.Time
	AttachmentID *string
	ID           string
}

func (q *Queries) AttachmentCommitUploadReceipt(ctx context.Context, arg AttachmentCommitUploadReceiptParams) error {
	_, err := q.db.ExecContext(ctx, attachmentCommitUploadReceipt, arg.ExpiresAt, arg.AttachmentID, arg.ID)
	return err
}

const attachmentInsertMetadata = `-- name: AttachmentInsertMetadata :exec
INSERT INTO attachments (
    board_id,
    id,
    origin_issue_id,
    blob_digest,
    blob_size_bytes,
    filename,
    media_type,
    lifecycle,
    created_actor,
    created_at,
    created_revision
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    'active',
    ?8,
    ?9,
    ?10
)
`

type AttachmentInsertMetadataParams struct {
	BoardID         string
	ID              string
	OriginIssueID   *string
	BlobDigest      string
	BlobSizeBytes   int64
	Filename        string
	MediaType       string
	CreatedActor    string
	CreatedAt       time.Time
	CreatedRevision int64
}

func (q *Queries) AttachmentInsertMetadata(ctx context.Context, arg AttachmentInsertMetadataParams) error {
	_, err := q.db.ExecContext(ctx, attachmentInsertMetadata,
		arg.BoardID,
		arg.ID,
		arg.OriginIssueID,
		arg.BlobDigest,
		arg.BlobSizeBytes,
		arg.Filename,
		arg.MediaType,
		arg.CreatedActor,
		arg.CreatedAt,
		arg.CreatedRevision,
	)
	return err
}

const attachmentRetainBlob = `-- name: AttachmentRetainBlob :exec
INSERT INTO attachment_blobs (
    digest,
    size_bytes
) VALUES (
    ?1,
    ?2
)
ON CONFLICT(digest) DO NOTHING
`

type AttachmentRetainBlobParams struct {
	Digest    string
	SizeBytes int64
}

func (q *Queries) AttachmentRetainBlob(ctx context.Context, arg AttachmentRetainBlobParams) error {
	_, err := q.db.ExecContext(ctx, attachmentRetainBlob, arg.Digest, arg.SizeBytes)
	return err
}
