// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment_upload_read.sql

package query

import (
	"context"
)

const attachmentGetUpload = `-- name: AttachmentGetUpload :one
SELECT attachment_uploads.id, attachment_uploads.board_id, attachment_uploads.origin_issue_id, attachment_uploads.filename, attachment_uploads.expected_size_bytes, attachment_uploads.expected_digest, attachment_uploads.actor, attachment_uploads.state, attachment_uploads.accepted_offset, attachment_uploads.expires_at, attachment_uploads.attachment_id, attachment_uploads.admitted_max_bytes
FROM attachment_uploads
WHERE id = ?1
`

func (q *Queries) AttachmentGetUpload(ctx context.Context, id string) (AttachmentUpload, error) {
	row := q.db.QueryRowContext(ctx, attachmentGetUpload, id)
	var i AttachmentUpload
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.OriginIssueID,
		&i.Filename,
		&i.ExpectedSizeBytes,
		&i.ExpectedDigest,
		&i.Actor,
		&i.State,
		&i.AcceptedOffset,
		&i.ExpiresAt,
		&i.AttachmentID,
		&i.AdmittedMaxBytes,
	)
	return i, err
}
