// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment_metadata_read.sql

package query

import (
	"context"
	"strings"
	"time"
)

const attachmentGetMetadata = `-- name: AttachmentGetMetadata :one
SELECT attachment.board_id, attachment.id, attachment.origin_issue_uid, attachment.blob_digest, attachment.blob_size_bytes, attachment.filename, attachment.media_type, attachment.lifecycle, attachment.created_actor, attachment.created_at, attachment.created_revision, attachment.removed_actor, attachment.removed_at, attachment.removed_revision, issue.id AS origin_issue_id
FROM attachments AS attachment
LEFT JOIN issues AS issue ON issue.uid = attachment.origin_issue_uid
WHERE attachment.board_id = ?1
    AND attachment.id = ?2
`

type AttachmentGetMetadataParams struct {
	BoardID string
	ID      string
}

type AttachmentGetMetadataRow struct {
	BoardID         string
	ID              string
	OriginIssueUid  []byte
	BlobDigest      string
	BlobSizeBytes   int64
	Filename        string
	MediaType       string
	Lifecycle       string
	CreatedActor    string
	CreatedAt       time.Time
	CreatedRevision int64
	RemovedActor    *string
	RemovedAt       *time.Time
	RemovedRevision *int64
	OriginIssueID   *string
}

func (q *Queries) AttachmentGetMetadata(ctx context.Context, arg AttachmentGetMetadataParams) (AttachmentGetMetadataRow, error) {
	row := q.db.QueryRowContext(ctx, attachmentGetMetadata, arg.BoardID, arg.ID)
	var i AttachmentGetMetadataRow
	err := row.Scan(
		&i.BoardID,
		&i.ID,
		&i.OriginIssueUid,
		&i.BlobDigest,
		&i.BlobSizeBytes,
		&i.Filename,
		&i.MediaType,
		&i.Lifecycle,
		&i.CreatedActor,
		&i.CreatedAt,
		&i.CreatedRevision,
		&i.RemovedActor,
		&i.RemovedAt,
		&i.RemovedRevision,
		&i.OriginIssueID,
	)
	return i, err
}

const attachmentListMetadata = `-- name: AttachmentListMetadata :many
SELECT attachment.board_id, attachment.id, attachment.origin_issue_uid, attachment.blob_digest, attachment.blob_size_bytes, attachment.filename, attachment.media_type, attachment.lifecycle, attachment.created_actor, attachment.created_at, attachment.created_revision, attachment.removed_actor, attachment.removed_at, attachment.removed_revision, issue.id AS origin_issue_id
FROM attachments AS attachment
LEFT JOIN issues AS issue ON issue.uid = attachment.origin_issue_uid
WHERE attachment.board_id = ?1
    AND attachment.id > ?2
    AND (?3 OR attachment.lifecycle = 'active')
    AND (
        NOT ?4
        OR attachment.origin_issue_uid = ?5
    )
ORDER BY attachment.id
LIMIT ?6
`

type AttachmentListMetadataParams struct {
	BoardID        string
	AfterID        string
	IncludeRemoved interface{}
	HasOriginIssue interface{}
	OriginIssueUid []byte
	ResultLimit    int64
}

type AttachmentListMetadataRow struct {
	BoardID         string
	ID              string
	OriginIssueUid  []byte
	BlobDigest      string
	BlobSizeBytes   int64
	Filename        string
	MediaType       string
	Lifecycle       string
	CreatedActor    string
	CreatedAt       time.Time
	CreatedRevision int64
	RemovedActor    *string
	RemovedAt       *time.Time
	RemovedRevision *int64
	OriginIssueID   *string
}

func (q *Queries) AttachmentListMetadata(ctx context.Context, arg AttachmentListMetadataParams) ([]AttachmentListMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, attachmentListMetadata,
		arg.BoardID,
		arg.AfterID,
		arg.IncludeRemoved,
		arg.HasOriginIssue,
		arg.OriginIssueUid,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttachmentListMetadataRow
	for rows.Next() {
		var i AttachmentListMetadataRow
		if err := rows.Scan(
			&i.BoardID,
			&i.ID,
			&i.OriginIssueUid,
			&i.BlobDigest,
			&i.BlobSizeBytes,
			&i.Filename,
			&i.MediaType,
			&i.Lifecycle,
			&i.CreatedActor,
			&i.CreatedAt,
			&i.CreatedRevision,
			&i.RemovedActor,
			&i.RemovedAt,
			&i.RemovedRevision,
			&i.OriginIssueID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attachmentResolveMetadata = `-- name: AttachmentResolveMetadata :many
SELECT attachment.board_id, attachment.id, attachment.origin_issue_uid, attachment.blob_digest, attachment.blob_size_bytes, attachment.filename, attachment.media_type, attachment.lifecycle, attachment.created_actor, attachment.created_at, attachment.created_revision, attachment.removed_actor, attachment.removed_at, attachment.removed_revision, issue.id AS origin_issue_id
FROM attachments AS attachment
LEFT JOIN issues AS issue ON issue.uid = attachment.origin_issue_uid
WHERE attachment.board_id = ?1
    AND attachment.id IN (/*SLICE:attachment_ids*/?)
`

type AttachmentResolveMetadataParams struct {
	BoardID       string
	AttachmentIDs []string
}

type AttachmentResolveMetadataRow struct {
	BoardID         string
	ID              string
	OriginIssueUid  []byte
	BlobDigest      string
	BlobSizeBytes   int64
	Filename        string
	MediaType       string
	Lifecycle       string
	CreatedActor    string
	CreatedAt       time.Time
	CreatedRevision int64
	RemovedActor    *string
	RemovedAt       *time.Time
	RemovedRevision *int64
	OriginIssueID   *string
}

func (q *Queries) AttachmentResolveMetadata(ctx context.Context, arg AttachmentResolveMetadataParams) ([]AttachmentResolveMetadataRow, error) {
	query := attachmentResolveMetadata
	var queryParams []interface{}
	queryParams = append(queryParams, arg.BoardID)
	if len(arg.AttachmentIDs) > 0 {
		for _, v := range arg.AttachmentIDs {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:attachment_ids*/?", strings.Repeat(",?", len(arg.AttachmentIDs))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:attachment_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttachmentResolveMetadataRow
	for rows.Next() {
		var i AttachmentResolveMetadataRow
		if err := rows.Scan(
			&i.BoardID,
			&i.ID,
			&i.OriginIssueUid,
			&i.BlobDigest,
			&i.BlobSizeBytes,
			&i.Filename,
			&i.MediaType,
			&i.Lifecycle,
			&i.CreatedActor,
			&i.CreatedAt,
			&i.CreatedRevision,
			&i.RemovedActor,
			&i.RemovedAt,
			&i.RemovedRevision,
			&i.OriginIssueID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
