// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment_revision_publication.sql

package query

import (
	"context"
	"database/sql"
)

const attachmentGetBoardRevision = `-- name: AttachmentGetBoardRevision :one
SELECT revision
FROM boards
WHERE id = ?1
`

func (q *Queries) AttachmentGetBoardRevision(ctx context.Context, boardID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, attachmentGetBoardRevision, boardID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const attachmentPublishBoardRevision = `-- name: AttachmentPublishBoardRevision :execresult
UPDATE boards
SET revision = ?1
WHERE id = ?2
    AND revision = ?3
`

type AttachmentPublishBoardRevisionParams struct {
	Revision         int64
	BoardID          string
	PreviousRevision int64
}

func (q *Queries) AttachmentPublishBoardRevision(ctx context.Context, arg AttachmentPublishBoardRevisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, attachmentPublishBoardRevision, arg.Revision, arg.BoardID, arg.PreviousRevision)
}

const attachmentPublishIssueRevision = `-- name: AttachmentPublishIssueRevision :execresult
UPDATE issues
SET revision = ?1
WHERE board_id = ?2
    AND id = ?3
`

type AttachmentPublishIssueRevisionParams struct {
	Revision int64
	BoardID  string
	IssueID  string
}

func (q *Queries) AttachmentPublishIssueRevision(ctx context.Context, arg AttachmentPublishIssueRevisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, attachmentPublishIssueRevision, arg.Revision, arg.BoardID, arg.IssueID)
}
