// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment_upload_status.sql

package query

import (
	"context"
	"time"
)

const attachmentExpireUpload = `-- name: AttachmentExpireUpload :exec
UPDATE attachment_uploads
SET state = 'expired',
    expires_at = ?1
WHERE id = ?2
    AND state = 'active'
`

type AttachmentExpireUploadParams struct {
	ExpiresAt time.Time
	ID        string
}

func (q *Queries) AttachmentExpireUpload(ctx context.Context, arg AttachmentExpireUploadParams) error {
	_, err := q.db.ExecContext(ctx, attachmentExpireUpload, arg.ExpiresAt, arg.ID)
	return err
}
