// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment_upload_chunk.sql

package query

import (
	"context"
	"time"
)

const attachmentUpdateUploadProgress = `-- name: AttachmentUpdateUploadProgress :exec
UPDATE attachment_uploads
SET accepted_offset = ?1,
    expires_at = ?2
WHERE id = ?3
    AND state = 'active'
`

type AttachmentUpdateUploadProgressParams struct {
	AcceptedOffset int64
	ExpiresAt      time.Time
	ID             string
}

func (q *Queries) AttachmentUpdateUploadProgress(ctx context.Context, arg AttachmentUpdateUploadProgressParams) error {
	_, err := q.db.ExecContext(ctx, attachmentUpdateUploadProgress, arg.AcceptedOffset, arg.ExpiresAt, arg.ID)
	return err
}
