// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment_board_copy.sql

package query

import (
	"context"
	"time"
)

const attachmentCountCopyActiveUploads = `-- name: AttachmentCountCopyActiveUploads :one
SELECT count(*) AS active_upload_count
FROM attachment_uploads
WHERE board_id = ?1
    AND state = 'active'
`

func (q *Queries) AttachmentCountCopyActiveUploads(ctx context.Context, boardID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, attachmentCountCopyActiveUploads, boardID)
	var active_upload_count int64
	err := row.Scan(&active_upload_count)
	return active_upload_count, err
}

const attachmentInsertCopiedMetadata = `-- name: AttachmentInsertCopiedMetadata :exec
INSERT INTO attachments (
    board_id,
    id,
    origin_issue_id,
    blob_digest,
    blob_size_bytes,
    filename,
    media_type,
    lifecycle,
    created_actor,
    created_at,
    created_revision,
    removed_actor,
    removed_at,
    removed_revision
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14
)
`

type AttachmentInsertCopiedMetadataParams struct {
	BoardID         string
	ID              string
	OriginIssueID   *string
	BlobDigest      string
	BlobSizeBytes   int64
	Filename        string
	MediaType       string
	Lifecycle       string
	CreatedActor    string
	CreatedAt       time.Time
	CreatedRevision int64
	RemovedActor    *string
	RemovedAt       *time.Time
	RemovedRevision *int64
}

func (q *Queries) AttachmentInsertCopiedMetadata(ctx context.Context, arg AttachmentInsertCopiedMetadataParams) error {
	_, err := q.db.ExecContext(ctx, attachmentInsertCopiedMetadata,
		arg.BoardID,
		arg.ID,
		arg.OriginIssueID,
		arg.BlobDigest,
		arg.BlobSizeBytes,
		arg.Filename,
		arg.MediaType,
		arg.Lifecycle,
		arg.CreatedActor,
		arg.CreatedAt,
		arg.CreatedRevision,
		arg.RemovedActor,
		arg.RemovedAt,
		arg.RemovedRevision,
	)
	return err
}

const attachmentListCopyMetadata = `-- name: AttachmentListCopyMetadata :many
SELECT
    id,
    origin_issue_id,
    blob_digest,
    blob_size_bytes,
    filename,
    media_type,
    lifecycle,
    created_actor,
    created_at,
    removed_actor,
    removed_at
FROM attachments
WHERE board_id = ?1
ORDER BY id
`

type AttachmentListCopyMetadataRow struct {
	ID            string
	OriginIssueID *string
	BlobDigest    string
	BlobSizeBytes int64
	Filename      string
	MediaType     string
	Lifecycle     string
	CreatedActor  string
	CreatedAt     time.Time
	RemovedActor  *string
	RemovedAt     *time.Time
}

func (q *Queries) AttachmentListCopyMetadata(ctx context.Context, boardID string) ([]AttachmentListCopyMetadataRow, error) {
	rows, err := q.db.QueryContext(ctx, attachmentListCopyMetadata, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttachmentListCopyMetadataRow
	for rows.Next() {
		var i AttachmentListCopyMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginIssueID,
			&i.BlobDigest,
			&i.BlobSizeBytes,
			&i.Filename,
			&i.MediaType,
			&i.Lifecycle,
			&i.CreatedActor,
			&i.CreatedAt,
			&i.RemovedActor,
			&i.RemovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
