// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment_collection.sql

package query

import (
	"context"
	"time"
)

const attachmentDeleteExpiredUploadReceipts = `-- name: AttachmentDeleteExpiredUploadReceipts :exec
DELETE FROM attachment_uploads
WHERE state <> 'active'
    AND expires_at <= ?1
`

func (q *Queries) AttachmentDeleteExpiredUploadReceipts(ctx context.Context, now time.Time) error {
	_, err := q.db.ExecContext(ctx, attachmentDeleteExpiredUploadReceipts, now)
	return err
}

const attachmentExpireActiveUploads = `-- name: AttachmentExpireActiveUploads :exec
UPDATE attachment_uploads
SET state = 'expired',
    expires_at = ?1
WHERE state = 'active'
    AND expires_at <= ?2
`

type AttachmentExpireActiveUploadsParams struct {
	ReceiptExpiresAt time.Time
	Now              time.Time
}

func (q *Queries) AttachmentExpireActiveUploads(ctx context.Context, arg AttachmentExpireActiveUploadsParams) error {
	_, err := q.db.ExecContext(ctx, attachmentExpireActiveUploads, arg.ReceiptExpiresAt, arg.Now)
	return err
}

const attachmentListCollectibleUploads = `-- name: AttachmentListCollectibleUploads :many
SELECT id
FROM attachment_uploads
WHERE state <> 'active'
    OR (
        ?1
        AND state = 'active'
        AND expires_at <= ?2
    )
ORDER BY id
`

type AttachmentListCollectibleUploadsParams struct {
	IncludeExpiredActive interface{}
	Now                  time.Time
}

func (q *Queries) AttachmentListCollectibleUploads(ctx context.Context, arg AttachmentListCollectibleUploadsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, attachmentListCollectibleUploads, arg.IncludeExpiredActive, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const attachmentListRetainedBlobs = `-- name: AttachmentListRetainedBlobs :many
SELECT board_id, id, blob_digest, blob_size_bytes
FROM attachments
ORDER BY board_id, id
`

type AttachmentListRetainedBlobsRow struct {
	BoardID       string
	ID            string
	BlobDigest    string
	BlobSizeBytes int64
}

func (q *Queries) AttachmentListRetainedBlobs(ctx context.Context) ([]AttachmentListRetainedBlobsRow, error) {
	rows, err := q.db.QueryContext(ctx, attachmentListRetainedBlobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttachmentListRetainedBlobsRow
	for rows.Next() {
		var i AttachmentListRetainedBlobsRow
		if err := rows.Scan(
			&i.BoardID,
			&i.ID,
			&i.BlobDigest,
			&i.BlobSizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
