// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachment_upload_begin.sql

package query

import (
	"context"
	"time"
)

const attachmentInsertUpload = `-- name: AttachmentInsertUpload :exec
INSERT INTO attachment_uploads (
    id,
    board_id,
    origin_issue_id,
    filename,
    expected_size_bytes,
    expected_digest,
    actor,
    state,
    accepted_offset,
    expires_at,
    admitted_max_bytes
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11
)
`

type AttachmentInsertUploadParams struct {
	ID                string
	BoardID           string
	OriginIssueID     *string
	Filename          string
	ExpectedSizeBytes *int64
	ExpectedDigest    *string
	Actor             string
	State             string
	AcceptedOffset    int64
	ExpiresAt         time.Time
	AdmittedMaxBytes  int64
}

func (q *Queries) AttachmentInsertUpload(ctx context.Context, arg AttachmentInsertUploadParams) error {
	_, err := q.db.ExecContext(ctx, attachmentInsertUpload,
		arg.ID,
		arg.BoardID,
		arg.OriginIssueID,
		arg.Filename,
		arg.ExpectedSizeBytes,
		arg.ExpectedDigest,
		arg.Actor,
		arg.State,
		arg.AcceptedOffset,
		arg.ExpiresAt,
		arg.AdmittedMaxBytes,
	)
	return err
}

const attachmentTargetBoardExists = `-- name: AttachmentTargetBoardExists :one
SELECT EXISTS (
    SELECT 1
    FROM boards
    WHERE id = ?1
) AS board_exists
`

func (q *Queries) AttachmentTargetBoardExists(ctx context.Context, boardID string) (bool, error) {
	row := q.db.QueryRowContext(ctx, attachmentTargetBoardExists, boardID)
	var board_exists bool
	err := row.Scan(&board_exists)
	return board_exists, err
}

const attachmentTargetIssueExists = `-- name: AttachmentTargetIssueExists :one
SELECT EXISTS (
    SELECT 1
    FROM issues
    WHERE board_id = ?1
        AND id = ?2
) AS issue_exists
`

type AttachmentTargetIssueExistsParams struct {
	BoardID string
	IssueID string
}

func (q *Queries) AttachmentTargetIssueExists(ctx context.Context, arg AttachmentTargetIssueExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, attachmentTargetIssueExists, arg.BoardID, arg.IssueID)
	var issue_exists bool
	err := row.Scan(&issue_exists)
	return issue_exists, err
}
