// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_pins.sql

package query

import (
	"context"
	"database/sql"
)

const boardCountPins = `-- name: BoardCountPins :one
SELECT count(*)
FROM board_pins
WHERE board_id = ?1
`

func (q *Queries) BoardCountPins(ctx context.Context, boardID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, boardCountPins, boardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const boardDeletePin = `-- name: BoardDeletePin :execresult
DELETE FROM board_pins
WHERE board_id = ?1
    AND issue_uid = ?2
`

type BoardDeletePinParams struct {
	BoardID  string
	IssueUid []byte
}

func (q *Queries) BoardDeletePin(ctx context.Context, arg BoardDeletePinParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, boardDeletePin, arg.BoardID, arg.IssueUid)
}

const boardGetPinIssueReference = `-- name: BoardGetPinIssueReference :one
SELECT
    issue.id,
    issue.title,
    issue.kind,
    CAST(CASE
        WHEN issue.lifecycle <> 'open' THEN issue.lifecycle
        WHEN claim.issue_uid IS NOT NULL THEN 'in_progress'
        WHEN issue.waiting_reason IS NOT NULL THEN 'waiting'
        WHEN EXISTS (
            SELECT 1
            FROM dependencies AS dependency
            JOIN issues AS prerequisite
                ON prerequisite.uid = dependency.prerequisite_uid
            WHERE dependency.issue_uid = issue.uid
                AND prerequisite.lifecycle <> 'closed'
        ) THEN 'blocked'
        ELSE 'ready'
    END AS TEXT) AS status,
    issue.priority
FROM issues AS issue
LEFT JOIN active_claims AS claim ON claim.issue_uid = issue.uid
WHERE issue.board_id = ?1
    AND issue.id = ?2
`

type BoardGetPinIssueReferenceParams struct {
	BoardID string
	IssueID string
}

type BoardGetPinIssueReferenceRow struct {
	ID       string
	Title    string
	Kind     string
	Status   string
	Priority int64
}

func (q *Queries) BoardGetPinIssueReference(ctx context.Context, arg BoardGetPinIssueReferenceParams) (BoardGetPinIssueReferenceRow, error) {
	row := q.db.QueryRowContext(ctx, boardGetPinIssueReference, arg.BoardID, arg.IssueID)
	var i BoardGetPinIssueReferenceRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Kind,
		&i.Status,
		&i.Priority,
	)
	return i, err
}

const boardInsertPin = `-- name: BoardInsertPin :exec
INSERT INTO board_pins (board_id, issue_uid, position)
SELECT
    ?1,
    ?2,
    COALESCE(MAX(position), 0) + 1
FROM board_pins
WHERE board_id = ?1
`

type BoardInsertPinParams struct {
	BoardID  string
	IssueUid []byte
}

func (q *Queries) BoardInsertPin(ctx context.Context, arg BoardInsertPinParams) error {
	_, err := q.db.ExecContext(ctx, boardInsertPin, arg.BoardID, arg.IssueUid)
	return err
}

const boardListPinIDs = `-- name: BoardListPinIDs :many
SELECT issue.id
FROM board_pins AS pin
JOIN issues AS issue ON issue.uid = pin.issue_uid
WHERE pin.board_id = ?1
ORDER BY pin.position
`

func (q *Queries) BoardListPinIDs(ctx context.Context, boardID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, boardListPinIDs, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListPinReferences = `-- name: BoardListPinReferences :many
SELECT
    issue.id,
    issue.title,
    issue.kind,
    CAST(CASE
        WHEN issue.lifecycle <> 'open' THEN issue.lifecycle
        WHEN claim.issue_uid IS NOT NULL THEN 'in_progress'
        WHEN issue.waiting_reason IS NOT NULL THEN 'waiting'
        WHEN EXISTS (
            SELECT 1
            FROM dependencies AS dependency
            JOIN issues AS prerequisite
                ON prerequisite.uid = dependency.prerequisite_uid
            WHERE dependency.issue_uid = issue.uid
                AND prerequisite.lifecycle <> 'closed'
        ) THEN 'blocked'
        ELSE 'ready'
    END AS TEXT) AS status,
    issue.priority
FROM board_pins AS pin
JOIN issues AS issue
    ON issue.board_id = pin.board_id
    AND issue.uid = pin.issue_uid
LEFT JOIN active_claims AS claim ON claim.issue_uid = issue.uid
WHERE pin.board_id = ?1
ORDER BY pin.position
`

type BoardListPinReferencesRow struct {
	ID       string
	Title    string
	Kind     string
	Status   string
	Priority int64
}

func (q *Queries) BoardListPinReferences(ctx context.Context, boardID string) ([]BoardListPinReferencesRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListPinReferences, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListPinReferencesRow
	for rows.Next() {
		var i BoardListPinReferencesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Kind,
			&i.Status,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardPinExists = `-- name: BoardPinExists :one
SELECT EXISTS (
    SELECT 1
    FROM board_pins
    WHERE board_id = ?1
        AND issue_uid = ?2
)
`

type BoardPinExistsParams struct {
	BoardID  string
	IssueUid []byte
}

func (q *Queries) BoardPinExists(ctx context.Context, arg BoardPinExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, boardPinExists, arg.BoardID, arg.IssueUid)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
