// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_copy_import.sql

package query

import (
	"context"
	"time"
)

const boardCopyLogIDExists = `-- name: BoardCopyLogIDExists :one
SELECT EXISTS (
    SELECT 1
    FROM issue_log_entries
    WHERE id = ?1
) AS log_exists
`

func (q *Queries) BoardCopyLogIDExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, boardCopyLogIDExists, id)
	var log_exists bool
	err := row.Scan(&log_exists)
	return log_exists, err
}

const boardGetCopyReceipt = `-- name: BoardGetCopyReceipt :one
SELECT
    id,
    snapshot_digest,
    source_revision,
    destination_project_id,
    destination_name,
    destination_board_id,
    destination_revision
FROM board_copy_receipts
WHERE source_lineage_id = ?1
    AND source_board_id = ?2
    AND snapshot_version = ?3
ORDER BY id
LIMIT 1
`

type BoardGetCopyReceiptParams struct {
	SourceLineageID string
	SourceBoardID   string
	SnapshotVersion int64
}

type BoardGetCopyReceiptRow struct {
	ID                   int64
	SnapshotDigest       string
	SourceRevision       int64
	DestinationProjectID string
	DestinationName      string
	DestinationBoardID   string
	DestinationRevision  int64
}

func (q *Queries) BoardGetCopyReceipt(ctx context.Context, arg BoardGetCopyReceiptParams) (BoardGetCopyReceiptRow, error) {
	row := q.db.QueryRowContext(ctx, boardGetCopyReceipt, arg.SourceLineageID, arg.SourceBoardID, arg.SnapshotVersion)
	var i BoardGetCopyReceiptRow
	err := row.Scan(
		&i.ID,
		&i.SnapshotDigest,
		&i.SourceRevision,
		&i.DestinationProjectID,
		&i.DestinationName,
		&i.DestinationBoardID,
		&i.DestinationRevision,
	)
	return i, err
}

const boardInsertCopiedIssue = `-- name: BoardInsertCopiedIssue :exec
INSERT INTO issues (
    id,
    board_id,
    title,
    kind,
    lifecycle,
    priority,
    created_at,
    updated_at,
    closed_at,
    waiting_reason,
    waiting_since,
    summary,
    details,
    revision
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10,
    ?11,
    ?12,
    ?13,
    ?14
)
`

type BoardInsertCopiedIssueParams struct {
	ID            string
	BoardID       string
	Title         string
	Kind          string
	Lifecycle     string
	Priority      int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ClosedAt      *time.Time
	WaitingReason *string
	WaitingSince  *time.Time
	Summary       *string
	Details       *string
	Revision      int64
}

func (q *Queries) BoardInsertCopiedIssue(ctx context.Context, arg BoardInsertCopiedIssueParams) error {
	_, err := q.db.ExecContext(ctx, boardInsertCopiedIssue,
		arg.ID,
		arg.BoardID,
		arg.Title,
		arg.Kind,
		arg.Lifecycle,
		arg.Priority,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ClosedAt,
		arg.WaitingReason,
		arg.WaitingSince,
		arg.Summary,
		arg.Details,
		arg.Revision,
	)
	return err
}

const boardInsertCopyAttachmentMapping = `-- name: BoardInsertCopyAttachmentMapping :exec
INSERT INTO board_copy_attachment_mappings (
    receipt_id,
    source_id,
    destination_id
) VALUES (
    ?1,
    ?2,
    ?3
)
`

type BoardInsertCopyAttachmentMappingParams struct {
	ReceiptID     int64
	SourceID      string
	DestinationID string
}

func (q *Queries) BoardInsertCopyAttachmentMapping(ctx context.Context, arg BoardInsertCopyAttachmentMappingParams) error {
	_, err := q.db.ExecContext(ctx, boardInsertCopyAttachmentMapping, arg.ReceiptID, arg.SourceID, arg.DestinationID)
	return err
}

const boardInsertCopyIssueMapping = `-- name: BoardInsertCopyIssueMapping :exec
INSERT INTO board_copy_issue_mappings (
    receipt_id,
    source_id,
    destination_id
) VALUES (
    ?1,
    ?2,
    ?3
)
`

type BoardInsertCopyIssueMappingParams struct {
	ReceiptID     int64
	SourceID      string
	DestinationID string
}

func (q *Queries) BoardInsertCopyIssueMapping(ctx context.Context, arg BoardInsertCopyIssueMappingParams) error {
	_, err := q.db.ExecContext(ctx, boardInsertCopyIssueMapping, arg.ReceiptID, arg.SourceID, arg.DestinationID)
	return err
}

const boardInsertCopyLogMapping = `-- name: BoardInsertCopyLogMapping :exec
INSERT INTO board_copy_log_mappings (
    receipt_id,
    source_id,
    destination_id
) VALUES (
    ?1,
    ?2,
    ?3
)
`

type BoardInsertCopyLogMappingParams struct {
	ReceiptID     int64
	SourceID      string
	DestinationID string
}

func (q *Queries) BoardInsertCopyLogMapping(ctx context.Context, arg BoardInsertCopyLogMappingParams) error {
	_, err := q.db.ExecContext(ctx, boardInsertCopyLogMapping, arg.ReceiptID, arg.SourceID, arg.DestinationID)
	return err
}

const boardInsertCopyReceipt = `-- name: BoardInsertCopyReceipt :one
INSERT INTO board_copy_receipts (
    source_lineage_id,
    source_board_id,
    snapshot_version,
    snapshot_digest,
    source_revision,
    destination_project_id,
    destination_name,
    destination_board_id,
    destination_revision,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10
)
RETURNING id
`

type BoardInsertCopyReceiptParams struct {
	SourceLineageID      string
	SourceBoardID        string
	SnapshotVersion      int64
	SnapshotDigest       string
	SourceRevision       int64
	DestinationProjectID string
	DestinationName      string
	DestinationBoardID   string
	DestinationRevision  int64
	CreatedAt            time.Time
}

func (q *Queries) BoardInsertCopyReceipt(ctx context.Context, arg BoardInsertCopyReceiptParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, boardInsertCopyReceipt,
		arg.SourceLineageID,
		arg.SourceBoardID,
		arg.SnapshotVersion,
		arg.SnapshotDigest,
		arg.SourceRevision,
		arg.DestinationProjectID,
		arg.DestinationName,
		arg.DestinationBoardID,
		arg.DestinationRevision,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const boardListCopyAttachmentMappings = `-- name: BoardListCopyAttachmentMappings :many
SELECT source_id, destination_id
FROM board_copy_attachment_mappings
WHERE receipt_id = ?1
ORDER BY source_id
`

type BoardListCopyAttachmentMappingsRow struct {
	SourceID      string
	DestinationID string
}

func (q *Queries) BoardListCopyAttachmentMappings(ctx context.Context, receiptID int64) ([]BoardListCopyAttachmentMappingsRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListCopyAttachmentMappings, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListCopyAttachmentMappingsRow
	for rows.Next() {
		var i BoardListCopyAttachmentMappingsRow
		if err := rows.Scan(&i.SourceID, &i.DestinationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListCopyIssueMappings = `-- name: BoardListCopyIssueMappings :many
SELECT source_id, destination_id
FROM board_copy_issue_mappings
WHERE receipt_id = ?1
ORDER BY source_id
`

type BoardListCopyIssueMappingsRow struct {
	SourceID      string
	DestinationID string
}

func (q *Queries) BoardListCopyIssueMappings(ctx context.Context, receiptID int64) ([]BoardListCopyIssueMappingsRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListCopyIssueMappings, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListCopyIssueMappingsRow
	for rows.Next() {
		var i BoardListCopyIssueMappingsRow
		if err := rows.Scan(&i.SourceID, &i.DestinationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListCopyLogMappings = `-- name: BoardListCopyLogMappings :many
SELECT source_id, destination_id
FROM board_copy_log_mappings
WHERE receipt_id = ?1
ORDER BY source_id
`

type BoardListCopyLogMappingsRow struct {
	SourceID      string
	DestinationID string
}

func (q *Queries) BoardListCopyLogMappings(ctx context.Context, receiptID int64) ([]BoardListCopyLogMappingsRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListCopyLogMappings, receiptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListCopyLogMappingsRow
	for rows.Next() {
		var i BoardListCopyLogMappingsRow
		if err := rows.Scan(&i.SourceID, &i.DestinationID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
