// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_copy_snapshot.sql

package query

import (
	"context"
	"time"
)

const boardCountCopyActiveClaims = `-- name: BoardCountCopyActiveClaims :one
SELECT count(*) AS active_claim_count
FROM active_claims
WHERE board_id = ?1
`

func (q *Queries) BoardCountCopyActiveClaims(ctx context.Context, boardID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, boardCountCopyActiveClaims, boardID)
	var active_claim_count int64
	err := row.Scan(&active_claim_count)
	return active_claim_count, err
}

const boardGetCopySource = `-- name: BoardGetCopySource :one
SELECT
    board.id AS board_id,
    board.name AS board_name,
    board.description AS board_description,
    board.created_at AS board_created_at,
    project.issue_id_prefix AS project_issue_id_prefix,
    project.issue_id_strategy AS project_issue_id_strategy,
    project.issue_summary_max_bytes AS project_issue_summary_max_bytes,
    project.attachment_max_bytes AS project_attachment_max_bytes,
    board.issue_id_prefix AS board_issue_id_prefix,
    board.issue_id_strategy AS board_issue_id_strategy,
    board.issue_summary_max_bytes AS board_issue_summary_max_bytes,
    board.attachment_max_bytes AS board_attachment_max_bytes
FROM boards AS board
JOIN projects AS project ON project.id = board.project_id
WHERE board.id = ?1
`

type BoardGetCopySourceRow struct {
	BoardID                     string
	BoardName                   string
	BoardDescription            *string
	BoardCreatedAt              time.Time
	ProjectIssueIDPrefix        *string
	ProjectIssueIDStrategy      *string
	ProjectIssueSummaryMaxBytes *int64
	ProjectAttachmentMaxBytes   *int64
	BoardIssueIDPrefix          *string
	BoardIssueIDStrategy        *string
	BoardIssueSummaryMaxBytes   *int64
	BoardAttachmentMaxBytes     *int64
}

func (q *Queries) BoardGetCopySource(ctx context.Context, boardID string) (BoardGetCopySourceRow, error) {
	row := q.db.QueryRowContext(ctx, boardGetCopySource, boardID)
	var i BoardGetCopySourceRow
	err := row.Scan(
		&i.BoardID,
		&i.BoardName,
		&i.BoardDescription,
		&i.BoardCreatedAt,
		&i.ProjectIssueIDPrefix,
		&i.ProjectIssueIDStrategy,
		&i.ProjectIssueSummaryMaxBytes,
		&i.ProjectAttachmentMaxBytes,
		&i.BoardIssueIDPrefix,
		&i.BoardIssueIDStrategy,
		&i.BoardIssueSummaryMaxBytes,
		&i.BoardAttachmentMaxBytes,
	)
	return i, err
}

const boardListCopyCheckpoints = `-- name: BoardListCopyCheckpoints :many
SELECT issue_id, outcome, reason, decided_at
FROM checkpoint_decisions
WHERE board_id = ?1
ORDER BY issue_id
`

type BoardListCopyCheckpointsRow struct {
	IssueID   string
	Outcome   string
	Reason    string
	DecidedAt time.Time
}

func (q *Queries) BoardListCopyCheckpoints(ctx context.Context, boardID string) ([]BoardListCopyCheckpointsRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListCopyCheckpoints, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListCopyCheckpointsRow
	for rows.Next() {
		var i BoardListCopyCheckpointsRow
		if err := rows.Scan(
			&i.IssueID,
			&i.Outcome,
			&i.Reason,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListCopyContainment = `-- name: BoardListCopyContainment :many
SELECT child_id, parent_id
FROM containment
WHERE board_id = ?1
ORDER BY child_id
`

type BoardListCopyContainmentRow struct {
	ChildID  string
	ParentID string
}

func (q *Queries) BoardListCopyContainment(ctx context.Context, boardID string) ([]BoardListCopyContainmentRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListCopyContainment, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListCopyContainmentRow
	for rows.Next() {
		var i BoardListCopyContainmentRow
		if err := rows.Scan(&i.ChildID, &i.ParentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListCopyDependencies = `-- name: BoardListCopyDependencies :many
SELECT issue_id, prerequisite_id
FROM dependencies
WHERE board_id = ?1
ORDER BY issue_id, prerequisite_id
`

type BoardListCopyDependenciesRow struct {
	IssueID        string
	PrerequisiteID string
}

func (q *Queries) BoardListCopyDependencies(ctx context.Context, boardID string) ([]BoardListCopyDependenciesRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListCopyDependencies, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListCopyDependenciesRow
	for rows.Next() {
		var i BoardListCopyDependenciesRow
		if err := rows.Scan(&i.IssueID, &i.PrerequisiteID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListCopyExternalKeys = `-- name: BoardListCopyExternalKeys :many
SELECT external_key, issue_id
FROM issue_external_keys
WHERE board_id = ?1
ORDER BY external_key
`

type BoardListCopyExternalKeysRow struct {
	ExternalKey string
	IssueID     string
}

func (q *Queries) BoardListCopyExternalKeys(ctx context.Context, boardID string) ([]BoardListCopyExternalKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListCopyExternalKeys, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListCopyExternalKeysRow
	for rows.Next() {
		var i BoardListCopyExternalKeysRow
		if err := rows.Scan(&i.ExternalKey, &i.IssueID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListCopyIssues = `-- name: BoardListCopyIssues :many
SELECT
    id,
    title,
    kind,
    lifecycle,
    priority,
    created_at,
    updated_at,
    closed_at,
    waiting_reason,
    waiting_since,
    summary,
    details
FROM issues
WHERE board_id = ?1
ORDER BY id
`

type BoardListCopyIssuesRow struct {
	ID            string
	Title         string
	Kind          string
	Lifecycle     string
	Priority      int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	ClosedAt      *time.Time
	WaitingReason *string
	WaitingSince  *time.Time
	Summary       *string
	Details       *string
}

func (q *Queries) BoardListCopyIssues(ctx context.Context, boardID string) ([]BoardListCopyIssuesRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListCopyIssues, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListCopyIssuesRow
	for rows.Next() {
		var i BoardListCopyIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Kind,
			&i.Lifecycle,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.WaitingReason,
			&i.WaitingSince,
			&i.Summary,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListCopyLabels = `-- name: BoardListCopyLabels :many
SELECT issue_id, label
FROM issue_labels
WHERE board_id = ?1
ORDER BY issue_id, label
`

type BoardListCopyLabelsRow struct {
	IssueID string
	Label   string
}

func (q *Queries) BoardListCopyLabels(ctx context.Context, boardID string) ([]BoardListCopyLabelsRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListCopyLabels, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListCopyLabelsRow
	for rows.Next() {
		var i BoardListCopyLabelsRow
		if err := rows.Scan(&i.IssueID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListCopyLogEntries = `-- name: BoardListCopyLogEntries :many
SELECT id, issue_id, kind, author, committer, body, created_at, next_action
FROM issue_log_entries
WHERE board_id = ?1
ORDER BY local_sequence
`

type BoardListCopyLogEntriesRow struct {
	ID         string
	IssueID    string
	Kind       string
	Author     *string
	Committer  *string
	Body       string
	CreatedAt  *time.Time
	NextAction *string
}

func (q *Queries) BoardListCopyLogEntries(ctx context.Context, boardID string) ([]BoardListCopyLogEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListCopyLogEntries, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListCopyLogEntriesRow
	for rows.Next() {
		var i BoardListCopyLogEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Kind,
			&i.Author,
			&i.Committer,
			&i.Body,
			&i.CreatedAt,
			&i.NextAction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListCopyResults = `-- name: BoardListCopyResults :many
SELECT issue_id, body
FROM issue_results
WHERE board_id = ?1
ORDER BY issue_id
`

type BoardListCopyResultsRow struct {
	IssueID string
	Body    string
}

func (q *Queries) BoardListCopyResults(ctx context.Context, boardID string) ([]BoardListCopyResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListCopyResults, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListCopyResultsRow
	for rows.Next() {
		var i BoardListCopyResultsRow
		if err := rows.Scan(&i.IssueID, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListCopyStates = `-- name: BoardListCopyStates :many
SELECT issue_id, body, author, updated_at, snapshot_log_entry_id, next_action
FROM issue_states
WHERE board_id = ?1
ORDER BY issue_id
`

type BoardListCopyStatesRow struct {
	IssueID            string
	Body               string
	Author             *string
	UpdatedAt          *time.Time
	SnapshotLogEntryID *string
	NextAction         *string
}

func (q *Queries) BoardListCopyStates(ctx context.Context, boardID string) ([]BoardListCopyStatesRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListCopyStates, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListCopyStatesRow
	for rows.Next() {
		var i BoardListCopyStatesRow
		if err := rows.Scan(
			&i.IssueID,
			&i.Body,
			&i.Author,
			&i.UpdatedAt,
			&i.SnapshotLogEntryID,
			&i.NextAction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
