// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_checkpoints.sql

package query

import (
	"context"
	"time"
)

const boardInsertCheckpointDecision = `-- name: BoardInsertCheckpointDecision :exec
INSERT INTO checkpoint_decisions (
    issue_id,
    board_id,
    outcome,
    reason,
    decided_at,
    revision
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
`

type BoardInsertCheckpointDecisionParams struct {
	IssueID   string
	BoardID   string
	Outcome   string
	Reason    string
	DecidedAt time.Time
	Revision  int64
}

func (q *Queries) BoardInsertCheckpointDecision(ctx context.Context, arg BoardInsertCheckpointDecisionParams) error {
	_, err := q.db.ExecContext(ctx, boardInsertCheckpointDecision,
		arg.IssueID,
		arg.BoardID,
		arg.Outcome,
		arg.Reason,
		arg.DecidedAt,
		arg.Revision,
	)
	return err
}
