// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_graph_mutation.sql

package query

import (
	"context"
)

const boardDeleteIssueDependencies = `-- name: BoardDeleteIssueDependencies :exec
DELETE FROM dependencies
WHERE board_id = ?1
    AND issue_id = ?2
`

type BoardDeleteIssueDependenciesParams struct {
	BoardID string
	IssueID string
}

func (q *Queries) BoardDeleteIssueDependencies(ctx context.Context, arg BoardDeleteIssueDependenciesParams) error {
	_, err := q.db.ExecContext(ctx, boardDeleteIssueDependencies, arg.BoardID, arg.IssueID)
	return err
}

const boardDeleteIssueParent = `-- name: BoardDeleteIssueParent :exec
DELETE FROM containment
WHERE board_id = ?1
    AND child_id = ?2
`

type BoardDeleteIssueParentParams struct {
	BoardID string
	ChildID string
}

func (q *Queries) BoardDeleteIssueParent(ctx context.Context, arg BoardDeleteIssueParentParams) error {
	_, err := q.db.ExecContext(ctx, boardDeleteIssueParent, arg.BoardID, arg.ChildID)
	return err
}

const boardInsertIssueDependency = `-- name: BoardInsertIssueDependency :exec
INSERT INTO dependencies (
    board_id,
    issue_id,
    prerequisite_id
) VALUES (
    ?1,
    ?2,
    ?3
)
`

type BoardInsertIssueDependencyParams struct {
	BoardID        string
	IssueID        string
	PrerequisiteID string
}

func (q *Queries) BoardInsertIssueDependency(ctx context.Context, arg BoardInsertIssueDependencyParams) error {
	_, err := q.db.ExecContext(ctx, boardInsertIssueDependency, arg.BoardID, arg.IssueID, arg.PrerequisiteID)
	return err
}

const boardInsertIssueExternalKey = `-- name: BoardInsertIssueExternalKey :exec
INSERT INTO issue_external_keys (
    board_id,
    external_key,
    issue_id
) VALUES (
    ?1,
    ?2,
    ?3
)
`

type BoardInsertIssueExternalKeyParams struct {
	BoardID     string
	ExternalKey string
	IssueID     string
}

func (q *Queries) BoardInsertIssueExternalKey(ctx context.Context, arg BoardInsertIssueExternalKeyParams) error {
	_, err := q.db.ExecContext(ctx, boardInsertIssueExternalKey, arg.BoardID, arg.ExternalKey, arg.IssueID)
	return err
}

const boardInsertIssueParent = `-- name: BoardInsertIssueParent :exec
INSERT INTO containment (
    board_id,
    child_id,
    parent_id
) VALUES (
    ?1,
    ?2,
    ?3
)
`

type BoardInsertIssueParentParams struct {
	BoardID  string
	ChildID  string
	ParentID string
}

func (q *Queries) BoardInsertIssueParent(ctx context.Context, arg BoardInsertIssueParentParams) error {
	_, err := q.db.ExecContext(ctx, boardInsertIssueParent, arg.BoardID, arg.ChildID, arg.ParentID)
	return err
}
