// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_issue_records.sql

package query

import (
	"context"
	"time"
)

const boardDeleteIssueState = `-- name: BoardDeleteIssueState :exec
DELETE FROM issue_states
WHERE board_id = ?1
    AND issue_uid = ?2
`

type BoardDeleteIssueStateParams struct {
	BoardID  string
	IssueUid []byte
}

func (q *Queries) BoardDeleteIssueState(ctx context.Context, arg BoardDeleteIssueStateParams) error {
	_, err := q.db.ExecContext(ctx, boardDeleteIssueState, arg.BoardID, arg.IssueUid)
	return err
}

const boardInsertIssueLogEntry = `-- name: BoardInsertIssueLogEntry :exec
INSERT INTO issue_log_entries (
    id,
    board_id,
    issue_uid,
    kind,
    author,
    committer,
    body,
    next_action,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9
)
`

type BoardInsertIssueLogEntryParams struct {
	ID         string
	BoardID    string
	IssueUid   []byte
	Kind       string
	Author     *string
	Committer  *string
	Body       string
	NextAction *string
	CreatedAt  *time.Time
}

func (q *Queries) BoardInsertIssueLogEntry(ctx context.Context, arg BoardInsertIssueLogEntryParams) error {
	_, err := q.db.ExecContext(ctx, boardInsertIssueLogEntry,
		arg.ID,
		arg.BoardID,
		arg.IssueUid,
		arg.Kind,
		arg.Author,
		arg.Committer,
		arg.Body,
		arg.NextAction,
		arg.CreatedAt,
	)
	return err
}

const boardListIssueLogEntriesAscending = `-- name: BoardListIssueLogEntriesAscending :many
SELECT log.id, issue.id AS issue_id, log.kind, log.author, log.committer,
    log.body, log.next_action, log.created_at
FROM issue_log_entries AS log
JOIN issues AS issue ON issue.uid = log.issue_uid
WHERE log.board_id = ?1
    AND log.issue_uid = ?2
ORDER BY log.local_sequence
LIMIT ?3
`

type BoardListIssueLogEntriesAscendingParams struct {
	BoardID    string
	IssueUid   []byte
	LimitCount int64
}

type BoardListIssueLogEntriesAscendingRow struct {
	ID         string
	IssueID    string
	Kind       string
	Author     *string
	Committer  *string
	Body       string
	NextAction *string
	CreatedAt  *time.Time
}

func (q *Queries) BoardListIssueLogEntriesAscending(ctx context.Context, arg BoardListIssueLogEntriesAscendingParams) ([]BoardListIssueLogEntriesAscendingRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListIssueLogEntriesAscending, arg.BoardID, arg.IssueUid, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListIssueLogEntriesAscendingRow
	for rows.Next() {
		var i BoardListIssueLogEntriesAscendingRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Kind,
			&i.Author,
			&i.Committer,
			&i.Body,
			&i.NextAction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListIssueLogEntriesDescending = `-- name: BoardListIssueLogEntriesDescending :many
SELECT log.id, issue.id AS issue_id, log.kind, log.author, log.committer,
    log.body, log.next_action, log.created_at
FROM issue_log_entries AS log
JOIN issues AS issue ON issue.uid = log.issue_uid
WHERE log.board_id = ?1
    AND log.issue_uid = ?2
ORDER BY log.local_sequence DESC
LIMIT ?3
`

type BoardListIssueLogEntriesDescendingParams struct {
	BoardID    string
	IssueUid   []byte
	LimitCount int64
}

type BoardListIssueLogEntriesDescendingRow struct {
	ID         string
	IssueID    string
	Kind       string
	Author     *string
	Committer  *string
	Body       string
	NextAction *string
	CreatedAt  *time.Time
}

func (q *Queries) BoardListIssueLogEntriesDescending(ctx context.Context, arg BoardListIssueLogEntriesDescendingParams) ([]BoardListIssueLogEntriesDescendingRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListIssueLogEntriesDescending, arg.BoardID, arg.IssueUid, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListIssueLogEntriesDescendingRow
	for rows.Next() {
		var i BoardListIssueLogEntriesDescendingRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Kind,
			&i.Author,
			&i.Committer,
			&i.Body,
			&i.NextAction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardReadIssueLogEntry = `-- name: BoardReadIssueLogEntry :one
SELECT log.id, issue.id AS issue_id, log.kind, log.author, log.committer,
    log.body, log.next_action, log.created_at
FROM issue_log_entries AS log
JOIN issues AS issue ON issue.uid = log.issue_uid
WHERE log.board_id = ?1
    AND log.id = ?2
`

type BoardReadIssueLogEntryParams struct {
	BoardID string
	LogID   string
}

type BoardReadIssueLogEntryRow struct {
	ID         string
	IssueID    string
	Kind       string
	Author     *string
	Committer  *string
	Body       string
	NextAction *string
	CreatedAt  *time.Time
}

func (q *Queries) BoardReadIssueLogEntry(ctx context.Context, arg BoardReadIssueLogEntryParams) (BoardReadIssueLogEntryRow, error) {
	row := q.db.QueryRowContext(ctx, boardReadIssueLogEntry, arg.BoardID, arg.LogID)
	var i BoardReadIssueLogEntryRow
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.Kind,
		&i.Author,
		&i.Committer,
		&i.Body,
		&i.NextAction,
		&i.CreatedAt,
	)
	return i, err
}

const boardReadIssueResult = `-- name: BoardReadIssueResult :one
SELECT issue.id, issue.title, result.body
FROM issues AS issue
JOIN issue_results AS result ON result.issue_uid = issue.uid
WHERE issue.board_id = ?1
    AND issue.uid = ?2
`

type BoardReadIssueResultParams struct {
	BoardID  string
	IssueUid []byte
}

type BoardReadIssueResultRow struct {
	ID    string
	Title string
	Body  string
}

func (q *Queries) BoardReadIssueResult(ctx context.Context, arg BoardReadIssueResultParams) (BoardReadIssueResultRow, error) {
	row := q.db.QueryRowContext(ctx, boardReadIssueResult, arg.BoardID, arg.IssueUid)
	var i BoardReadIssueResultRow
	err := row.Scan(&i.ID, &i.Title, &i.Body)
	return i, err
}

const boardUpsertIssueResult = `-- name: BoardUpsertIssueResult :exec
INSERT INTO issue_results (issue_uid, board_id, body)
VALUES (
    ?1,
    ?2,
    ?3
)
ON CONFLICT(issue_uid) DO UPDATE SET body = excluded.body
`

type BoardUpsertIssueResultParams struct {
	IssueUid []byte
	BoardID  string
	Body     string
}

func (q *Queries) BoardUpsertIssueResult(ctx context.Context, arg BoardUpsertIssueResultParams) error {
	_, err := q.db.ExecContext(ctx, boardUpsertIssueResult, arg.IssueUid, arg.BoardID, arg.Body)
	return err
}

const boardUpsertIssueState = `-- name: BoardUpsertIssueState :exec
INSERT INTO issue_states (
    issue_uid,
    board_id,
    body,
    next_action,
    author,
    updated_at,
    snapshot_log_entry_id
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
)
ON CONFLICT(issue_uid) DO UPDATE SET
    body = excluded.body,
    next_action = excluded.next_action,
    author = excluded.author,
    updated_at = excluded.updated_at,
    snapshot_log_entry_id = excluded.snapshot_log_entry_id
`

type BoardUpsertIssueStateParams struct {
	IssueUid           []byte
	BoardID            string
	Body               string
	NextAction         *string
	Author             *string
	UpdatedAt          *time.Time
	SnapshotLogEntryID *string
}

func (q *Queries) BoardUpsertIssueState(ctx context.Context, arg BoardUpsertIssueStateParams) error {
	_, err := q.db.ExecContext(ctx, boardUpsertIssueState,
		arg.IssueUid,
		arg.BoardID,
		arg.Body,
		arg.NextAction,
		arg.Author,
		arg.UpdatedAt,
		arg.SnapshotLogEntryID,
	)
	return err
}
