// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_information.sql

package query

import (
	"context"
)

const boardCountInventoryIssues = `-- name: BoardCountInventoryIssues :one
SELECT COUNT(*)
FROM issues
WHERE board_id = ?1
`

func (q *Queries) BoardCountInventoryIssues(ctx context.Context, boardID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, boardCountInventoryIssues, boardID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const boardCountInventoryIssuesByStatus = `-- name: BoardCountInventoryIssuesByStatus :one
SELECT COUNT(*)
FROM issues AS issue
LEFT JOIN active_claims AS claim ON claim.issue_id = issue.id
WHERE issue.board_id = ?1
    AND CASE
        WHEN issue.lifecycle <> 'open' THEN issue.lifecycle
        WHEN claim.issue_id IS NOT NULL THEN 'in_progress'
        WHEN issue.waiting_reason IS NOT NULL THEN 'waiting'
        WHEN EXISTS (
            SELECT 1
            FROM dependencies AS dependency
            JOIN issues AS prerequisite ON prerequisite.id = dependency.prerequisite_id
            WHERE dependency.issue_id = issue.id
                AND prerequisite.lifecycle <> 'closed'
        ) THEN 'blocked'
        ELSE 'ready'
    END = ?2
`

type BoardCountInventoryIssuesByStatusParams struct {
	BoardID string
	Status  string
}

func (q *Queries) BoardCountInventoryIssuesByStatus(ctx context.Context, arg BoardCountInventoryIssuesByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, boardCountInventoryIssuesByStatus, arg.BoardID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}
