// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_completion.sql

package query

import (
	"context"
)

const boardListCompletionActors = `-- name: BoardListCompletionActors :many
SELECT attributed.actor
FROM (
    SELECT log_entry.author AS actor
    FROM issue_log_entries AS log_entry
    WHERE log_entry.board_id = ?1
        AND log_entry.author IS NOT NULL
    UNION
    SELECT committed_log_entry.committer AS actor
    FROM issue_log_entries AS committed_log_entry
    WHERE committed_log_entry.board_id = ?1
        AND committed_log_entry.committer IS NOT NULL
    UNION
    SELECT state.author AS actor
    FROM issue_states AS state
    WHERE state.board_id = ?1
        AND state.author IS NOT NULL
    UNION
    SELECT claim.actor
    FROM active_claims AS claim
    WHERE claim.board_id = ?1
    UNION
    SELECT attachment.created_actor
    FROM attachments AS attachment
    WHERE attachment.board_id = ?1
    UNION
    SELECT removed_attachment.removed_actor
    FROM attachments AS removed_attachment
    WHERE removed_attachment.board_id = ?1
        AND removed_attachment.removed_actor IS NOT NULL
    UNION
    SELECT upload.actor
    FROM attachment_uploads AS upload
    WHERE upload.board_id = ?1
) AS attributed
ORDER BY attributed.actor
`

func (q *Queries) BoardListCompletionActors(ctx context.Context, scopeBoardID string) ([]*string, error) {
	rows, err := q.db.QueryContext(ctx, boardListCompletionActors, scopeBoardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var actor *string
		if err := rows.Scan(&actor); err != nil {
			return nil, err
		}
		items = append(items, actor)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListCompletionIssueIDs = `-- name: BoardListCompletionIssueIDs :many
SELECT id
FROM issues
WHERE board_id = ?1
ORDER BY priority, created_at, id
`

func (q *Queries) BoardListCompletionIssueIDs(ctx context.Context, boardID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, boardListCompletionIssueIDs, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListCompletionLabels = `-- name: BoardListCompletionLabels :many
SELECT DISTINCT label
FROM issue_labels
WHERE board_id = ?1
ORDER BY label
`

func (q *Queries) BoardListCompletionLabels(ctx context.Context, boardID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, boardListCompletionLabels, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
