// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_mutation.sql

package query

import (
	"context"
	"database/sql"
	"time"
)

const boardGetRevision = `-- name: BoardGetRevision :one
SELECT revision, archived_at
FROM boards
WHERE id = ?1
`

type BoardGetRevisionRow struct {
	Revision   int64
	ArchivedAt *time.Time
}

// Issue writers read lifecycle and revision together through their immediate
// transaction, preventing archive and mutation acceptance from interleaving.
func (q *Queries) BoardGetRevision(ctx context.Context, id string) (BoardGetRevisionRow, error) {
	row := q.db.QueryRowContext(ctx, boardGetRevision, id)
	var i BoardGetRevisionRow
	err := row.Scan(&i.Revision, &i.ArchivedAt)
	return i, err
}

const boardPublishIssueRevision = `-- name: BoardPublishIssueRevision :execresult
UPDATE issues
SET revision = ?1
WHERE board_id = ?2
    AND id = ?3
`

type BoardPublishIssueRevisionParams struct {
	Revision int64
	BoardID  string
	IssueID  string
}

func (q *Queries) BoardPublishIssueRevision(ctx context.Context, arg BoardPublishIssueRevisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, boardPublishIssueRevision, arg.Revision, arg.BoardID, arg.IssueID)
}

const boardPublishRevision = `-- name: BoardPublishRevision :execresult
UPDATE boards
SET revision = ?1
WHERE id = ?2
    AND revision = ?3
`

type BoardPublishRevisionParams struct {
	Revision         int64
	ID               string
	PreviousRevision int64
}

func (q *Queries) BoardPublishRevision(ctx context.Context, arg BoardPublishRevisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, boardPublishRevision, arg.Revision, arg.ID, arg.PreviousRevision)
}
