// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_issue_references.sql

package query

import (
	"context"
	"strings"
)

const boardResolveIssueReferences = `-- name: BoardResolveIssueReferences :many
SELECT id
FROM issues
WHERE board_id = ?1
    AND id IN (/*SLICE:issue_ids*/?)
`

type BoardResolveIssueReferencesParams struct {
	BoardID  string
	IssueIDs []string
}

func (q *Queries) BoardResolveIssueReferences(ctx context.Context, arg BoardResolveIssueReferencesParams) ([]string, error) {
	query := boardResolveIssueReferences
	var queryParams []interface{}
	queryParams = append(queryParams, arg.BoardID)
	if len(arg.IssueIDs) > 0 {
		for _, v := range arg.IssueIDs {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:issue_ids*/?", strings.Repeat(",?", len(arg.IssueIDs))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:issue_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardResolveLogReferences = `-- name: BoardResolveLogReferences :many
SELECT id, issue_id
FROM issue_log_entries
WHERE board_id = ?1
    AND id IN (/*SLICE:log_ids*/?)
`

type BoardResolveLogReferencesParams struct {
	BoardID string
	LogIDs  []string
}

type BoardResolveLogReferencesRow struct {
	ID      string
	IssueID string
}

func (q *Queries) BoardResolveLogReferences(ctx context.Context, arg BoardResolveLogReferencesParams) ([]BoardResolveLogReferencesRow, error) {
	query := boardResolveLogReferences
	var queryParams []interface{}
	queryParams = append(queryParams, arg.BoardID)
	if len(arg.LogIDs) > 0 {
		for _, v := range arg.LogIDs {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:log_ids*/?", strings.Repeat(",?", len(arg.LogIDs))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:log_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardResolveLogReferencesRow
	for rows.Next() {
		var i BoardResolveLogReferencesRow
		if err := rows.Scan(&i.ID, &i.IssueID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
