// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_graph_editing.sql

package query

import (
	"context"
)

const boardListEditContainmentAncestorIDs = `-- name: BoardListEditContainmentAncestorIDs :many
WITH RECURSIVE ancestors AS (
    SELECT containment.parent_uid AS uid
    FROM containment
    WHERE containment.board_id = ?1
        AND containment.child_uid = ?2
    UNION ALL
    SELECT containment.parent_uid
    FROM containment
    JOIN ancestors ON containment.child_uid = ancestors.uid
    WHERE containment.board_id = ?1
)
SELECT issue.id
FROM ancestors
JOIN issues AS issue ON issue.uid = ancestors.uid
`

type BoardListEditContainmentAncestorIDsParams struct {
	ScopeBoardID string
	StartUid     []byte
}

func (q *Queries) BoardListEditContainmentAncestorIDs(ctx context.Context, arg BoardListEditContainmentAncestorIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, boardListEditContainmentAncestorIDs, arg.ScopeBoardID, arg.StartUid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListEditDependencyAncestorIDs = `-- name: BoardListEditDependencyAncestorIDs :many
WITH RECURSIVE ancestors AS (
    SELECT dependencies.prerequisite_uid AS uid
    FROM dependencies
    WHERE dependencies.board_id = ?1
        AND dependencies.issue_uid = ?2
    UNION
    SELECT dependency.prerequisite_uid
    FROM dependencies AS dependency
    JOIN ancestors ON dependency.issue_uid = ancestors.uid
    WHERE dependency.board_id = ?1
)
SELECT issue.id
FROM ancestors
JOIN issues AS issue ON issue.uid = ancestors.uid
ORDER BY issue.id
`

type BoardListEditDependencyAncestorIDsParams struct {
	ScopeBoardID string
	StartUid     []byte
}

func (q *Queries) BoardListEditDependencyAncestorIDs(ctx context.Context, arg BoardListEditDependencyAncestorIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, boardListEditDependencyAncestorIDs, arg.ScopeBoardID, arg.StartUid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
