// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_labels.sql

package query

import (
	"context"
)

const boardDeleteIssueLabels = `-- name: BoardDeleteIssueLabels :exec
DELETE FROM issue_labels
WHERE board_id = ?1
    AND issue_id = ?2
`

type BoardDeleteIssueLabelsParams struct {
	BoardID string
	IssueID string
}

func (q *Queries) BoardDeleteIssueLabels(ctx context.Context, arg BoardDeleteIssueLabelsParams) error {
	_, err := q.db.ExecContext(ctx, boardDeleteIssueLabels, arg.BoardID, arg.IssueID)
	return err
}

const boardInsertIssueLabel = `-- name: BoardInsertIssueLabel :exec
INSERT INTO issue_labels (
    board_id,
    issue_id,
    label
) VALUES (
    ?1,
    ?2,
    ?3
)
`

type BoardInsertIssueLabelParams struct {
	BoardID string
	IssueID string
	Label   string
}

func (q *Queries) BoardInsertIssueLabel(ctx context.Context, arg BoardInsertIssueLabelParams) error {
	_, err := q.db.ExecContext(ctx, boardInsertIssueLabel, arg.BoardID, arg.IssueID, arg.Label)
	return err
}

const boardListAllIssueLabels = `-- name: BoardListAllIssueLabels :many
SELECT issue_id, label
FROM issue_labels
WHERE board_id = ?1
ORDER BY issue_id, label
`

type BoardListAllIssueLabelsRow struct {
	IssueID string
	Label   string
}

func (q *Queries) BoardListAllIssueLabels(ctx context.Context, boardID string) ([]BoardListAllIssueLabelsRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListAllIssueLabels, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListAllIssueLabelsRow
	for rows.Next() {
		var i BoardListAllIssueLabelsRow
		if err := rows.Scan(&i.IssueID, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListLabelsForIssue = `-- name: BoardListLabelsForIssue :many
SELECT label
FROM issue_labels
WHERE board_id = ?1
    AND issue_id = ?2
ORDER BY label
`

type BoardListLabelsForIssueParams struct {
	BoardID string
	IssueID string
}

func (q *Queries) BoardListLabelsForIssue(ctx context.Context, arg BoardListLabelsForIssueParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, boardListLabelsForIssue, arg.BoardID, arg.IssueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var label string
		if err := rows.Scan(&label); err != nil {
			return nil, err
		}
		items = append(items, label)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
