// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_snapshot_read.sql

package query

import (
	"context"
	"time"
)

const boardGetSnapshotDescription = `-- name: BoardGetSnapshotDescription :one
SELECT description
FROM boards
WHERE id = ?1
`

func (q *Queries) BoardGetSnapshotDescription(ctx context.Context, boardID string) (*string, error) {
	row := q.db.QueryRowContext(ctx, boardGetSnapshotDescription, boardID)
	var description *string
	err := row.Scan(&description)
	return description, err
}

const boardListSnapshotLogEntries = `-- name: BoardListSnapshotLogEntries :many
SELECT id, issue_id, kind, author, committer, body, next_action, created_at
FROM issue_log_entries
WHERE board_id = ?1
ORDER BY local_sequence
`

type BoardListSnapshotLogEntriesRow struct {
	ID         string
	IssueID    string
	Kind       string
	Author     *string
	Committer  *string
	Body       string
	NextAction *string
	CreatedAt  *time.Time
}

func (q *Queries) BoardListSnapshotLogEntries(ctx context.Context, boardID string) ([]BoardListSnapshotLogEntriesRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListSnapshotLogEntries, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListSnapshotLogEntriesRow
	for rows.Next() {
		var i BoardListSnapshotLogEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.Kind,
			&i.Author,
			&i.Committer,
			&i.Body,
			&i.NextAction,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListSnapshotResults = `-- name: BoardListSnapshotResults :many
SELECT issue_id, body
FROM issue_results
WHERE board_id = ?1
ORDER BY issue_id
`

type BoardListSnapshotResultsRow struct {
	IssueID string
	Body    string
}

func (q *Queries) BoardListSnapshotResults(ctx context.Context, boardID string) ([]BoardListSnapshotResultsRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListSnapshotResults, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListSnapshotResultsRow
	for rows.Next() {
		var i BoardListSnapshotResultsRow
		if err := rows.Scan(&i.IssueID, &i.Body); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
