// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_graph_relationships.sql

package query

import (
	"context"
)

const boardGetParentID = `-- name: BoardGetParentID :one
SELECT parent_id
FROM containment
WHERE board_id = ?1
    AND child_id = ?2
`

type BoardGetParentIDParams struct {
	BoardID string
	ChildID string
}

func (q *Queries) BoardGetParentID(ctx context.Context, arg BoardGetParentIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, boardGetParentID, arg.BoardID, arg.ChildID)
	var parent_id string
	err := row.Scan(&parent_id)
	return parent_id, err
}

const boardIssueExists = `-- name: BoardIssueExists :one
SELECT EXISTS(
    SELECT 1
    FROM issues
    WHERE board_id = ?1
        AND id = ?2
)
`

type BoardIssueExistsParams struct {
	BoardID string
	IssueID string
}

func (q *Queries) BoardIssueExists(ctx context.Context, arg BoardIssueExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, boardIssueExists, arg.BoardID, arg.IssueID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const boardListBlockIDs = `-- name: BoardListBlockIDs :many
SELECT issue_id
FROM dependencies
WHERE board_id = ?1
    AND prerequisite_id = ?2
ORDER BY issue_id
`

type BoardListBlockIDsParams struct {
	BoardID        string
	PrerequisiteID string
}

func (q *Queries) BoardListBlockIDs(ctx context.Context, arg BoardListBlockIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, boardListBlockIDs, arg.BoardID, arg.PrerequisiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var issue_id string
		if err := rows.Scan(&issue_id); err != nil {
			return nil, err
		}
		items = append(items, issue_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListBlockedIssueIDs = `-- name: BoardListBlockedIssueIDs :many
SELECT DISTINCT dependency.issue_id
FROM dependencies AS dependency
JOIN issues AS prerequisite ON prerequisite.id = dependency.prerequisite_id
WHERE dependency.board_id = ?1
    AND prerequisite.lifecycle <> 'closed'
`

func (q *Queries) BoardListBlockedIssueIDs(ctx context.Context, boardID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, boardListBlockedIssueIDs, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var issue_id string
		if err := rows.Scan(&issue_id); err != nil {
			return nil, err
		}
		items = append(items, issue_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListContainmentParents = `-- name: BoardListContainmentParents :many
SELECT child_id, parent_id
FROM containment
WHERE board_id = ?1
`

type BoardListContainmentParentsRow struct {
	ChildID  string
	ParentID string
}

func (q *Queries) BoardListContainmentParents(ctx context.Context, boardID string) ([]BoardListContainmentParentsRow, error) {
	rows, err := q.db.QueryContext(ctx, boardListContainmentParents, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BoardListContainmentParentsRow
	for rows.Next() {
		var i BoardListContainmentParentsRow
		if err := rows.Scan(&i.ChildID, &i.ParentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListDescendantIDs = `-- name: BoardListDescendantIDs :many
WITH RECURSIVE descendants AS (
    SELECT containment.child_id AS id
    FROM containment
    WHERE containment.board_id = ?1
        AND containment.parent_id = ?2
    UNION ALL
    SELECT containment.child_id
    FROM containment
    JOIN descendants ON containment.parent_id = descendants.id
    WHERE containment.board_id = ?1
)
SELECT descendants.id
FROM descendants
`

type BoardListDescendantIDsParams struct {
	ScopeBoardID string
	RootID       string
}

func (q *Queries) BoardListDescendantIDs(ctx context.Context, arg BoardListDescendantIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, boardListDescendantIDs, arg.ScopeBoardID, arg.RootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListDirectChildIDs = `-- name: BoardListDirectChildIDs :many
SELECT child_id
FROM containment
WHERE board_id = ?1
    AND parent_id = ?2
ORDER BY child_id
`

type BoardListDirectChildIDsParams struct {
	BoardID  string
	ParentID string
}

func (q *Queries) BoardListDirectChildIDs(ctx context.Context, arg BoardListDirectChildIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, boardListDirectChildIDs, arg.BoardID, arg.ParentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var child_id string
		if err := rows.Scan(&child_id); err != nil {
			return nil, err
		}
		items = append(items, child_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardListPrerequisiteIDs = `-- name: BoardListPrerequisiteIDs :many
SELECT prerequisite_id
FROM dependencies
WHERE board_id = ?1
    AND issue_id = ?2
ORDER BY prerequisite_id
`

type BoardListPrerequisiteIDsParams struct {
	BoardID string
	IssueID string
}

func (q *Queries) BoardListPrerequisiteIDs(ctx context.Context, arg BoardListPrerequisiteIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, boardListPrerequisiteIDs, arg.BoardID, arg.IssueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var prerequisite_id string
		if err := rows.Scan(&prerequisite_id); err != nil {
			return nil, err
		}
		items = append(items, prerequisite_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
