// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_issue_detail.sql

package query

import (
	"context"
	"time"
)

const boardGetCheckpointDecision = `-- name: BoardGetCheckpointDecision :one
SELECT outcome, reason, decided_at, revision
FROM checkpoint_decisions
WHERE board_id = ?1
    AND issue_id = ?2
`

type BoardGetCheckpointDecisionParams struct {
	BoardID string
	IssueID string
}

type BoardGetCheckpointDecisionRow struct {
	Outcome   string
	Reason    string
	DecidedAt time.Time
	Revision  int64
}

func (q *Queries) BoardGetCheckpointDecision(ctx context.Context, arg BoardGetCheckpointDecisionParams) (BoardGetCheckpointDecisionRow, error) {
	row := q.db.QueryRowContext(ctx, boardGetCheckpointDecision, arg.BoardID, arg.IssueID)
	var i BoardGetCheckpointDecisionRow
	err := row.Scan(
		&i.Outcome,
		&i.Reason,
		&i.DecidedAt,
		&i.Revision,
	)
	return i, err
}

const boardGetIssueContextDescription = `-- name: BoardGetIssueContextDescription :one
SELECT description
FROM boards
WHERE id = ?1
`

func (q *Queries) BoardGetIssueContextDescription(ctx context.Context, boardID string) (*string, error) {
	row := q.db.QueryRowContext(ctx, boardGetIssueContextDescription, boardID)
	var description *string
	err := row.Scan(&description)
	return description, err
}

const boardGetIssueIDByExternalKey = `-- name: BoardGetIssueIDByExternalKey :one
SELECT issue_id
FROM issue_external_keys
WHERE board_id = ?1
    AND external_key = ?2
`

type BoardGetIssueIDByExternalKeyParams struct {
	BoardID     string
	ExternalKey string
}

func (q *Queries) BoardGetIssueIDByExternalKey(ctx context.Context, arg BoardGetIssueIDByExternalKeyParams) (string, error) {
	row := q.db.QueryRowContext(ctx, boardGetIssueIDByExternalKey, arg.BoardID, arg.ExternalKey)
	var issue_id string
	err := row.Scan(&issue_id)
	return issue_id, err
}

const boardGetIssueLogSummary = `-- name: BoardGetIssueLogSummary :one
SELECT
    COUNT(*) AS log_count,
    CAST(COALESCE((
        SELECT latest.id
        FROM issue_log_entries AS latest
        WHERE latest.board_id = ?1
            AND latest.issue_id = ?2
        ORDER BY latest.local_sequence DESC
        LIMIT 1
    ), '') AS TEXT) AS latest_log_id
FROM issue_log_entries AS entry
WHERE entry.board_id = ?1
    AND entry.issue_id = ?2
`

type BoardGetIssueLogSummaryParams struct {
	ScopeBoardID    string
	SelectedIssueID string
}

type BoardGetIssueLogSummaryRow struct {
	LogCount    int64
	LatestLogID string
}

func (q *Queries) BoardGetIssueLogSummary(ctx context.Context, arg BoardGetIssueLogSummaryParams) (BoardGetIssueLogSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, boardGetIssueLogSummary, arg.ScopeBoardID, arg.SelectedIssueID)
	var i BoardGetIssueLogSummaryRow
	err := row.Scan(&i.LogCount, &i.LatestLogID)
	return i, err
}

const boardGetIssueResultBody = `-- name: BoardGetIssueResultBody :one
SELECT body
FROM issue_results
WHERE board_id = ?1
    AND issue_id = ?2
`

type BoardGetIssueResultBodyParams struct {
	BoardID string
	IssueID string
}

func (q *Queries) BoardGetIssueResultBody(ctx context.Context, arg BoardGetIssueResultBodyParams) (string, error) {
	row := q.db.QueryRowContext(ctx, boardGetIssueResultBody, arg.BoardID, arg.IssueID)
	var body string
	err := row.Scan(&body)
	return body, err
}

const boardListIssueExternalKeys = `-- name: BoardListIssueExternalKeys :many
SELECT external_key
FROM issue_external_keys
WHERE board_id = ?1
    AND issue_id = ?2
ORDER BY external_key
`

type BoardListIssueExternalKeysParams struct {
	BoardID string
	IssueID string
}

func (q *Queries) BoardListIssueExternalKeys(ctx context.Context, arg BoardListIssueExternalKeysParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, boardListIssueExternalKeys, arg.BoardID, arg.IssueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var external_key string
		if err := rows.Scan(&external_key); err != nil {
			return nil, err
		}
		items = append(items, external_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
