// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lease_custody.sql

package query

import (
	"context"
	"time"
)

const leaseAcquire = `-- name: LeaseAcquire :one
INSERT INTO leases (
    name,
    owner,
    acquired_at,
    expires_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
ON CONFLICT(name) DO UPDATE SET
    owner = excluded.owner,
    acquired_at = excluded.acquired_at,
    expires_at = excluded.expires_at
WHERE leases.expires_at <= excluded.acquired_at
RETURNING name, owner, acquired_at, expires_at
`

type LeaseAcquireParams struct {
	Name       string
	Owner      string
	AcquiredAt time.Time
	ExpiresAt  time.Time
}

func (q *Queries) LeaseAcquire(ctx context.Context, arg LeaseAcquireParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, leaseAcquire,
		arg.Name,
		arg.Owner,
		arg.AcquiredAt,
		arg.ExpiresAt,
	)
	var i Lease
	err := row.Scan(
		&i.Name,
		&i.Owner,
		&i.AcquiredAt,
		&i.ExpiresAt,
	)
	return i, err
}

const leaseGetActive = `-- name: LeaseGetActive :one
SELECT name, owner, acquired_at, expires_at
FROM leases
WHERE name = ?1
    AND expires_at > ?2
`

type LeaseGetActiveParams struct {
	Name string
	Now  time.Time
}

func (q *Queries) LeaseGetActive(ctx context.Context, arg LeaseGetActiveParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, leaseGetActive, arg.Name, arg.Now)
	var i Lease
	err := row.Scan(
		&i.Name,
		&i.Owner,
		&i.AcquiredAt,
		&i.ExpiresAt,
	)
	return i, err
}

const leaseListActive = `-- name: LeaseListActive :many
SELECT name, owner, acquired_at, expires_at
FROM leases
WHERE expires_at > ?1
ORDER BY name ASC
`

func (q *Queries) LeaseListActive(ctx context.Context, now time.Time) ([]Lease, error) {
	rows, err := q.db.QueryContext(ctx, leaseListActive, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lease
	for rows.Next() {
		var i Lease
		if err := rows.Scan(
			&i.Name,
			&i.Owner,
			&i.AcquiredAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leaseRelease = `-- name: LeaseRelease :one
DELETE FROM leases
WHERE name = ?1
    AND owner = ?2
    AND expires_at > ?3
RETURNING name, owner, acquired_at, expires_at
`

type LeaseReleaseParams struct {
	Name  string
	Owner string
	Now   time.Time
}

func (q *Queries) LeaseRelease(ctx context.Context, arg LeaseReleaseParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, leaseRelease, arg.Name, arg.Owner, arg.Now)
	var i Lease
	err := row.Scan(
		&i.Name,
		&i.Owner,
		&i.AcquiredAt,
		&i.ExpiresAt,
	)
	return i, err
}

const leaseRenew = `-- name: LeaseRenew :one
UPDATE leases
SET expires_at = ?1
WHERE name = ?2
    AND owner = ?3
    AND expires_at > ?4
RETURNING name, owner, acquired_at, expires_at
`

type LeaseRenewParams struct {
	ExpiresAt time.Time
	Name      string
	Owner     string
	Now       time.Time
}

func (q *Queries) LeaseRenew(ctx context.Context, arg LeaseRenewParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, leaseRenew,
		arg.ExpiresAt,
		arg.Name,
		arg.Owner,
		arg.Now,
	)
	var i Lease
	err := row.Scan(
		&i.Name,
		&i.Owner,
		&i.AcquiredAt,
		&i.ExpiresAt,
	)
	return i, err
}

const leaseRevoke = `-- name: LeaseRevoke :one
DELETE FROM leases
WHERE name = ?1
    AND owner = ?2
    AND expires_at > ?3
RETURNING name, owner, acquired_at, expires_at
`

type LeaseRevokeParams struct {
	Name  string
	Owner string
	Now   time.Time
}

func (q *Queries) LeaseRevoke(ctx context.Context, arg LeaseRevokeParams) (Lease, error) {
	row := q.db.QueryRowContext(ctx, leaseRevoke, arg.Name, arg.Owner, arg.Now)
	var i Lease
	err := row.Scan(
		&i.Name,
		&i.Owner,
		&i.AcquiredAt,
		&i.ExpiresAt,
	)
	return i, err
}
