// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mail_subscription_reconciliation.sql

package query

import (
	"context"
	"database/sql"
	"time"
)

const mailListActiveSubscriptions = `-- name: MailListActiveSubscriptions :many
SELECT listener, pattern, created_at, expires_at
FROM subscriptions
WHERE expires_at > ?1
ORDER BY listener, pattern
`

func (q *Queries) MailListActiveSubscriptions(ctx context.Context, now time.Time) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, mailListActiveSubscriptions, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.Listener,
			&i.Pattern,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailListListenerSubscriptions = `-- name: MailListListenerSubscriptions :many
SELECT listener, pattern, created_at, expires_at
FROM subscriptions
WHERE listener = ?1
    AND expires_at > ?2
ORDER BY pattern
`

type MailListListenerSubscriptionsParams struct {
	Listener string
	Now      time.Time
}

func (q *Queries) MailListListenerSubscriptions(ctx context.Context, arg MailListListenerSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, mailListListenerSubscriptions, arg.Listener, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.Listener,
			&i.Pattern,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mailRefreshSubscription = `-- name: MailRefreshSubscription :one
INSERT INTO subscriptions (
    listener,
    pattern,
    created_at,
    expires_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
ON CONFLICT(listener, pattern) DO UPDATE SET
    expires_at = excluded.expires_at
RETURNING created_at
`

type MailRefreshSubscriptionParams struct {
	Listener  string
	Pattern   string
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) MailRefreshSubscription(ctx context.Context, arg MailRefreshSubscriptionParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, mailRefreshSubscription,
		arg.Listener,
		arg.Pattern,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const mailRemoveSubscription = `-- name: MailRemoveSubscription :execresult
DELETE FROM subscriptions
WHERE listener = ?1
    AND pattern = ?2
`

type MailRemoveSubscriptionParams struct {
	Listener string
	Pattern  string
}

func (q *Queries) MailRemoveSubscription(ctx context.Context, arg MailRemoveSubscriptionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, mailRemoveSubscription, arg.Listener, arg.Pattern)
}
