// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mail_mailbox_delivery.sql

package query

import (
	"context"
	"time"
)

const mailInsertDelivery = `-- name: MailInsertDelivery :exec
INSERT INTO mailbox (
    id,
    sender,
    recipient,
    source_topic,
    body,
    created_at,
    expires_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
)
`

type MailInsertDeliveryParams struct {
	ID          string
	Sender      string
	Recipient   string
	SourceTopic *string
	Body        string
	CreatedAt   time.Time
	ExpiresAt   time.Time
}

func (q *Queries) MailInsertDelivery(ctx context.Context, arg MailInsertDeliveryParams) error {
	_, err := q.db.ExecContext(ctx, mailInsertDelivery,
		arg.ID,
		arg.Sender,
		arg.Recipient,
		arg.SourceTopic,
		arg.Body,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const mailSelectPublicationSubscriptions = `-- name: MailSelectPublicationSubscriptions :many
SELECT listener, pattern, created_at, expires_at
FROM subscriptions
WHERE expires_at > ?1
ORDER BY listener, pattern
`

func (q *Queries) MailSelectPublicationSubscriptions(ctx context.Context, now time.Time) ([]Subscription, error) {
	rows, err := q.db.QueryContext(ctx, mailSelectPublicationSubscriptions, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.Listener,
			&i.Pattern,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
