// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package query

import (
	"time"
)

type Lease struct {
	Name       string
	Owner      string
	AcquiredAt time.Time
	ExpiresAt  time.Time
}

type Subscription struct {
	Listener  string
	Pattern   string
	CreatedAt time.Time
	ExpiresAt time.Time
}
