// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_backup.sql

package query

import (
	"context"
	"strings"
	"time"
)

const projectListBackupBoards = `-- name: ProjectListBackupBoards :many
SELECT
    project.id AS project_id,
    project.name AS project_name,
    project.created_at AS project_created_at,
    board.id AS board_id
FROM boards AS board
JOIN projects AS project ON project.id = board.project_id
ORDER BY board.id
`

type ProjectListBackupBoardsRow struct {
	ProjectID        string
	ProjectName      string
	ProjectCreatedAt time.Time
	BoardID          string
}

func (q *Queries) ProjectListBackupBoards(ctx context.Context) ([]ProjectListBackupBoardsRow, error) {
	rows, err := q.db.QueryContext(ctx, projectListBackupBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectListBackupBoardsRow
	for rows.Next() {
		var i ProjectListBackupBoardsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectCreatedAt,
			&i.BoardID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectListSelectedBackupBoards = `-- name: ProjectListSelectedBackupBoards :many
SELECT
    project.id AS project_id,
    project.name AS project_name,
    project.created_at AS project_created_at,
    board.id AS board_id
FROM boards AS board
JOIN projects AS project ON project.id = board.project_id
WHERE board.id IN (/*SLICE:board_ids*/?)
ORDER BY board.id
`

type ProjectListSelectedBackupBoardsRow struct {
	ProjectID        string
	ProjectName      string
	ProjectCreatedAt time.Time
	BoardID          string
}

func (q *Queries) ProjectListSelectedBackupBoards(ctx context.Context, boardIds []string) ([]ProjectListSelectedBackupBoardsRow, error) {
	query := projectListSelectedBackupBoards
	var queryParams []interface{}
	if len(boardIds) > 0 {
		for _, v := range boardIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:board_ids*/?", strings.Repeat(",?", len(boardIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:board_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectListSelectedBackupBoardsRow
	for rows.Next() {
		var i ProjectListSelectedBackupBoardsRow
		if err := rows.Scan(
			&i.ProjectID,
			&i.ProjectName,
			&i.ProjectCreatedAt,
			&i.BoardID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
