// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_initialization.sql

package query

import (
	"context"
	"time"
)

const projectCreateInitialBoard = `-- name: ProjectCreateInitialBoard :exec
INSERT INTO boards (id, project_id, name, created_at)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
`

type ProjectCreateInitialBoardParams struct {
	ID        string
	ProjectID string
	Name      string
	CreatedAt time.Time
}

func (q *Queries) ProjectCreateInitialBoard(ctx context.Context, arg ProjectCreateInitialBoardParams) error {
	_, err := q.db.ExecContext(ctx, projectCreateInitialBoard,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const projectCreateInitialProject = `-- name: ProjectCreateInitialProject :exec
INSERT INTO projects (id, name, created_at, issue_id_prefix)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
`

type ProjectCreateInitialProjectParams struct {
	ID            string
	Name          string
	CreatedAt     time.Time
	IssueIDPrefix *string
}

func (q *Queries) ProjectCreateInitialProject(ctx context.Context, arg ProjectCreateInitialProjectParams) error {
	_, err := q.db.ExecContext(ctx, projectCreateInitialProject,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.IssueIDPrefix,
	)
	return err
}
