// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_board_changes.sql

package query

import (
	"context"
	"time"
)

const projectArchiveBoard = `-- name: ProjectArchiveBoard :exec
UPDATE boards
SET archived_at = ?1,
    archived_by = ?2,
    archive_reason = ?3
WHERE id = ?4
`

type ProjectArchiveBoardParams struct {
	ArchivedAt    *time.Time
	ArchivedBy    *string
	ArchiveReason *string
	ID            string
}

// Archive metadata is one logical value protected by the table invariant.
func (q *Queries) ProjectArchiveBoard(ctx context.Context, arg ProjectArchiveBoardParams) error {
	_, err := q.db.ExecContext(ctx, projectArchiveBoard,
		arg.ArchivedAt,
		arg.ArchivedBy,
		arg.ArchiveReason,
		arg.ID,
	)
	return err
}

const projectCreateBoard = `-- name: ProjectCreateBoard :exec
INSERT INTO boards (
    id,
    project_id,
    name,
    description,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
`

type ProjectCreateBoardParams struct {
	ID          string
	ProjectID   string
	Name        string
	Description *string
	CreatedAt   time.Time
}

func (q *Queries) ProjectCreateBoard(ctx context.Context, arg ProjectCreateBoardParams) error {
	_, err := q.db.ExecContext(ctx, projectCreateBoard,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
	)
	return err
}

const projectExists = `-- name: ProjectExists :one
SELECT EXISTS (
    SELECT 1
    FROM projects
    WHERE id = ?1
) AS project_exists
`

func (q *Queries) ProjectExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, projectExists, id)
	var project_exists bool
	err := row.Scan(&project_exists)
	return project_exists, err
}

const projectUnarchiveBoard = `-- name: ProjectUnarchiveBoard :exec
UPDATE boards
SET archived_at = NULL, archived_by = NULL, archive_reason = NULL
WHERE id = ?1
`

// Clearing all archive columns restores the active representation.
func (q *Queries) ProjectUnarchiveBoard(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, projectUnarchiveBoard, id)
	return err
}

const projectUpdateBoardSettings = `-- name: ProjectUpdateBoardSettings :exec
UPDATE boards
SET name = ?1,
    description = ?2
WHERE id = ?3
`

type ProjectUpdateBoardSettingsParams struct {
	Name        string
	Description *string
	ID          string
}

func (q *Queries) ProjectUpdateBoardSettings(ctx context.Context, arg ProjectUpdateBoardSettingsParams) error {
	_, err := q.db.ExecContext(ctx, projectUpdateBoardSettings, arg.Name, arg.Description, arg.ID)
	return err
}
