// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_changes.sql

package query

import (
	"context"
	"time"
)

const projectGetProject = `-- name: ProjectGetProject :one
SELECT id, name, created_at
FROM projects
WHERE id = ?1
`

type ProjectGetProjectRow struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

func (q *Queries) ProjectGetProject(ctx context.Context, id string) (ProjectGetProjectRow, error) {
	row := q.db.QueryRowContext(ctx, projectGetProject, id)
	var i ProjectGetProjectRow
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const projectUpdateProjectName = `-- name: ProjectUpdateProjectName :exec
UPDATE projects
SET name = ?1
WHERE id = ?2
`

type ProjectUpdateProjectNameParams struct {
	Name string
	ID   string
}

func (q *Queries) ProjectUpdateProjectName(ctx context.Context, arg ProjectUpdateProjectNameParams) error {
	_, err := q.db.ExecContext(ctx, projectUpdateProjectName, arg.Name, arg.ID)
	return err
}
