// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_configuration.sql

package query

import (
	"context"
)

const projectGetBoardConfiguration = `-- name: ProjectGetBoardConfiguration :one
SELECT
    issue_id_prefix,
    issue_id_strategy,
    issue_summary_max_bytes,
    attachment_max_bytes
FROM boards
WHERE id = ?1
`

type ProjectGetBoardConfigurationRow struct {
	IssueIDPrefix        *string
	IssueIDStrategy      *string
	IssueSummaryMaxBytes *int64
	AttachmentMaxBytes   *int64
}

func (q *Queries) ProjectGetBoardConfiguration(ctx context.Context, id string) (ProjectGetBoardConfigurationRow, error) {
	row := q.db.QueryRowContext(ctx, projectGetBoardConfiguration, id)
	var i ProjectGetBoardConfigurationRow
	err := row.Scan(
		&i.IssueIDPrefix,
		&i.IssueIDStrategy,
		&i.IssueSummaryMaxBytes,
		&i.AttachmentMaxBytes,
	)
	return i, err
}

const projectGetConfigurationLayers = `-- name: ProjectGetConfigurationLayers :one
SELECT
    p.id AS project_id,
    p.issue_id_prefix AS project_issue_id_prefix,
    p.issue_id_strategy AS project_issue_id_strategy,
    p.issue_summary_max_bytes AS project_issue_summary_max_bytes,
    p.attachment_max_bytes AS project_attachment_max_bytes,
    b.issue_id_prefix AS board_issue_id_prefix,
    b.issue_id_strategy AS board_issue_id_strategy,
    b.issue_summary_max_bytes AS board_issue_summary_max_bytes,
    b.attachment_max_bytes AS board_attachment_max_bytes
FROM boards AS b
JOIN projects AS p ON p.id = b.project_id
WHERE b.id = ?1
`

type ProjectGetConfigurationLayersRow struct {
	ProjectID                   string
	ProjectIssueIDPrefix        *string
	ProjectIssueIDStrategy      *string
	ProjectIssueSummaryMaxBytes *int64
	ProjectAttachmentMaxBytes   *int64
	BoardIssueIDPrefix          *string
	BoardIssueIDStrategy        *string
	BoardIssueSummaryMaxBytes   *int64
	BoardAttachmentMaxBytes     *int64
}

func (q *Queries) ProjectGetConfigurationLayers(ctx context.Context, boardID string) (ProjectGetConfigurationLayersRow, error) {
	row := q.db.QueryRowContext(ctx, projectGetConfigurationLayers, boardID)
	var i ProjectGetConfigurationLayersRow
	err := row.Scan(
		&i.ProjectID,
		&i.ProjectIssueIDPrefix,
		&i.ProjectIssueIDStrategy,
		&i.ProjectIssueSummaryMaxBytes,
		&i.ProjectAttachmentMaxBytes,
		&i.BoardIssueIDPrefix,
		&i.BoardIssueIDStrategy,
		&i.BoardIssueSummaryMaxBytes,
		&i.BoardAttachmentMaxBytes,
	)
	return i, err
}

const projectGetProjectConfiguration = `-- name: ProjectGetProjectConfiguration :one
SELECT
    issue_id_prefix,
    issue_id_strategy,
    issue_summary_max_bytes,
    attachment_max_bytes
FROM projects
WHERE id = ?1
`

type ProjectGetProjectConfigurationRow struct {
	IssueIDPrefix        *string
	IssueIDStrategy      *string
	IssueSummaryMaxBytes *int64
	AttachmentMaxBytes   *int64
}

func (q *Queries) ProjectGetProjectConfiguration(ctx context.Context, id string) (ProjectGetProjectConfigurationRow, error) {
	row := q.db.QueryRowContext(ctx, projectGetProjectConfiguration, id)
	var i ProjectGetProjectConfigurationRow
	err := row.Scan(
		&i.IssueIDPrefix,
		&i.IssueIDStrategy,
		&i.IssueSummaryMaxBytes,
		&i.AttachmentMaxBytes,
	)
	return i, err
}

const projectUpdateBoardConfiguration = `-- name: ProjectUpdateBoardConfiguration :exec
UPDATE boards
SET issue_id_prefix = ?1,
    issue_id_strategy = ?2,
    issue_summary_max_bytes = ?3,
    attachment_max_bytes = ?4
WHERE id = ?5
`

type ProjectUpdateBoardConfigurationParams struct {
	IssueIDPrefix        *string
	IssueIDStrategy      *string
	IssueSummaryMaxBytes *int64
	AttachmentMaxBytes   *int64
	ID                   string
}

func (q *Queries) ProjectUpdateBoardConfiguration(ctx context.Context, arg ProjectUpdateBoardConfigurationParams) error {
	_, err := q.db.ExecContext(ctx, projectUpdateBoardConfiguration,
		arg.IssueIDPrefix,
		arg.IssueIDStrategy,
		arg.IssueSummaryMaxBytes,
		arg.AttachmentMaxBytes,
		arg.ID,
	)
	return err
}

const projectUpdateProjectConfiguration = `-- name: ProjectUpdateProjectConfiguration :exec
UPDATE projects
SET issue_id_prefix = ?1,
    issue_id_strategy = ?2,
    issue_summary_max_bytes = ?3,
    attachment_max_bytes = ?4
WHERE id = ?5
`

type ProjectUpdateProjectConfigurationParams struct {
	IssueIDPrefix        *string
	IssueIDStrategy      *string
	IssueSummaryMaxBytes *int64
	AttachmentMaxBytes   *int64
	ID                   string
}

func (q *Queries) ProjectUpdateProjectConfiguration(ctx context.Context, arg ProjectUpdateProjectConfigurationParams) error {
	_, err := q.db.ExecContext(ctx, projectUpdateProjectConfiguration,
		arg.IssueIDPrefix,
		arg.IssueIDStrategy,
		arg.IssueSummaryMaxBytes,
		arg.AttachmentMaxBytes,
		arg.ID,
	)
	return err
}
