// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_board_changes.sql

package query

import (
	"context"
	"time"
)

const projectCreateBoard = `-- name: ProjectCreateBoard :exec
INSERT INTO boards (
    id,
    project_id,
    name,
    description,
    created_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
`

type ProjectCreateBoardParams struct {
	ID          string
	ProjectID   string
	Name        string
	Description *string
	CreatedAt   time.Time
}

func (q *Queries) ProjectCreateBoard(ctx context.Context, arg ProjectCreateBoardParams) error {
	_, err := q.db.ExecContext(ctx, projectCreateBoard,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
	)
	return err
}

const projectExists = `-- name: ProjectExists :one
SELECT EXISTS (
    SELECT 1
    FROM projects
    WHERE id = ?1
) AS project_exists
`

func (q *Queries) ProjectExists(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRowContext(ctx, projectExists, id)
	var project_exists bool
	err := row.Scan(&project_exists)
	return project_exists, err
}

const projectUpdateBoardSettings = `-- name: ProjectUpdateBoardSettings :exec
UPDATE boards
SET name = ?1,
    description = ?2
WHERE id = ?3
`

type ProjectUpdateBoardSettingsParams struct {
	Name        string
	Description *string
	ID          string
}

func (q *Queries) ProjectUpdateBoardSettings(ctx context.Context, arg ProjectUpdateBoardSettingsParams) error {
	_, err := q.db.ExecContext(ctx, projectUpdateBoardSettings, arg.Name, arg.Description, arg.ID)
	return err
}
