// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_catalog.sql

package query

import (
	"context"
	"time"
)

const projectListProjects = `-- name: ProjectListProjects :many
SELECT id, name, created_at
FROM projects
ORDER BY name, id
`

type ProjectListProjectsRow struct {
	ID        string
	Name      string
	CreatedAt time.Time
}

func (q *Queries) ProjectListProjects(ctx context.Context) ([]ProjectListProjectsRow, error) {
	rows, err := q.db.QueryContext(ctx, projectListProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectListProjectsRow
	for rows.Next() {
		var i ProjectListProjectsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
