// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_creation.sql

package query

import (
	"context"
	"time"
)

const projectCreateProject = `-- name: ProjectCreateProject :exec
INSERT INTO projects (
    id,
    name,
    created_at,
    issue_id_prefix
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
`

type ProjectCreateProjectParams struct {
	ID            string
	Name          string
	CreatedAt     time.Time
	IssueIDPrefix *string
}

func (q *Queries) ProjectCreateProject(ctx context.Context, arg ProjectCreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, projectCreateProject,
		arg.ID,
		arg.Name,
		arg.CreatedAt,
		arg.IssueIDPrefix,
	)
	return err
}
