// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_lineage.sql

package query

import (
	"context"
)

const storeGetLineageID = `-- name: StoreGetLineageID :one
SELECT id
FROM store_lineage
WHERE singleton = 1
`

func (q *Queries) StoreGetLineageID(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, storeGetLineageID)
	var id string
	err := row.Scan(&id)
	return id, err
}
