// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_state.sql

package query

import (
	"context"
	"database/sql"
)

const storeAdvanceNextIssueNumber = `-- name: StoreAdvanceNextIssueNumber :exec
UPDATE store_state
SET next_issue_number = ?1
WHERE singleton = 1
    AND next_issue_number < ?1
`

func (q *Queries) StoreAdvanceNextIssueNumber(ctx context.Context, nextIssueNumber int64) error {
	_, err := q.db.ExecContext(ctx, storeAdvanceNextIssueNumber, nextIssueNumber)
	return err
}

const storeGetCanonicalRevision = `-- name: StoreGetCanonicalRevision :one
SELECT current_revision
FROM store_state
WHERE singleton = 1
`

func (q *Queries) StoreGetCanonicalRevision(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, storeGetCanonicalRevision)
	var current_revision int64
	err := row.Scan(&current_revision)
	return current_revision, err
}

const storeGetNextIssueNumber = `-- name: StoreGetNextIssueNumber :one
SELECT next_issue_number
FROM store_state
WHERE singleton = 1
`

func (q *Queries) StoreGetNextIssueNumber(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, storeGetNextIssueNumber)
	var next_issue_number int64
	err := row.Scan(&next_issue_number)
	return next_issue_number, err
}

const storePublishCanonicalRevision = `-- name: StorePublishCanonicalRevision :execresult
UPDATE store_state
SET current_revision = ?1
WHERE singleton = 1
    AND current_revision = ?2
`

type StorePublishCanonicalRevisionParams struct {
	Revision        int64
	CurrentRevision int64
}

func (q *Queries) StorePublishCanonicalRevision(ctx context.Context, arg StorePublishCanonicalRevisionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, storePublishCanonicalRevision, arg.Revision, arg.CurrentRevision)
}

const storeSetNextIssueNumber = `-- name: StoreSetNextIssueNumber :exec
UPDATE store_state
SET next_issue_number = ?1
WHERE singleton = 1
`

func (q *Queries) StoreSetNextIssueNumber(ctx context.Context, nextIssueNumber int64) error {
	_, err := q.db.ExecContext(ctx, storeSetNextIssueNumber, nextIssueNumber)
	return err
}
