// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/cli (interfaces: LogEntryWriteOperations,LogEntryReadOperations)
//
// Generated by this command:
//
//	mockgen -destination log_mocks_test.go -package cli -typed -write_package_comment=false . LogEntryWriteOperations,LogEntryReadOperations
//

package cli

import (
	context "context"
	reflect "reflect"

	issue "go.abhg.dev/cardamom/internal/issue"
	record "go.abhg.dev/cardamom/internal/issue/record"
	gomock "go.uber.org/mock/gomock"
)

// MockLogEntryWriteOperations is a mock of LogEntryWriteOperations interface.
type MockLogEntryWriteOperations struct {
	ctrl     *gomock.Controller
	recorder *MockLogEntryWriteOperationsMockRecorder
	isgomock struct{}
}

// MockLogEntryWriteOperationsMockRecorder is the mock recorder for MockLogEntryWriteOperations.
type MockLogEntryWriteOperationsMockRecorder struct {
	mock *MockLogEntryWriteOperations
}

// NewMockLogEntryWriteOperations creates a new mock instance.
func NewMockLogEntryWriteOperations(ctrl *gomock.Controller) *MockLogEntryWriteOperations {
	mock := &MockLogEntryWriteOperations{ctrl: ctrl}
	mock.recorder = &MockLogEntryWriteOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogEntryWriteOperations) EXPECT() *MockLogEntryWriteOperationsMockRecorder {
	return m.recorder
}

// AddLogEntry mocks base method.
func (m *MockLogEntryWriteOperations) AddLogEntry(arg0 context.Context, arg1 issue.Invocation, arg2 record.AddLogEntryRequest) (record.AddLogEntryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLogEntry", arg0, arg1, arg2)
	ret0, _ := ret[0].(record.AddLogEntryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLogEntry indicates an expected call of AddLogEntry.
func (mr *MockLogEntryWriteOperationsMockRecorder) AddLogEntry(arg0, arg1, arg2 any) *MockLogEntryWriteOperationsAddLogEntryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLogEntry", reflect.TypeOf((*MockLogEntryWriteOperations)(nil).AddLogEntry), arg0, arg1, arg2)
	return &MockLogEntryWriteOperationsAddLogEntryCall{Call: call}
}

// MockLogEntryWriteOperationsAddLogEntryCall wrap *gomock.Call
type MockLogEntryWriteOperationsAddLogEntryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLogEntryWriteOperationsAddLogEntryCall) Return(arg0 record.AddLogEntryResult, arg1 error) *MockLogEntryWriteOperationsAddLogEntryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLogEntryWriteOperationsAddLogEntryCall) Do(f func(context.Context, issue.Invocation, record.AddLogEntryRequest) (record.AddLogEntryResult, error)) *MockLogEntryWriteOperationsAddLogEntryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLogEntryWriteOperationsAddLogEntryCall) DoAndReturn(f func(context.Context, issue.Invocation, record.AddLogEntryRequest) (record.AddLogEntryResult, error)) *MockLogEntryWriteOperationsAddLogEntryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockLogEntryReadOperations is a mock of LogEntryReadOperations interface.
type MockLogEntryReadOperations struct {
	ctrl     *gomock.Controller
	recorder *MockLogEntryReadOperationsMockRecorder
	isgomock struct{}
}

// MockLogEntryReadOperationsMockRecorder is the mock recorder for MockLogEntryReadOperations.
type MockLogEntryReadOperationsMockRecorder struct {
	mock *MockLogEntryReadOperations
}

// NewMockLogEntryReadOperations creates a new mock instance.
func NewMockLogEntryReadOperations(ctrl *gomock.Controller) *MockLogEntryReadOperations {
	mock := &MockLogEntryReadOperations{ctrl: ctrl}
	mock.recorder = &MockLogEntryReadOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogEntryReadOperations) EXPECT() *MockLogEntryReadOperationsMockRecorder {
	return m.recorder
}

// GetLogEntry mocks base method.
func (m *MockLogEntryReadOperations) GetLogEntry(arg0 context.Context, arg1 record.GetLogEntryRequest) (issue.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogEntry", arg0, arg1)
	ret0, _ := ret[0].(issue.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogEntry indicates an expected call of GetLogEntry.
func (mr *MockLogEntryReadOperationsMockRecorder) GetLogEntry(arg0, arg1 any) *MockLogEntryReadOperationsGetLogEntryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogEntry", reflect.TypeOf((*MockLogEntryReadOperations)(nil).GetLogEntry), arg0, arg1)
	return &MockLogEntryReadOperationsGetLogEntryCall{Call: call}
}

// MockLogEntryReadOperationsGetLogEntryCall wrap *gomock.Call
type MockLogEntryReadOperationsGetLogEntryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLogEntryReadOperationsGetLogEntryCall) Return(arg0 issue.LogEntry, arg1 error) *MockLogEntryReadOperationsGetLogEntryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLogEntryReadOperationsGetLogEntryCall) Do(f func(context.Context, record.GetLogEntryRequest) (issue.LogEntry, error)) *MockLogEntryReadOperationsGetLogEntryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLogEntryReadOperationsGetLogEntryCall) DoAndReturn(f func(context.Context, record.GetLogEntryRequest) (issue.LogEntry, error)) *MockLogEntryReadOperationsGetLogEntryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListLogEntries mocks base method.
func (m *MockLogEntryReadOperations) ListLogEntries(arg0 context.Context, arg1 issue.LogListRequest) ([]issue.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLogEntries", arg0, arg1)
	ret0, _ := ret[0].([]issue.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLogEntries indicates an expected call of ListLogEntries.
func (mr *MockLogEntryReadOperationsMockRecorder) ListLogEntries(arg0, arg1 any) *MockLogEntryReadOperationsListLogEntriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLogEntries", reflect.TypeOf((*MockLogEntryReadOperations)(nil).ListLogEntries), arg0, arg1)
	return &MockLogEntryReadOperationsListLogEntriesCall{Call: call}
}

// MockLogEntryReadOperationsListLogEntriesCall wrap *gomock.Call
type MockLogEntryReadOperationsListLogEntriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLogEntryReadOperationsListLogEntriesCall) Return(arg0 []issue.LogEntry, arg1 error) *MockLogEntryReadOperationsListLogEntriesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLogEntryReadOperationsListLogEntriesCall) Do(f func(context.Context, issue.LogListRequest) ([]issue.LogEntry, error)) *MockLogEntryReadOperationsListLogEntriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLogEntryReadOperationsListLogEntriesCall) DoAndReturn(f func(context.Context, issue.LogListRequest) ([]issue.LogEntry, error)) *MockLogEntryReadOperationsListLogEntriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
