// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/cli (interfaces: BackupOperation,RestoreOperation,DumpOperation,LeaseOperations,InitOperation,InfoOperation,WebOperation,ListIssuesOperation,ListReadyIssuesOperation,ListBlockedIssuesOperation,ReadIssueOperation,CreateIssueOperation,ApplyDocumentOperation,EditIssueOperation,ClaimOperations,ReleaseOperations,CloseOperations,CancelOperations,ReopenOperations,CheckpointOperations,LogEntryWriteOperations,LogEntryReadOperations,StateWriteOperations,StateReadOperations,StateCommitOperations,ResultWriteOperations,ResultReadOperations)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package cli -typed -write_package_comment=false . BackupOperation,RestoreOperation,DumpOperation,LeaseOperations,InitOperation,InfoOperation,WebOperation,ListIssuesOperation,ListReadyIssuesOperation,ListBlockedIssuesOperation,ReadIssueOperation,CreateIssueOperation,ApplyDocumentOperation,EditIssueOperation,ClaimOperations,ReleaseOperations,CloseOperations,CancelOperations,ReopenOperations,CheckpointOperations,LogEntryWriteOperations,LogEntryReadOperations,StateWriteOperations,StateReadOperations,StateCommitOperations,ResultWriteOperations,ResultReadOperations
//

package cli

import (
	context "context"
	reflect "reflect"

	attachment "go.abhg.dev/cardamom/internal/attachment"
	dump "go.abhg.dev/cardamom/internal/dump"
	issue "go.abhg.dev/cardamom/internal/issue"
	execution "go.abhg.dev/cardamom/internal/issue/execution"
	planning "go.abhg.dev/cardamom/internal/issue/planning"
	record "go.abhg.dev/cardamom/internal/issue/record"
	lease "go.abhg.dev/cardamom/internal/lease"
	gomock "go.uber.org/mock/gomock"
)

// MockBackupOperation is a mock of BackupOperation interface.
type MockBackupOperation struct {
	ctrl     *gomock.Controller
	recorder *MockBackupOperationMockRecorder
	isgomock struct{}
}

// MockBackupOperationMockRecorder is the mock recorder for MockBackupOperation.
type MockBackupOperationMockRecorder struct {
	mock *MockBackupOperation
}

// NewMockBackupOperation creates a new mock instance.
func NewMockBackupOperation(ctrl *gomock.Controller) *MockBackupOperation {
	mock := &MockBackupOperation{ctrl: ctrl}
	mock.recorder = &MockBackupOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackupOperation) EXPECT() *MockBackupOperationMockRecorder {
	return m.recorder
}

// Backup mocks base method.
func (m *MockBackupOperation) Backup(arg0 context.Context, arg1 BackupRequest) (BackupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Backup", arg0, arg1)
	ret0, _ := ret[0].(BackupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Backup indicates an expected call of Backup.
func (mr *MockBackupOperationMockRecorder) Backup(arg0, arg1 any) *MockBackupOperationBackupCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Backup", reflect.TypeOf((*MockBackupOperation)(nil).Backup), arg0, arg1)
	return &MockBackupOperationBackupCall{Call: call}
}

// MockBackupOperationBackupCall wrap *gomock.Call
type MockBackupOperationBackupCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBackupOperationBackupCall) Return(arg0 BackupResult, arg1 error) *MockBackupOperationBackupCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBackupOperationBackupCall) Do(f func(context.Context, BackupRequest) (BackupResult, error)) *MockBackupOperationBackupCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBackupOperationBackupCall) DoAndReturn(f func(context.Context, BackupRequest) (BackupResult, error)) *MockBackupOperationBackupCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRestoreOperation is a mock of RestoreOperation interface.
type MockRestoreOperation struct {
	ctrl     *gomock.Controller
	recorder *MockRestoreOperationMockRecorder
	isgomock struct{}
}

// MockRestoreOperationMockRecorder is the mock recorder for MockRestoreOperation.
type MockRestoreOperationMockRecorder struct {
	mock *MockRestoreOperation
}

// NewMockRestoreOperation creates a new mock instance.
func NewMockRestoreOperation(ctrl *gomock.Controller) *MockRestoreOperation {
	mock := &MockRestoreOperation{ctrl: ctrl}
	mock.recorder = &MockRestoreOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRestoreOperation) EXPECT() *MockRestoreOperationMockRecorder {
	return m.recorder
}

// Restore mocks base method.
func (m *MockRestoreOperation) Restore(arg0 context.Context, arg1 RestoreRequest) (RestoreResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", arg0, arg1)
	ret0, _ := ret[0].(RestoreResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockRestoreOperationMockRecorder) Restore(arg0, arg1 any) *MockRestoreOperationRestoreCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockRestoreOperation)(nil).Restore), arg0, arg1)
	return &MockRestoreOperationRestoreCall{Call: call}
}

// MockRestoreOperationRestoreCall wrap *gomock.Call
type MockRestoreOperationRestoreCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRestoreOperationRestoreCall) Return(arg0 RestoreResult, arg1 error) *MockRestoreOperationRestoreCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRestoreOperationRestoreCall) Do(f func(context.Context, RestoreRequest) (RestoreResult, error)) *MockRestoreOperationRestoreCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRestoreOperationRestoreCall) DoAndReturn(f func(context.Context, RestoreRequest) (RestoreResult, error)) *MockRestoreOperationRestoreCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockDumpOperation is a mock of DumpOperation interface.
type MockDumpOperation struct {
	ctrl     *gomock.Controller
	recorder *MockDumpOperationMockRecorder
	isgomock struct{}
}

// MockDumpOperationMockRecorder is the mock recorder for MockDumpOperation.
type MockDumpOperationMockRecorder struct {
	mock *MockDumpOperation
}

// NewMockDumpOperation creates a new mock instance.
func NewMockDumpOperation(ctrl *gomock.Controller) *MockDumpOperation {
	mock := &MockDumpOperation{ctrl: ctrl}
	mock.recorder = &MockDumpOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDumpOperation) EXPECT() *MockDumpOperationMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockDumpOperation) Execute(arg0 context.Context, arg1 dump.Request) (dump.ExecutionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(dump.ExecutionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockDumpOperationMockRecorder) Execute(arg0, arg1 any) *MockDumpOperationExecuteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockDumpOperation)(nil).Execute), arg0, arg1)
	return &MockDumpOperationExecuteCall{Call: call}
}

// MockDumpOperationExecuteCall wrap *gomock.Call
type MockDumpOperationExecuteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDumpOperationExecuteCall) Return(arg0 dump.ExecutionResult, arg1 error) *MockDumpOperationExecuteCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDumpOperationExecuteCall) Do(f func(context.Context, dump.Request) (dump.ExecutionResult, error)) *MockDumpOperationExecuteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDumpOperationExecuteCall) DoAndReturn(f func(context.Context, dump.Request) (dump.ExecutionResult, error)) *MockDumpOperationExecuteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockLeaseOperations is a mock of LeaseOperations interface.
type MockLeaseOperations struct {
	ctrl     *gomock.Controller
	recorder *MockLeaseOperationsMockRecorder
	isgomock struct{}
}

// MockLeaseOperationsMockRecorder is the mock recorder for MockLeaseOperations.
type MockLeaseOperationsMockRecorder struct {
	mock *MockLeaseOperations
}

// NewMockLeaseOperations creates a new mock instance.
func NewMockLeaseOperations(ctrl *gomock.Controller) *MockLeaseOperations {
	mock := &MockLeaseOperations{ctrl: ctrl}
	mock.recorder = &MockLeaseOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaseOperations) EXPECT() *MockLeaseOperationsMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockLeaseOperations) Acquire(arg0 context.Context, arg1 lease.AcquireRequest) (lease.Lease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", arg0, arg1)
	ret0, _ := ret[0].(lease.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockLeaseOperationsMockRecorder) Acquire(arg0, arg1 any) *MockLeaseOperationsAcquireCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockLeaseOperations)(nil).Acquire), arg0, arg1)
	return &MockLeaseOperationsAcquireCall{Call: call}
}

// MockLeaseOperationsAcquireCall wrap *gomock.Call
type MockLeaseOperationsAcquireCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLeaseOperationsAcquireCall) Return(arg0 lease.Lease, arg1 error) *MockLeaseOperationsAcquireCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLeaseOperationsAcquireCall) Do(f func(context.Context, lease.AcquireRequest) (lease.Lease, error)) *MockLeaseOperationsAcquireCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLeaseOperationsAcquireCall) DoAndReturn(f func(context.Context, lease.AcquireRequest) (lease.Lease, error)) *MockLeaseOperationsAcquireCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockLeaseOperations) Get(arg0 context.Context, arg1 lease.GetRequest) (lease.Lease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(lease.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLeaseOperationsMockRecorder) Get(arg0, arg1 any) *MockLeaseOperationsGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLeaseOperations)(nil).Get), arg0, arg1)
	return &MockLeaseOperationsGetCall{Call: call}
}

// MockLeaseOperationsGetCall wrap *gomock.Call
type MockLeaseOperationsGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLeaseOperationsGetCall) Return(arg0 lease.Lease, arg1 error) *MockLeaseOperationsGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLeaseOperationsGetCall) Do(f func(context.Context, lease.GetRequest) (lease.Lease, error)) *MockLeaseOperationsGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLeaseOperationsGetCall) DoAndReturn(f func(context.Context, lease.GetRequest) (lease.Lease, error)) *MockLeaseOperationsGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockLeaseOperations) List(arg0 context.Context) ([]lease.Lease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]lease.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockLeaseOperationsMockRecorder) List(arg0 any) *MockLeaseOperationsListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockLeaseOperations)(nil).List), arg0)
	return &MockLeaseOperationsListCall{Call: call}
}

// MockLeaseOperationsListCall wrap *gomock.Call
type MockLeaseOperationsListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLeaseOperationsListCall) Return(arg0 []lease.Lease, arg1 error) *MockLeaseOperationsListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLeaseOperationsListCall) Do(f func(context.Context) ([]lease.Lease, error)) *MockLeaseOperationsListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLeaseOperationsListCall) DoAndReturn(f func(context.Context) ([]lease.Lease, error)) *MockLeaseOperationsListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Release mocks base method.
func (m *MockLeaseOperations) Release(arg0 context.Context, arg1 lease.ReleaseRequest) (lease.Lease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", arg0, arg1)
	ret0, _ := ret[0].(lease.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Release indicates an expected call of Release.
func (mr *MockLeaseOperationsMockRecorder) Release(arg0, arg1 any) *MockLeaseOperationsReleaseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockLeaseOperations)(nil).Release), arg0, arg1)
	return &MockLeaseOperationsReleaseCall{Call: call}
}

// MockLeaseOperationsReleaseCall wrap *gomock.Call
type MockLeaseOperationsReleaseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLeaseOperationsReleaseCall) Return(arg0 lease.Lease, arg1 error) *MockLeaseOperationsReleaseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLeaseOperationsReleaseCall) Do(f func(context.Context, lease.ReleaseRequest) (lease.Lease, error)) *MockLeaseOperationsReleaseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLeaseOperationsReleaseCall) DoAndReturn(f func(context.Context, lease.ReleaseRequest) (lease.Lease, error)) *MockLeaseOperationsReleaseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Renew mocks base method.
func (m *MockLeaseOperations) Renew(arg0 context.Context, arg1 lease.RenewRequest) (lease.Lease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Renew", arg0, arg1)
	ret0, _ := ret[0].(lease.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Renew indicates an expected call of Renew.
func (mr *MockLeaseOperationsMockRecorder) Renew(arg0, arg1 any) *MockLeaseOperationsRenewCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Renew", reflect.TypeOf((*MockLeaseOperations)(nil).Renew), arg0, arg1)
	return &MockLeaseOperationsRenewCall{Call: call}
}

// MockLeaseOperationsRenewCall wrap *gomock.Call
type MockLeaseOperationsRenewCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLeaseOperationsRenewCall) Return(arg0 lease.Lease, arg1 error) *MockLeaseOperationsRenewCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLeaseOperationsRenewCall) Do(f func(context.Context, lease.RenewRequest) (lease.Lease, error)) *MockLeaseOperationsRenewCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLeaseOperationsRenewCall) DoAndReturn(f func(context.Context, lease.RenewRequest) (lease.Lease, error)) *MockLeaseOperationsRenewCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Revoke mocks base method.
func (m *MockLeaseOperations) Revoke(arg0 context.Context, arg1 lease.RevokeRequest) (lease.Revocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", arg0, arg1)
	ret0, _ := ret[0].(lease.Revocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MockLeaseOperationsMockRecorder) Revoke(arg0, arg1 any) *MockLeaseOperationsRevokeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockLeaseOperations)(nil).Revoke), arg0, arg1)
	return &MockLeaseOperationsRevokeCall{Call: call}
}

// MockLeaseOperationsRevokeCall wrap *gomock.Call
type MockLeaseOperationsRevokeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLeaseOperationsRevokeCall) Return(arg0 lease.Revocation, arg1 error) *MockLeaseOperationsRevokeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLeaseOperationsRevokeCall) Do(f func(context.Context, lease.RevokeRequest) (lease.Revocation, error)) *MockLeaseOperationsRevokeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLeaseOperationsRevokeCall) DoAndReturn(f func(context.Context, lease.RevokeRequest) (lease.Revocation, error)) *MockLeaseOperationsRevokeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockInitOperation is a mock of InitOperation interface.
type MockInitOperation struct {
	ctrl     *gomock.Controller
	recorder *MockInitOperationMockRecorder
	isgomock struct{}
}

// MockInitOperationMockRecorder is the mock recorder for MockInitOperation.
type MockInitOperationMockRecorder struct {
	mock *MockInitOperation
}

// NewMockInitOperation creates a new mock instance.
func NewMockInitOperation(ctrl *gomock.Controller) *MockInitOperation {
	mock := &MockInitOperation{ctrl: ctrl}
	mock.recorder = &MockInitOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInitOperation) EXPECT() *MockInitOperationMockRecorder {
	return m.recorder
}

// Initialize mocks base method.
func (m *MockInitOperation) Initialize(arg0 context.Context, arg1 InitRequest) (InitResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize", arg0, arg1)
	ret0, _ := ret[0].(InitResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Initialize indicates an expected call of Initialize.
func (mr *MockInitOperationMockRecorder) Initialize(arg0, arg1 any) *MockInitOperationInitializeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockInitOperation)(nil).Initialize), arg0, arg1)
	return &MockInitOperationInitializeCall{Call: call}
}

// MockInitOperationInitializeCall wrap *gomock.Call
type MockInitOperationInitializeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInitOperationInitializeCall) Return(arg0 InitResult, arg1 error) *MockInitOperationInitializeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInitOperationInitializeCall) Do(f func(context.Context, InitRequest) (InitResult, error)) *MockInitOperationInitializeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInitOperationInitializeCall) DoAndReturn(f func(context.Context, InitRequest) (InitResult, error)) *MockInitOperationInitializeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockInfoOperation is a mock of InfoOperation interface.
type MockInfoOperation struct {
	ctrl     *gomock.Controller
	recorder *MockInfoOperationMockRecorder
	isgomock struct{}
}

// MockInfoOperationMockRecorder is the mock recorder for MockInfoOperation.
type MockInfoOperationMockRecorder struct {
	mock *MockInfoOperation
}

// NewMockInfoOperation creates a new mock instance.
func NewMockInfoOperation(ctrl *gomock.Controller) *MockInfoOperation {
	mock := &MockInfoOperation{ctrl: ctrl}
	mock.recorder = &MockInfoOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInfoOperation) EXPECT() *MockInfoOperationMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockInfoOperation) Read(arg0 context.Context, arg1 InfoRequest) (InfoResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0, arg1)
	ret0, _ := ret[0].(InfoResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockInfoOperationMockRecorder) Read(arg0, arg1 any) *MockInfoOperationReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockInfoOperation)(nil).Read), arg0, arg1)
	return &MockInfoOperationReadCall{Call: call}
}

// MockInfoOperationReadCall wrap *gomock.Call
type MockInfoOperationReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockInfoOperationReadCall) Return(arg0 InfoResult, arg1 error) *MockInfoOperationReadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockInfoOperationReadCall) Do(f func(context.Context, InfoRequest) (InfoResult, error)) *MockInfoOperationReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockInfoOperationReadCall) DoAndReturn(f func(context.Context, InfoRequest) (InfoResult, error)) *MockInfoOperationReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockWebOperation is a mock of WebOperation interface.
type MockWebOperation struct {
	ctrl     *gomock.Controller
	recorder *MockWebOperationMockRecorder
	isgomock struct{}
}

// MockWebOperationMockRecorder is the mock recorder for MockWebOperation.
type MockWebOperationMockRecorder struct {
	mock *MockWebOperation
}

// NewMockWebOperation creates a new mock instance.
func NewMockWebOperation(ctrl *gomock.Controller) *MockWebOperation {
	mock := &MockWebOperation{ctrl: ctrl}
	mock.recorder = &MockWebOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebOperation) EXPECT() *MockWebOperationMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockWebOperation) Run(arg0 context.Context, arg1 WebRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockWebOperationMockRecorder) Run(arg0, arg1 any) *MockWebOperationRunCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockWebOperation)(nil).Run), arg0, arg1)
	return &MockWebOperationRunCall{Call: call}
}

// MockWebOperationRunCall wrap *gomock.Call
type MockWebOperationRunCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWebOperationRunCall) Return(arg0 error) *MockWebOperationRunCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWebOperationRunCall) Do(f func(context.Context, WebRequest) error) *MockWebOperationRunCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWebOperationRunCall) DoAndReturn(f func(context.Context, WebRequest) error) *MockWebOperationRunCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockListIssuesOperation is a mock of ListIssuesOperation interface.
type MockListIssuesOperation struct {
	ctrl     *gomock.Controller
	recorder *MockListIssuesOperationMockRecorder
	isgomock struct{}
}

// MockListIssuesOperationMockRecorder is the mock recorder for MockListIssuesOperation.
type MockListIssuesOperationMockRecorder struct {
	mock *MockListIssuesOperation
}

// NewMockListIssuesOperation creates a new mock instance.
func NewMockListIssuesOperation(ctrl *gomock.Controller) *MockListIssuesOperation {
	mock := &MockListIssuesOperation{ctrl: ctrl}
	mock.recorder = &MockListIssuesOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListIssuesOperation) EXPECT() *MockListIssuesOperationMockRecorder {
	return m.recorder
}

// ListIssues mocks base method.
func (m *MockListIssuesOperation) ListIssues(arg0 context.Context, arg1 issue.ListRequest) ([]issue.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIssues", arg0, arg1)
	ret0, _ := ret[0].([]issue.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIssues indicates an expected call of ListIssues.
func (mr *MockListIssuesOperationMockRecorder) ListIssues(arg0, arg1 any) *MockListIssuesOperationListIssuesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIssues", reflect.TypeOf((*MockListIssuesOperation)(nil).ListIssues), arg0, arg1)
	return &MockListIssuesOperationListIssuesCall{Call: call}
}

// MockListIssuesOperationListIssuesCall wrap *gomock.Call
type MockListIssuesOperationListIssuesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockListIssuesOperationListIssuesCall) Return(arg0 []issue.Summary, arg1 error) *MockListIssuesOperationListIssuesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockListIssuesOperationListIssuesCall) Do(f func(context.Context, issue.ListRequest) ([]issue.Summary, error)) *MockListIssuesOperationListIssuesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockListIssuesOperationListIssuesCall) DoAndReturn(f func(context.Context, issue.ListRequest) ([]issue.Summary, error)) *MockListIssuesOperationListIssuesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockListReadyIssuesOperation is a mock of ListReadyIssuesOperation interface.
type MockListReadyIssuesOperation struct {
	ctrl     *gomock.Controller
	recorder *MockListReadyIssuesOperationMockRecorder
	isgomock struct{}
}

// MockListReadyIssuesOperationMockRecorder is the mock recorder for MockListReadyIssuesOperation.
type MockListReadyIssuesOperationMockRecorder struct {
	mock *MockListReadyIssuesOperation
}

// NewMockListReadyIssuesOperation creates a new mock instance.
func NewMockListReadyIssuesOperation(ctrl *gomock.Controller) *MockListReadyIssuesOperation {
	mock := &MockListReadyIssuesOperation{ctrl: ctrl}
	mock.recorder = &MockListReadyIssuesOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListReadyIssuesOperation) EXPECT() *MockListReadyIssuesOperationMockRecorder {
	return m.recorder
}

// ListReadyIssues mocks base method.
func (m *MockListReadyIssuesOperation) ListReadyIssues(arg0 context.Context, arg1 issue.ListReadyRequest) ([]issue.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReadyIssues", arg0, arg1)
	ret0, _ := ret[0].([]issue.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReadyIssues indicates an expected call of ListReadyIssues.
func (mr *MockListReadyIssuesOperationMockRecorder) ListReadyIssues(arg0, arg1 any) *MockListReadyIssuesOperationListReadyIssuesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReadyIssues", reflect.TypeOf((*MockListReadyIssuesOperation)(nil).ListReadyIssues), arg0, arg1)
	return &MockListReadyIssuesOperationListReadyIssuesCall{Call: call}
}

// MockListReadyIssuesOperationListReadyIssuesCall wrap *gomock.Call
type MockListReadyIssuesOperationListReadyIssuesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockListReadyIssuesOperationListReadyIssuesCall) Return(arg0 []issue.Summary, arg1 error) *MockListReadyIssuesOperationListReadyIssuesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockListReadyIssuesOperationListReadyIssuesCall) Do(f func(context.Context, issue.ListReadyRequest) ([]issue.Summary, error)) *MockListReadyIssuesOperationListReadyIssuesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockListReadyIssuesOperationListReadyIssuesCall) DoAndReturn(f func(context.Context, issue.ListReadyRequest) ([]issue.Summary, error)) *MockListReadyIssuesOperationListReadyIssuesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockListBlockedIssuesOperation is a mock of ListBlockedIssuesOperation interface.
type MockListBlockedIssuesOperation struct {
	ctrl     *gomock.Controller
	recorder *MockListBlockedIssuesOperationMockRecorder
	isgomock struct{}
}

// MockListBlockedIssuesOperationMockRecorder is the mock recorder for MockListBlockedIssuesOperation.
type MockListBlockedIssuesOperationMockRecorder struct {
	mock *MockListBlockedIssuesOperation
}

// NewMockListBlockedIssuesOperation creates a new mock instance.
func NewMockListBlockedIssuesOperation(ctrl *gomock.Controller) *MockListBlockedIssuesOperation {
	mock := &MockListBlockedIssuesOperation{ctrl: ctrl}
	mock.recorder = &MockListBlockedIssuesOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListBlockedIssuesOperation) EXPECT() *MockListBlockedIssuesOperationMockRecorder {
	return m.recorder
}

// ListBlockedIssues mocks base method.
func (m *MockListBlockedIssuesOperation) ListBlockedIssues(arg0 context.Context, arg1 issue.ListBlockedRequest) ([]issue.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBlockedIssues", arg0, arg1)
	ret0, _ := ret[0].([]issue.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlockedIssues indicates an expected call of ListBlockedIssues.
func (mr *MockListBlockedIssuesOperationMockRecorder) ListBlockedIssues(arg0, arg1 any) *MockListBlockedIssuesOperationListBlockedIssuesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlockedIssues", reflect.TypeOf((*MockListBlockedIssuesOperation)(nil).ListBlockedIssues), arg0, arg1)
	return &MockListBlockedIssuesOperationListBlockedIssuesCall{Call: call}
}

// MockListBlockedIssuesOperationListBlockedIssuesCall wrap *gomock.Call
type MockListBlockedIssuesOperationListBlockedIssuesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockListBlockedIssuesOperationListBlockedIssuesCall) Return(arg0 []issue.Summary, arg1 error) *MockListBlockedIssuesOperationListBlockedIssuesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockListBlockedIssuesOperationListBlockedIssuesCall) Do(f func(context.Context, issue.ListBlockedRequest) ([]issue.Summary, error)) *MockListBlockedIssuesOperationListBlockedIssuesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockListBlockedIssuesOperationListBlockedIssuesCall) DoAndReturn(f func(context.Context, issue.ListBlockedRequest) ([]issue.Summary, error)) *MockListBlockedIssuesOperationListBlockedIssuesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockReadIssueOperation is a mock of ReadIssueOperation interface.
type MockReadIssueOperation struct {
	ctrl     *gomock.Controller
	recorder *MockReadIssueOperationMockRecorder
	isgomock struct{}
}

// MockReadIssueOperationMockRecorder is the mock recorder for MockReadIssueOperation.
type MockReadIssueOperationMockRecorder struct {
	mock *MockReadIssueOperation
}

// NewMockReadIssueOperation creates a new mock instance.
func NewMockReadIssueOperation(ctrl *gomock.Controller) *MockReadIssueOperation {
	mock := &MockReadIssueOperation{ctrl: ctrl}
	mock.recorder = &MockReadIssueOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadIssueOperation) EXPECT() *MockReadIssueOperationMockRecorder {
	return m.recorder
}

// ReadIssue mocks base method.
func (m *MockReadIssueOperation) ReadIssue(arg0 context.Context, arg1 issue.ReadRequest) (attachment.IssueView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadIssue", arg0, arg1)
	ret0, _ := ret[0].(attachment.IssueView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadIssue indicates an expected call of ReadIssue.
func (mr *MockReadIssueOperationMockRecorder) ReadIssue(arg0, arg1 any) *MockReadIssueOperationReadIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadIssue", reflect.TypeOf((*MockReadIssueOperation)(nil).ReadIssue), arg0, arg1)
	return &MockReadIssueOperationReadIssueCall{Call: call}
}

// MockReadIssueOperationReadIssueCall wrap *gomock.Call
type MockReadIssueOperationReadIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReadIssueOperationReadIssueCall) Return(arg0 attachment.IssueView, arg1 error) *MockReadIssueOperationReadIssueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReadIssueOperationReadIssueCall) Do(f func(context.Context, issue.ReadRequest) (attachment.IssueView, error)) *MockReadIssueOperationReadIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReadIssueOperationReadIssueCall) DoAndReturn(f func(context.Context, issue.ReadRequest) (attachment.IssueView, error)) *MockReadIssueOperationReadIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCreateIssueOperation is a mock of CreateIssueOperation interface.
type MockCreateIssueOperation struct {
	ctrl     *gomock.Controller
	recorder *MockCreateIssueOperationMockRecorder
	isgomock struct{}
}

// MockCreateIssueOperationMockRecorder is the mock recorder for MockCreateIssueOperation.
type MockCreateIssueOperationMockRecorder struct {
	mock *MockCreateIssueOperation
}

// NewMockCreateIssueOperation creates a new mock instance.
func NewMockCreateIssueOperation(ctrl *gomock.Controller) *MockCreateIssueOperation {
	mock := &MockCreateIssueOperation{ctrl: ctrl}
	mock.recorder = &MockCreateIssueOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreateIssueOperation) EXPECT() *MockCreateIssueOperationMockRecorder {
	return m.recorder
}

// CreateIssue mocks base method.
func (m *MockCreateIssueOperation) CreateIssue(arg0 context.Context, arg1 issue.Invocation, arg2 planning.CreateIssueRequest) (planning.CreateIssueResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIssue", arg0, arg1, arg2)
	ret0, _ := ret[0].(planning.CreateIssueResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIssue indicates an expected call of CreateIssue.
func (mr *MockCreateIssueOperationMockRecorder) CreateIssue(arg0, arg1, arg2 any) *MockCreateIssueOperationCreateIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIssue", reflect.TypeOf((*MockCreateIssueOperation)(nil).CreateIssue), arg0, arg1, arg2)
	return &MockCreateIssueOperationCreateIssueCall{Call: call}
}

// MockCreateIssueOperationCreateIssueCall wrap *gomock.Call
type MockCreateIssueOperationCreateIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCreateIssueOperationCreateIssueCall) Return(arg0 planning.CreateIssueResult, arg1 error) *MockCreateIssueOperationCreateIssueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCreateIssueOperationCreateIssueCall) Do(f func(context.Context, issue.Invocation, planning.CreateIssueRequest) (planning.CreateIssueResult, error)) *MockCreateIssueOperationCreateIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCreateIssueOperationCreateIssueCall) DoAndReturn(f func(context.Context, issue.Invocation, planning.CreateIssueRequest) (planning.CreateIssueResult, error)) *MockCreateIssueOperationCreateIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockApplyDocumentOperation is a mock of ApplyDocumentOperation interface.
type MockApplyDocumentOperation struct {
	ctrl     *gomock.Controller
	recorder *MockApplyDocumentOperationMockRecorder
	isgomock struct{}
}

// MockApplyDocumentOperationMockRecorder is the mock recorder for MockApplyDocumentOperation.
type MockApplyDocumentOperationMockRecorder struct {
	mock *MockApplyDocumentOperation
}

// NewMockApplyDocumentOperation creates a new mock instance.
func NewMockApplyDocumentOperation(ctrl *gomock.Controller) *MockApplyDocumentOperation {
	mock := &MockApplyDocumentOperation{ctrl: ctrl}
	mock.recorder = &MockApplyDocumentOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplyDocumentOperation) EXPECT() *MockApplyDocumentOperationMockRecorder {
	return m.recorder
}

// ApplyDocument mocks base method.
func (m *MockApplyDocumentOperation) ApplyDocument(arg0 context.Context, arg1 issue.Invocation, arg2 planning.ApplyDocumentRequest) (planning.ApplyReceipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyDocument", arg0, arg1, arg2)
	ret0, _ := ret[0].(planning.ApplyReceipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyDocument indicates an expected call of ApplyDocument.
func (mr *MockApplyDocumentOperationMockRecorder) ApplyDocument(arg0, arg1, arg2 any) *MockApplyDocumentOperationApplyDocumentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyDocument", reflect.TypeOf((*MockApplyDocumentOperation)(nil).ApplyDocument), arg0, arg1, arg2)
	return &MockApplyDocumentOperationApplyDocumentCall{Call: call}
}

// MockApplyDocumentOperationApplyDocumentCall wrap *gomock.Call
type MockApplyDocumentOperationApplyDocumentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApplyDocumentOperationApplyDocumentCall) Return(arg0 planning.ApplyReceipt, arg1 error) *MockApplyDocumentOperationApplyDocumentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApplyDocumentOperationApplyDocumentCall) Do(f func(context.Context, issue.Invocation, planning.ApplyDocumentRequest) (planning.ApplyReceipt, error)) *MockApplyDocumentOperationApplyDocumentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApplyDocumentOperationApplyDocumentCall) DoAndReturn(f func(context.Context, issue.Invocation, planning.ApplyDocumentRequest) (planning.ApplyReceipt, error)) *MockApplyDocumentOperationApplyDocumentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEditIssueOperation is a mock of EditIssueOperation interface.
type MockEditIssueOperation struct {
	ctrl     *gomock.Controller
	recorder *MockEditIssueOperationMockRecorder
	isgomock struct{}
}

// MockEditIssueOperationMockRecorder is the mock recorder for MockEditIssueOperation.
type MockEditIssueOperationMockRecorder struct {
	mock *MockEditIssueOperation
}

// NewMockEditIssueOperation creates a new mock instance.
func NewMockEditIssueOperation(ctrl *gomock.Controller) *MockEditIssueOperation {
	mock := &MockEditIssueOperation{ctrl: ctrl}
	mock.recorder = &MockEditIssueOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEditIssueOperation) EXPECT() *MockEditIssueOperationMockRecorder {
	return m.recorder
}

// EditIssue mocks base method.
func (m *MockEditIssueOperation) EditIssue(arg0 context.Context, arg1 issue.Invocation, arg2 planning.EditIssueRequest) (planning.EditIssueResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditIssue", arg0, arg1, arg2)
	ret0, _ := ret[0].(planning.EditIssueResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditIssue indicates an expected call of EditIssue.
func (mr *MockEditIssueOperationMockRecorder) EditIssue(arg0, arg1, arg2 any) *MockEditIssueOperationEditIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditIssue", reflect.TypeOf((*MockEditIssueOperation)(nil).EditIssue), arg0, arg1, arg2)
	return &MockEditIssueOperationEditIssueCall{Call: call}
}

// MockEditIssueOperationEditIssueCall wrap *gomock.Call
type MockEditIssueOperationEditIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEditIssueOperationEditIssueCall) Return(arg0 planning.EditIssueResult, arg1 error) *MockEditIssueOperationEditIssueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEditIssueOperationEditIssueCall) Do(f func(context.Context, issue.Invocation, planning.EditIssueRequest) (planning.EditIssueResult, error)) *MockEditIssueOperationEditIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEditIssueOperationEditIssueCall) DoAndReturn(f func(context.Context, issue.Invocation, planning.EditIssueRequest) (planning.EditIssueResult, error)) *MockEditIssueOperationEditIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockClaimOperations is a mock of ClaimOperations interface.
type MockClaimOperations struct {
	ctrl     *gomock.Controller
	recorder *MockClaimOperationsMockRecorder
	isgomock struct{}
}

// MockClaimOperationsMockRecorder is the mock recorder for MockClaimOperations.
type MockClaimOperationsMockRecorder struct {
	mock *MockClaimOperations
}

// NewMockClaimOperations creates a new mock instance.
func NewMockClaimOperations(ctrl *gomock.Controller) *MockClaimOperations {
	mock := &MockClaimOperations{ctrl: ctrl}
	mock.recorder = &MockClaimOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClaimOperations) EXPECT() *MockClaimOperationsMockRecorder {
	return m.recorder
}

// ClaimIssue mocks base method.
func (m *MockClaimOperations) ClaimIssue(arg0 context.Context, arg1 issue.Invocation, arg2 execution.ClaimIssueRequest) (execution.ClaimIssueResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimIssue", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.ClaimIssueResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimIssue indicates an expected call of ClaimIssue.
func (mr *MockClaimOperationsMockRecorder) ClaimIssue(arg0, arg1, arg2 any) *MockClaimOperationsClaimIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimIssue", reflect.TypeOf((*MockClaimOperations)(nil).ClaimIssue), arg0, arg1, arg2)
	return &MockClaimOperationsClaimIssueCall{Call: call}
}

// MockClaimOperationsClaimIssueCall wrap *gomock.Call
type MockClaimOperationsClaimIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClaimOperationsClaimIssueCall) Return(arg0 execution.ClaimIssueResult, arg1 error) *MockClaimOperationsClaimIssueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClaimOperationsClaimIssueCall) Do(f func(context.Context, issue.Invocation, execution.ClaimIssueRequest) (execution.ClaimIssueResult, error)) *MockClaimOperationsClaimIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClaimOperationsClaimIssueCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.ClaimIssueRequest) (execution.ClaimIssueResult, error)) *MockClaimOperationsClaimIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ClaimNext mocks base method.
func (m *MockClaimOperations) ClaimNext(arg0 context.Context, arg1 issue.Invocation, arg2 execution.ClaimNextRequest) (execution.ClaimIssueResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimNext", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.ClaimIssueResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimNext indicates an expected call of ClaimNext.
func (mr *MockClaimOperationsMockRecorder) ClaimNext(arg0, arg1, arg2 any) *MockClaimOperationsClaimNextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimNext", reflect.TypeOf((*MockClaimOperations)(nil).ClaimNext), arg0, arg1, arg2)
	return &MockClaimOperationsClaimNextCall{Call: call}
}

// MockClaimOperationsClaimNextCall wrap *gomock.Call
type MockClaimOperationsClaimNextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClaimOperationsClaimNextCall) Return(arg0 execution.ClaimIssueResult, arg1 error) *MockClaimOperationsClaimNextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClaimOperationsClaimNextCall) Do(f func(context.Context, issue.Invocation, execution.ClaimNextRequest) (execution.ClaimIssueResult, error)) *MockClaimOperationsClaimNextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClaimOperationsClaimNextCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.ClaimNextRequest) (execution.ClaimIssueResult, error)) *MockClaimOperationsClaimNextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockReleaseOperations is a mock of ReleaseOperations interface.
type MockReleaseOperations struct {
	ctrl     *gomock.Controller
	recorder *MockReleaseOperationsMockRecorder
	isgomock struct{}
}

// MockReleaseOperationsMockRecorder is the mock recorder for MockReleaseOperations.
type MockReleaseOperationsMockRecorder struct {
	mock *MockReleaseOperations
}

// NewMockReleaseOperations creates a new mock instance.
func NewMockReleaseOperations(ctrl *gomock.Controller) *MockReleaseOperations {
	mock := &MockReleaseOperations{ctrl: ctrl}
	mock.recorder = &MockReleaseOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReleaseOperations) EXPECT() *MockReleaseOperationsMockRecorder {
	return m.recorder
}

// ReleaseIssue mocks base method.
func (m *MockReleaseOperations) ReleaseIssue(arg0 context.Context, arg1 issue.Invocation, arg2 execution.ReleaseIssueRequest) (execution.ReleaseIssueResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseIssue", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.ReleaseIssueResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseIssue indicates an expected call of ReleaseIssue.
func (mr *MockReleaseOperationsMockRecorder) ReleaseIssue(arg0, arg1, arg2 any) *MockReleaseOperationsReleaseIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseIssue", reflect.TypeOf((*MockReleaseOperations)(nil).ReleaseIssue), arg0, arg1, arg2)
	return &MockReleaseOperationsReleaseIssueCall{Call: call}
}

// MockReleaseOperationsReleaseIssueCall wrap *gomock.Call
type MockReleaseOperationsReleaseIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReleaseOperationsReleaseIssueCall) Return(arg0 execution.ReleaseIssueResult, arg1 error) *MockReleaseOperationsReleaseIssueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReleaseOperationsReleaseIssueCall) Do(f func(context.Context, issue.Invocation, execution.ReleaseIssueRequest) (execution.ReleaseIssueResult, error)) *MockReleaseOperationsReleaseIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReleaseOperationsReleaseIssueCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.ReleaseIssueRequest) (execution.ReleaseIssueResult, error)) *MockReleaseOperationsReleaseIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCloseOperations is a mock of CloseOperations interface.
type MockCloseOperations struct {
	ctrl     *gomock.Controller
	recorder *MockCloseOperationsMockRecorder
	isgomock struct{}
}

// MockCloseOperationsMockRecorder is the mock recorder for MockCloseOperations.
type MockCloseOperationsMockRecorder struct {
	mock *MockCloseOperations
}

// NewMockCloseOperations creates a new mock instance.
func NewMockCloseOperations(ctrl *gomock.Controller) *MockCloseOperations {
	mock := &MockCloseOperations{ctrl: ctrl}
	mock.recorder = &MockCloseOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloseOperations) EXPECT() *MockCloseOperationsMockRecorder {
	return m.recorder
}

// CloseIssues mocks base method.
func (m *MockCloseOperations) CloseIssues(arg0 context.Context, arg1 issue.Invocation, arg2 execution.CloseIssuesRequest) (execution.CloseIssuesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseIssues", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.CloseIssuesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseIssues indicates an expected call of CloseIssues.
func (mr *MockCloseOperationsMockRecorder) CloseIssues(arg0, arg1, arg2 any) *MockCloseOperationsCloseIssuesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseIssues", reflect.TypeOf((*MockCloseOperations)(nil).CloseIssues), arg0, arg1, arg2)
	return &MockCloseOperationsCloseIssuesCall{Call: call}
}

// MockCloseOperationsCloseIssuesCall wrap *gomock.Call
type MockCloseOperationsCloseIssuesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCloseOperationsCloseIssuesCall) Return(arg0 execution.CloseIssuesResult, arg1 error) *MockCloseOperationsCloseIssuesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCloseOperationsCloseIssuesCall) Do(f func(context.Context, issue.Invocation, execution.CloseIssuesRequest) (execution.CloseIssuesResult, error)) *MockCloseOperationsCloseIssuesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCloseOperationsCloseIssuesCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.CloseIssuesRequest) (execution.CloseIssuesResult, error)) *MockCloseOperationsCloseIssuesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCancelOperations is a mock of CancelOperations interface.
type MockCancelOperations struct {
	ctrl     *gomock.Controller
	recorder *MockCancelOperationsMockRecorder
	isgomock struct{}
}

// MockCancelOperationsMockRecorder is the mock recorder for MockCancelOperations.
type MockCancelOperationsMockRecorder struct {
	mock *MockCancelOperations
}

// NewMockCancelOperations creates a new mock instance.
func NewMockCancelOperations(ctrl *gomock.Controller) *MockCancelOperations {
	mock := &MockCancelOperations{ctrl: ctrl}
	mock.recorder = &MockCancelOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCancelOperations) EXPECT() *MockCancelOperationsMockRecorder {
	return m.recorder
}

// CancelIssues mocks base method.
func (m *MockCancelOperations) CancelIssues(arg0 context.Context, arg1 issue.Invocation, arg2 execution.CancelIssuesRequest) (execution.CancelIssuesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelIssues", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.CancelIssuesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelIssues indicates an expected call of CancelIssues.
func (mr *MockCancelOperationsMockRecorder) CancelIssues(arg0, arg1, arg2 any) *MockCancelOperationsCancelIssuesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelIssues", reflect.TypeOf((*MockCancelOperations)(nil).CancelIssues), arg0, arg1, arg2)
	return &MockCancelOperationsCancelIssuesCall{Call: call}
}

// MockCancelOperationsCancelIssuesCall wrap *gomock.Call
type MockCancelOperationsCancelIssuesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCancelOperationsCancelIssuesCall) Return(arg0 execution.CancelIssuesResult, arg1 error) *MockCancelOperationsCancelIssuesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCancelOperationsCancelIssuesCall) Do(f func(context.Context, issue.Invocation, execution.CancelIssuesRequest) (execution.CancelIssuesResult, error)) *MockCancelOperationsCancelIssuesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCancelOperationsCancelIssuesCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.CancelIssuesRequest) (execution.CancelIssuesResult, error)) *MockCancelOperationsCancelIssuesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockReopenOperations is a mock of ReopenOperations interface.
type MockReopenOperations struct {
	ctrl     *gomock.Controller
	recorder *MockReopenOperationsMockRecorder
	isgomock struct{}
}

// MockReopenOperationsMockRecorder is the mock recorder for MockReopenOperations.
type MockReopenOperationsMockRecorder struct {
	mock *MockReopenOperations
}

// NewMockReopenOperations creates a new mock instance.
func NewMockReopenOperations(ctrl *gomock.Controller) *MockReopenOperations {
	mock := &MockReopenOperations{ctrl: ctrl}
	mock.recorder = &MockReopenOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReopenOperations) EXPECT() *MockReopenOperationsMockRecorder {
	return m.recorder
}

// ReopenIssues mocks base method.
func (m *MockReopenOperations) ReopenIssues(arg0 context.Context, arg1 issue.Invocation, arg2 execution.ReopenIssuesRequest) (execution.ReopenIssuesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReopenIssues", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.ReopenIssuesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReopenIssues indicates an expected call of ReopenIssues.
func (mr *MockReopenOperationsMockRecorder) ReopenIssues(arg0, arg1, arg2 any) *MockReopenOperationsReopenIssuesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReopenIssues", reflect.TypeOf((*MockReopenOperations)(nil).ReopenIssues), arg0, arg1, arg2)
	return &MockReopenOperationsReopenIssuesCall{Call: call}
}

// MockReopenOperationsReopenIssuesCall wrap *gomock.Call
type MockReopenOperationsReopenIssuesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReopenOperationsReopenIssuesCall) Return(arg0 execution.ReopenIssuesResult, arg1 error) *MockReopenOperationsReopenIssuesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReopenOperationsReopenIssuesCall) Do(f func(context.Context, issue.Invocation, execution.ReopenIssuesRequest) (execution.ReopenIssuesResult, error)) *MockReopenOperationsReopenIssuesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReopenOperationsReopenIssuesCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.ReopenIssuesRequest) (execution.ReopenIssuesResult, error)) *MockReopenOperationsReopenIssuesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCheckpointOperations is a mock of CheckpointOperations interface.
type MockCheckpointOperations struct {
	ctrl     *gomock.Controller
	recorder *MockCheckpointOperationsMockRecorder
	isgomock struct{}
}

// MockCheckpointOperationsMockRecorder is the mock recorder for MockCheckpointOperations.
type MockCheckpointOperationsMockRecorder struct {
	mock *MockCheckpointOperations
}

// NewMockCheckpointOperations creates a new mock instance.
func NewMockCheckpointOperations(ctrl *gomock.Controller) *MockCheckpointOperations {
	mock := &MockCheckpointOperations{ctrl: ctrl}
	mock.recorder = &MockCheckpointOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCheckpointOperations) EXPECT() *MockCheckpointOperationsMockRecorder {
	return m.recorder
}

// ApproveCheckpoint mocks base method.
func (m *MockCheckpointOperations) ApproveCheckpoint(arg0 context.Context, arg1 issue.Invocation, arg2 execution.CheckpointRequest) (execution.ResolveCheckpointResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveCheckpoint", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.ResolveCheckpointResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveCheckpoint indicates an expected call of ApproveCheckpoint.
func (mr *MockCheckpointOperationsMockRecorder) ApproveCheckpoint(arg0, arg1, arg2 any) *MockCheckpointOperationsApproveCheckpointCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveCheckpoint", reflect.TypeOf((*MockCheckpointOperations)(nil).ApproveCheckpoint), arg0, arg1, arg2)
	return &MockCheckpointOperationsApproveCheckpointCall{Call: call}
}

// MockCheckpointOperationsApproveCheckpointCall wrap *gomock.Call
type MockCheckpointOperationsApproveCheckpointCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCheckpointOperationsApproveCheckpointCall) Return(arg0 execution.ResolveCheckpointResult, arg1 error) *MockCheckpointOperationsApproveCheckpointCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCheckpointOperationsApproveCheckpointCall) Do(f func(context.Context, issue.Invocation, execution.CheckpointRequest) (execution.ResolveCheckpointResult, error)) *MockCheckpointOperationsApproveCheckpointCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCheckpointOperationsApproveCheckpointCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.CheckpointRequest) (execution.ResolveCheckpointResult, error)) *MockCheckpointOperationsApproveCheckpointCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DenyCheckpoint mocks base method.
func (m *MockCheckpointOperations) DenyCheckpoint(arg0 context.Context, arg1 issue.Invocation, arg2 execution.CheckpointRequest) (execution.ResolveCheckpointResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DenyCheckpoint", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.ResolveCheckpointResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DenyCheckpoint indicates an expected call of DenyCheckpoint.
func (mr *MockCheckpointOperationsMockRecorder) DenyCheckpoint(arg0, arg1, arg2 any) *MockCheckpointOperationsDenyCheckpointCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DenyCheckpoint", reflect.TypeOf((*MockCheckpointOperations)(nil).DenyCheckpoint), arg0, arg1, arg2)
	return &MockCheckpointOperationsDenyCheckpointCall{Call: call}
}

// MockCheckpointOperationsDenyCheckpointCall wrap *gomock.Call
type MockCheckpointOperationsDenyCheckpointCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCheckpointOperationsDenyCheckpointCall) Return(arg0 execution.ResolveCheckpointResult, arg1 error) *MockCheckpointOperationsDenyCheckpointCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCheckpointOperationsDenyCheckpointCall) Do(f func(context.Context, issue.Invocation, execution.CheckpointRequest) (execution.ResolveCheckpointResult, error)) *MockCheckpointOperationsDenyCheckpointCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCheckpointOperationsDenyCheckpointCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.CheckpointRequest) (execution.ResolveCheckpointResult, error)) *MockCheckpointOperationsDenyCheckpointCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockLogEntryWriteOperations is a mock of LogEntryWriteOperations interface.
type MockLogEntryWriteOperations struct {
	ctrl     *gomock.Controller
	recorder *MockLogEntryWriteOperationsMockRecorder
	isgomock struct{}
}

// MockLogEntryWriteOperationsMockRecorder is the mock recorder for MockLogEntryWriteOperations.
type MockLogEntryWriteOperationsMockRecorder struct {
	mock *MockLogEntryWriteOperations
}

// NewMockLogEntryWriteOperations creates a new mock instance.
func NewMockLogEntryWriteOperations(ctrl *gomock.Controller) *MockLogEntryWriteOperations {
	mock := &MockLogEntryWriteOperations{ctrl: ctrl}
	mock.recorder = &MockLogEntryWriteOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogEntryWriteOperations) EXPECT() *MockLogEntryWriteOperationsMockRecorder {
	return m.recorder
}

// AddLogEntry mocks base method.
func (m *MockLogEntryWriteOperations) AddLogEntry(arg0 context.Context, arg1 issue.Invocation, arg2 record.AddLogEntryRequest) (record.AddLogEntryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLogEntry", arg0, arg1, arg2)
	ret0, _ := ret[0].(record.AddLogEntryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLogEntry indicates an expected call of AddLogEntry.
func (mr *MockLogEntryWriteOperationsMockRecorder) AddLogEntry(arg0, arg1, arg2 any) *MockLogEntryWriteOperationsAddLogEntryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLogEntry", reflect.TypeOf((*MockLogEntryWriteOperations)(nil).AddLogEntry), arg0, arg1, arg2)
	return &MockLogEntryWriteOperationsAddLogEntryCall{Call: call}
}

// MockLogEntryWriteOperationsAddLogEntryCall wrap *gomock.Call
type MockLogEntryWriteOperationsAddLogEntryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLogEntryWriteOperationsAddLogEntryCall) Return(arg0 record.AddLogEntryResult, arg1 error) *MockLogEntryWriteOperationsAddLogEntryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLogEntryWriteOperationsAddLogEntryCall) Do(f func(context.Context, issue.Invocation, record.AddLogEntryRequest) (record.AddLogEntryResult, error)) *MockLogEntryWriteOperationsAddLogEntryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLogEntryWriteOperationsAddLogEntryCall) DoAndReturn(f func(context.Context, issue.Invocation, record.AddLogEntryRequest) (record.AddLogEntryResult, error)) *MockLogEntryWriteOperationsAddLogEntryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockLogEntryReadOperations is a mock of LogEntryReadOperations interface.
type MockLogEntryReadOperations struct {
	ctrl     *gomock.Controller
	recorder *MockLogEntryReadOperationsMockRecorder
	isgomock struct{}
}

// MockLogEntryReadOperationsMockRecorder is the mock recorder for MockLogEntryReadOperations.
type MockLogEntryReadOperationsMockRecorder struct {
	mock *MockLogEntryReadOperations
}

// NewMockLogEntryReadOperations creates a new mock instance.
func NewMockLogEntryReadOperations(ctrl *gomock.Controller) *MockLogEntryReadOperations {
	mock := &MockLogEntryReadOperations{ctrl: ctrl}
	mock.recorder = &MockLogEntryReadOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogEntryReadOperations) EXPECT() *MockLogEntryReadOperationsMockRecorder {
	return m.recorder
}

// ListLogEntries mocks base method.
func (m *MockLogEntryReadOperations) ListLogEntries(arg0 context.Context, arg1 issue.LogListRequest) ([]issue.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLogEntries", arg0, arg1)
	ret0, _ := ret[0].([]issue.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLogEntries indicates an expected call of ListLogEntries.
func (mr *MockLogEntryReadOperationsMockRecorder) ListLogEntries(arg0, arg1 any) *MockLogEntryReadOperationsListLogEntriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLogEntries", reflect.TypeOf((*MockLogEntryReadOperations)(nil).ListLogEntries), arg0, arg1)
	return &MockLogEntryReadOperationsListLogEntriesCall{Call: call}
}

// MockLogEntryReadOperationsListLogEntriesCall wrap *gomock.Call
type MockLogEntryReadOperationsListLogEntriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLogEntryReadOperationsListLogEntriesCall) Return(arg0 []issue.LogEntry, arg1 error) *MockLogEntryReadOperationsListLogEntriesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLogEntryReadOperationsListLogEntriesCall) Do(f func(context.Context, issue.LogListRequest) ([]issue.LogEntry, error)) *MockLogEntryReadOperationsListLogEntriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLogEntryReadOperationsListLogEntriesCall) DoAndReturn(f func(context.Context, issue.LogListRequest) ([]issue.LogEntry, error)) *MockLogEntryReadOperationsListLogEntriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockStateWriteOperations is a mock of StateWriteOperations interface.
type MockStateWriteOperations struct {
	ctrl     *gomock.Controller
	recorder *MockStateWriteOperationsMockRecorder
	isgomock struct{}
}

// MockStateWriteOperationsMockRecorder is the mock recorder for MockStateWriteOperations.
type MockStateWriteOperationsMockRecorder struct {
	mock *MockStateWriteOperations
}

// NewMockStateWriteOperations creates a new mock instance.
func NewMockStateWriteOperations(ctrl *gomock.Controller) *MockStateWriteOperations {
	mock := &MockStateWriteOperations{ctrl: ctrl}
	mock.recorder = &MockStateWriteOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateWriteOperations) EXPECT() *MockStateWriteOperationsMockRecorder {
	return m.recorder
}

// AppendState mocks base method.
func (m *MockStateWriteOperations) AppendState(arg0 context.Context, arg1 issue.Invocation, arg2 record.SetStateRequest) (record.StateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendState", arg0, arg1, arg2)
	ret0, _ := ret[0].(record.StateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendState indicates an expected call of AppendState.
func (mr *MockStateWriteOperationsMockRecorder) AppendState(arg0, arg1, arg2 any) *MockStateWriteOperationsAppendStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendState", reflect.TypeOf((*MockStateWriteOperations)(nil).AppendState), arg0, arg1, arg2)
	return &MockStateWriteOperationsAppendStateCall{Call: call}
}

// MockStateWriteOperationsAppendStateCall wrap *gomock.Call
type MockStateWriteOperationsAppendStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateWriteOperationsAppendStateCall) Return(arg0 record.StateResult, arg1 error) *MockStateWriteOperationsAppendStateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateWriteOperationsAppendStateCall) Do(f func(context.Context, issue.Invocation, record.SetStateRequest) (record.StateResult, error)) *MockStateWriteOperationsAppendStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateWriteOperationsAppendStateCall) DoAndReturn(f func(context.Context, issue.Invocation, record.SetStateRequest) (record.StateResult, error)) *MockStateWriteOperationsAppendStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetState mocks base method.
func (m *MockStateWriteOperations) SetState(arg0 context.Context, arg1 issue.Invocation, arg2 record.SetStateRequest) (record.StateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetState", arg0, arg1, arg2)
	ret0, _ := ret[0].(record.StateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetState indicates an expected call of SetState.
func (mr *MockStateWriteOperationsMockRecorder) SetState(arg0, arg1, arg2 any) *MockStateWriteOperationsSetStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetState", reflect.TypeOf((*MockStateWriteOperations)(nil).SetState), arg0, arg1, arg2)
	return &MockStateWriteOperationsSetStateCall{Call: call}
}

// MockStateWriteOperationsSetStateCall wrap *gomock.Call
type MockStateWriteOperationsSetStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateWriteOperationsSetStateCall) Return(arg0 record.StateResult, arg1 error) *MockStateWriteOperationsSetStateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateWriteOperationsSetStateCall) Do(f func(context.Context, issue.Invocation, record.SetStateRequest) (record.StateResult, error)) *MockStateWriteOperationsSetStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateWriteOperationsSetStateCall) DoAndReturn(f func(context.Context, issue.Invocation, record.SetStateRequest) (record.StateResult, error)) *MockStateWriteOperationsSetStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockStateReadOperations is a mock of StateReadOperations interface.
type MockStateReadOperations struct {
	ctrl     *gomock.Controller
	recorder *MockStateReadOperationsMockRecorder
	isgomock struct{}
}

// MockStateReadOperationsMockRecorder is the mock recorder for MockStateReadOperations.
type MockStateReadOperationsMockRecorder struct {
	mock *MockStateReadOperations
}

// NewMockStateReadOperations creates a new mock instance.
func NewMockStateReadOperations(ctrl *gomock.Controller) *MockStateReadOperations {
	mock := &MockStateReadOperations{ctrl: ctrl}
	mock.recorder = &MockStateReadOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateReadOperations) EXPECT() *MockStateReadOperationsMockRecorder {
	return m.recorder
}

// GetState mocks base method.
func (m *MockStateReadOperations) GetState(arg0 context.Context, arg1 record.GetStateRequest) (record.GetStateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState", arg0, arg1)
	ret0, _ := ret[0].(record.GetStateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetState indicates an expected call of GetState.
func (mr *MockStateReadOperationsMockRecorder) GetState(arg0, arg1 any) *MockStateReadOperationsGetStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockStateReadOperations)(nil).GetState), arg0, arg1)
	return &MockStateReadOperationsGetStateCall{Call: call}
}

// MockStateReadOperationsGetStateCall wrap *gomock.Call
type MockStateReadOperationsGetStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateReadOperationsGetStateCall) Return(arg0 record.GetStateResult, arg1 error) *MockStateReadOperationsGetStateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateReadOperationsGetStateCall) Do(f func(context.Context, record.GetStateRequest) (record.GetStateResult, error)) *MockStateReadOperationsGetStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateReadOperationsGetStateCall) DoAndReturn(f func(context.Context, record.GetStateRequest) (record.GetStateResult, error)) *MockStateReadOperationsGetStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockStateCommitOperations is a mock of StateCommitOperations interface.
type MockStateCommitOperations struct {
	ctrl     *gomock.Controller
	recorder *MockStateCommitOperationsMockRecorder
	isgomock struct{}
}

// MockStateCommitOperationsMockRecorder is the mock recorder for MockStateCommitOperations.
type MockStateCommitOperationsMockRecorder struct {
	mock *MockStateCommitOperations
}

// NewMockStateCommitOperations creates a new mock instance.
func NewMockStateCommitOperations(ctrl *gomock.Controller) *MockStateCommitOperations {
	mock := &MockStateCommitOperations{ctrl: ctrl}
	mock.recorder = &MockStateCommitOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateCommitOperations) EXPECT() *MockStateCommitOperationsMockRecorder {
	return m.recorder
}

// CommitState mocks base method.
func (m *MockStateCommitOperations) CommitState(arg0 context.Context, arg1 issue.Invocation, arg2 record.CommitStateRequest) (record.CommitStateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitState", arg0, arg1, arg2)
	ret0, _ := ret[0].(record.CommitStateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitState indicates an expected call of CommitState.
func (mr *MockStateCommitOperationsMockRecorder) CommitState(arg0, arg1, arg2 any) *MockStateCommitOperationsCommitStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitState", reflect.TypeOf((*MockStateCommitOperations)(nil).CommitState), arg0, arg1, arg2)
	return &MockStateCommitOperationsCommitStateCall{Call: call}
}

// MockStateCommitOperationsCommitStateCall wrap *gomock.Call
type MockStateCommitOperationsCommitStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStateCommitOperationsCommitStateCall) Return(arg0 record.CommitStateResult, arg1 error) *MockStateCommitOperationsCommitStateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStateCommitOperationsCommitStateCall) Do(f func(context.Context, issue.Invocation, record.CommitStateRequest) (record.CommitStateResult, error)) *MockStateCommitOperationsCommitStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStateCommitOperationsCommitStateCall) DoAndReturn(f func(context.Context, issue.Invocation, record.CommitStateRequest) (record.CommitStateResult, error)) *MockStateCommitOperationsCommitStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockResultWriteOperations is a mock of ResultWriteOperations interface.
type MockResultWriteOperations struct {
	ctrl     *gomock.Controller
	recorder *MockResultWriteOperationsMockRecorder
	isgomock struct{}
}

// MockResultWriteOperationsMockRecorder is the mock recorder for MockResultWriteOperations.
type MockResultWriteOperationsMockRecorder struct {
	mock *MockResultWriteOperations
}

// NewMockResultWriteOperations creates a new mock instance.
func NewMockResultWriteOperations(ctrl *gomock.Controller) *MockResultWriteOperations {
	mock := &MockResultWriteOperations{ctrl: ctrl}
	mock.recorder = &MockResultWriteOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResultWriteOperations) EXPECT() *MockResultWriteOperationsMockRecorder {
	return m.recorder
}

// SetResult mocks base method.
func (m *MockResultWriteOperations) SetResult(arg0 context.Context, arg1 issue.Invocation, arg2 record.SetResultRequest) (record.SetResultResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetResult", arg0, arg1, arg2)
	ret0, _ := ret[0].(record.SetResultResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetResult indicates an expected call of SetResult.
func (mr *MockResultWriteOperationsMockRecorder) SetResult(arg0, arg1, arg2 any) *MockResultWriteOperationsSetResultCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetResult", reflect.TypeOf((*MockResultWriteOperations)(nil).SetResult), arg0, arg1, arg2)
	return &MockResultWriteOperationsSetResultCall{Call: call}
}

// MockResultWriteOperationsSetResultCall wrap *gomock.Call
type MockResultWriteOperationsSetResultCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResultWriteOperationsSetResultCall) Return(arg0 record.SetResultResult, arg1 error) *MockResultWriteOperationsSetResultCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResultWriteOperationsSetResultCall) Do(f func(context.Context, issue.Invocation, record.SetResultRequest) (record.SetResultResult, error)) *MockResultWriteOperationsSetResultCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResultWriteOperationsSetResultCall) DoAndReturn(f func(context.Context, issue.Invocation, record.SetResultRequest) (record.SetResultResult, error)) *MockResultWriteOperationsSetResultCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockResultReadOperations is a mock of ResultReadOperations interface.
type MockResultReadOperations struct {
	ctrl     *gomock.Controller
	recorder *MockResultReadOperationsMockRecorder
	isgomock struct{}
}

// MockResultReadOperationsMockRecorder is the mock recorder for MockResultReadOperations.
type MockResultReadOperationsMockRecorder struct {
	mock *MockResultReadOperations
}

// NewMockResultReadOperations creates a new mock instance.
func NewMockResultReadOperations(ctrl *gomock.Controller) *MockResultReadOperations {
	mock := &MockResultReadOperations{ctrl: ctrl}
	mock.recorder = &MockResultReadOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResultReadOperations) EXPECT() *MockResultReadOperationsMockRecorder {
	return m.recorder
}

// GetResult mocks base method.
func (m *MockResultReadOperations) GetResult(arg0 context.Context, arg1 record.GetResultRequest) (issue.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResult", arg0, arg1)
	ret0, _ := ret[0].(issue.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResult indicates an expected call of GetResult.
func (mr *MockResultReadOperationsMockRecorder) GetResult(arg0, arg1 any) *MockResultReadOperationsGetResultCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResult", reflect.TypeOf((*MockResultReadOperations)(nil).GetResult), arg0, arg1)
	return &MockResultReadOperationsGetResultCall{Call: call}
}

// MockResultReadOperationsGetResultCall wrap *gomock.Call
type MockResultReadOperationsGetResultCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockResultReadOperationsGetResultCall) Return(arg0 issue.Result, arg1 error) *MockResultReadOperationsGetResultCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockResultReadOperationsGetResultCall) Do(f func(context.Context, record.GetResultRequest) (issue.Result, error)) *MockResultReadOperationsGetResultCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockResultReadOperationsGetResultCall) DoAndReturn(f func(context.Context, record.GetResultRequest) (issue.Result, error)) *MockResultReadOperationsGetResultCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
