// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/cli (interfaces: SearchIssuesOperation)
//
// Generated by this command:
//
//	mockgen -destination search_mocks_test.go -package cli -typed -write_package_comment=false . SearchIssuesOperation
//

package cli

import (
	context "context"
	reflect "reflect"

	issue "go.abhg.dev/cardamom/internal/issue"
	gomock "go.uber.org/mock/gomock"
)

// MockSearchIssuesOperation is a mock of SearchIssuesOperation interface.
type MockSearchIssuesOperation struct {
	ctrl     *gomock.Controller
	recorder *MockSearchIssuesOperationMockRecorder
	isgomock struct{}
}

// MockSearchIssuesOperationMockRecorder is the mock recorder for MockSearchIssuesOperation.
type MockSearchIssuesOperationMockRecorder struct {
	mock *MockSearchIssuesOperation
}

// NewMockSearchIssuesOperation creates a new mock instance.
func NewMockSearchIssuesOperation(ctrl *gomock.Controller) *MockSearchIssuesOperation {
	mock := &MockSearchIssuesOperation{ctrl: ctrl}
	mock.recorder = &MockSearchIssuesOperationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchIssuesOperation) EXPECT() *MockSearchIssuesOperationMockRecorder {
	return m.recorder
}

// SearchIssues mocks base method.
func (m *MockSearchIssuesOperation) SearchIssues(arg0 context.Context, arg1 issue.SearchRequest) (issue.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchIssues", arg0, arg1)
	ret0, _ := ret[0].(issue.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchIssues indicates an expected call of SearchIssues.
func (mr *MockSearchIssuesOperationMockRecorder) SearchIssues(arg0, arg1 any) *MockSearchIssuesOperationSearchIssuesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchIssues", reflect.TypeOf((*MockSearchIssuesOperation)(nil).SearchIssues), arg0, arg1)
	return &MockSearchIssuesOperationSearchIssuesCall{Call: call}
}

// MockSearchIssuesOperationSearchIssuesCall wrap *gomock.Call
type MockSearchIssuesOperationSearchIssuesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSearchIssuesOperationSearchIssuesCall) Return(arg0 issue.SearchResult, arg1 error) *MockSearchIssuesOperationSearchIssuesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSearchIssuesOperationSearchIssuesCall) Do(f func(context.Context, issue.SearchRequest) (issue.SearchResult, error)) *MockSearchIssuesOperationSearchIssuesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSearchIssuesOperationSearchIssuesCall) DoAndReturn(f func(context.Context, issue.SearchRequest) (issue.SearchResult, error)) *MockSearchIssuesOperationSearchIssuesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
