// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/project (interfaces: Projects,Changes)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package project -typed -write_package_comment=false . Projects,Changes
//

package project

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProjects is a mock of Projects interface.
type MockProjects struct {
	ctrl     *gomock.Controller
	recorder *MockProjectsMockRecorder
	isgomock struct{}
}

// MockProjectsMockRecorder is the mock recorder for MockProjects.
type MockProjectsMockRecorder struct {
	mock *MockProjects
}

// NewMockProjects creates a new mock instance.
func NewMockProjects(ctrl *gomock.Controller) *MockProjects {
	mock := &MockProjects{ctrl: ctrl}
	mock.recorder = &MockProjectsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjects) EXPECT() *MockProjectsMockRecorder {
	return m.recorder
}

// ListProjects mocks base method.
func (m *MockProjects) ListProjects(arg0 context.Context) ([]*State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProjects", arg0)
	ret0, _ := ret[0].([]*State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProjects indicates an expected call of ListProjects.
func (mr *MockProjectsMockRecorder) ListProjects(arg0 any) *MockProjectsListProjectsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProjects", reflect.TypeOf((*MockProjects)(nil).ListProjects), arg0)
	return &MockProjectsListProjectsCall{Call: call}
}

// MockProjectsListProjectsCall wrap *gomock.Call
type MockProjectsListProjectsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectsListProjectsCall) Return(arg0 []*State, arg1 error) *MockProjectsListProjectsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectsListProjectsCall) Do(f func(context.Context) ([]*State, error)) *MockProjectsListProjectsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectsListProjectsCall) DoAndReturn(f func(context.Context) ([]*State, error)) *MockProjectsListProjectsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockChanges is a mock of Changes interface.
type MockChanges struct {
	ctrl     *gomock.Controller
	recorder *MockChangesMockRecorder
	isgomock struct{}
}

// MockChangesMockRecorder is the mock recorder for MockChanges.
type MockChangesMockRecorder struct {
	mock *MockChanges
}

// NewMockChanges creates a new mock instance.
func NewMockChanges(ctrl *gomock.Controller) *MockChanges {
	mock := &MockChanges{ctrl: ctrl}
	mock.recorder = &MockChangesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChanges) EXPECT() *MockChangesMockRecorder {
	return m.recorder
}

// EditProjectName mocks base method.
func (m *MockChanges) EditProjectName(arg0 context.Context, arg1 EditNameRequest) (*State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditProjectName", arg0, arg1)
	ret0, _ := ret[0].(*State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditProjectName indicates an expected call of EditProjectName.
func (mr *MockChangesMockRecorder) EditProjectName(arg0, arg1 any) *MockChangesEditProjectNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditProjectName", reflect.TypeOf((*MockChanges)(nil).EditProjectName), arg0, arg1)
	return &MockChangesEditProjectNameCall{Call: call}
}

// MockChangesEditProjectNameCall wrap *gomock.Call
type MockChangesEditProjectNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangesEditProjectNameCall) Return(arg0 *State, arg1 error) *MockChangesEditProjectNameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangesEditProjectNameCall) Do(f func(context.Context, EditNameRequest) (*State, error)) *MockChangesEditProjectNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangesEditProjectNameCall) DoAndReturn(f func(context.Context, EditNameRequest) (*State, error)) *MockChangesEditProjectNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
