// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/issue/execution (interfaces: Changes,IssueReader)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package execution -typed -write_package_comment=false . Changes,IssueReader
//

package execution

import (
	context "context"
	reflect "reflect"

	issue "go.abhg.dev/cardamom/internal/issue"
	gomock "go.uber.org/mock/gomock"
)

// MockChanges is a mock of Changes interface.
type MockChanges struct {
	ctrl     *gomock.Controller
	recorder *MockChangesMockRecorder
	isgomock struct{}
}

// MockChangesMockRecorder is the mock recorder for MockChanges.
type MockChangesMockRecorder struct {
	mock *MockChanges
}

// NewMockChanges creates a new mock instance.
func NewMockChanges(ctrl *gomock.Controller) *MockChanges {
	mock := &MockChanges{ctrl: ctrl}
	mock.recorder = &MockChangesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChanges) EXPECT() *MockChangesMockRecorder {
	return m.recorder
}

// ApproveCheckpoint mocks base method.
func (m *MockChanges) ApproveCheckpoint(arg0 context.Context, arg1 ApproveCheckpoint) (CheckpointResolved, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveCheckpoint", arg0, arg1)
	ret0, _ := ret[0].(CheckpointResolved)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApproveCheckpoint indicates an expected call of ApproveCheckpoint.
func (mr *MockChangesMockRecorder) ApproveCheckpoint(arg0, arg1 any) *MockChangesApproveCheckpointCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveCheckpoint", reflect.TypeOf((*MockChanges)(nil).ApproveCheckpoint), arg0, arg1)
	return &MockChangesApproveCheckpointCall{Call: call}
}

// MockChangesApproveCheckpointCall wrap *gomock.Call
type MockChangesApproveCheckpointCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangesApproveCheckpointCall) Return(arg0 CheckpointResolved, arg1 error) *MockChangesApproveCheckpointCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangesApproveCheckpointCall) Do(f func(context.Context, ApproveCheckpoint) (CheckpointResolved, error)) *MockChangesApproveCheckpointCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangesApproveCheckpointCall) DoAndReturn(f func(context.Context, ApproveCheckpoint) (CheckpointResolved, error)) *MockChangesApproveCheckpointCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CancelIssues mocks base method.
func (m *MockChanges) CancelIssues(arg0 context.Context, arg1 CancelIssues) (IssuesCancelled, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelIssues", arg0, arg1)
	ret0, _ := ret[0].(IssuesCancelled)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelIssues indicates an expected call of CancelIssues.
func (mr *MockChangesMockRecorder) CancelIssues(arg0, arg1 any) *MockChangesCancelIssuesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelIssues", reflect.TypeOf((*MockChanges)(nil).CancelIssues), arg0, arg1)
	return &MockChangesCancelIssuesCall{Call: call}
}

// MockChangesCancelIssuesCall wrap *gomock.Call
type MockChangesCancelIssuesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangesCancelIssuesCall) Return(arg0 IssuesCancelled, arg1 error) *MockChangesCancelIssuesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangesCancelIssuesCall) Do(f func(context.Context, CancelIssues) (IssuesCancelled, error)) *MockChangesCancelIssuesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangesCancelIssuesCall) DoAndReturn(f func(context.Context, CancelIssues) (IssuesCancelled, error)) *MockChangesCancelIssuesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ClaimIssue mocks base method.
func (m *MockChanges) ClaimIssue(arg0 context.Context, arg1 ClaimIssue) (IssueClaimed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimIssue", arg0, arg1)
	ret0, _ := ret[0].(IssueClaimed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimIssue indicates an expected call of ClaimIssue.
func (mr *MockChangesMockRecorder) ClaimIssue(arg0, arg1 any) *MockChangesClaimIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimIssue", reflect.TypeOf((*MockChanges)(nil).ClaimIssue), arg0, arg1)
	return &MockChangesClaimIssueCall{Call: call}
}

// MockChangesClaimIssueCall wrap *gomock.Call
type MockChangesClaimIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangesClaimIssueCall) Return(arg0 IssueClaimed, arg1 error) *MockChangesClaimIssueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangesClaimIssueCall) Do(f func(context.Context, ClaimIssue) (IssueClaimed, error)) *MockChangesClaimIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangesClaimIssueCall) DoAndReturn(f func(context.Context, ClaimIssue) (IssueClaimed, error)) *MockChangesClaimIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ClaimNext mocks base method.
func (m *MockChanges) ClaimNext(arg0 context.Context, arg1 ClaimNext) (IssueClaimed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimNext", arg0, arg1)
	ret0, _ := ret[0].(IssueClaimed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimNext indicates an expected call of ClaimNext.
func (mr *MockChangesMockRecorder) ClaimNext(arg0, arg1 any) *MockChangesClaimNextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimNext", reflect.TypeOf((*MockChanges)(nil).ClaimNext), arg0, arg1)
	return &MockChangesClaimNextCall{Call: call}
}

// MockChangesClaimNextCall wrap *gomock.Call
type MockChangesClaimNextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangesClaimNextCall) Return(arg0 IssueClaimed, arg1 error) *MockChangesClaimNextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangesClaimNextCall) Do(f func(context.Context, ClaimNext) (IssueClaimed, error)) *MockChangesClaimNextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangesClaimNextCall) DoAndReturn(f func(context.Context, ClaimNext) (IssueClaimed, error)) *MockChangesClaimNextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CloseIssue mocks base method.
func (m *MockChanges) CloseIssue(arg0 context.Context, arg1 CloseIssue) (IssueClosed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseIssue", arg0, arg1)
	ret0, _ := ret[0].(IssueClosed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseIssue indicates an expected call of CloseIssue.
func (mr *MockChangesMockRecorder) CloseIssue(arg0, arg1 any) *MockChangesCloseIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseIssue", reflect.TypeOf((*MockChanges)(nil).CloseIssue), arg0, arg1)
	return &MockChangesCloseIssueCall{Call: call}
}

// MockChangesCloseIssueCall wrap *gomock.Call
type MockChangesCloseIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangesCloseIssueCall) Return(arg0 IssueClosed, arg1 error) *MockChangesCloseIssueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangesCloseIssueCall) Do(f func(context.Context, CloseIssue) (IssueClosed, error)) *MockChangesCloseIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangesCloseIssueCall) DoAndReturn(f func(context.Context, CloseIssue) (IssueClosed, error)) *MockChangesCloseIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// DenyCheckpoint mocks base method.
func (m *MockChanges) DenyCheckpoint(arg0 context.Context, arg1 DenyCheckpoint) (CheckpointResolved, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DenyCheckpoint", arg0, arg1)
	ret0, _ := ret[0].(CheckpointResolved)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DenyCheckpoint indicates an expected call of DenyCheckpoint.
func (mr *MockChangesMockRecorder) DenyCheckpoint(arg0, arg1 any) *MockChangesDenyCheckpointCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DenyCheckpoint", reflect.TypeOf((*MockChanges)(nil).DenyCheckpoint), arg0, arg1)
	return &MockChangesDenyCheckpointCall{Call: call}
}

// MockChangesDenyCheckpointCall wrap *gomock.Call
type MockChangesDenyCheckpointCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangesDenyCheckpointCall) Return(arg0 CheckpointResolved, arg1 error) *MockChangesDenyCheckpointCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangesDenyCheckpointCall) Do(f func(context.Context, DenyCheckpoint) (CheckpointResolved, error)) *MockChangesDenyCheckpointCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangesDenyCheckpointCall) DoAndReturn(f func(context.Context, DenyCheckpoint) (CheckpointResolved, error)) *MockChangesDenyCheckpointCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReleaseIssue mocks base method.
func (m *MockChanges) ReleaseIssue(arg0 context.Context, arg1 ReleaseIssue) (IssueReleased, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseIssue", arg0, arg1)
	ret0, _ := ret[0].(IssueReleased)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseIssue indicates an expected call of ReleaseIssue.
func (mr *MockChangesMockRecorder) ReleaseIssue(arg0, arg1 any) *MockChangesReleaseIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseIssue", reflect.TypeOf((*MockChanges)(nil).ReleaseIssue), arg0, arg1)
	return &MockChangesReleaseIssueCall{Call: call}
}

// MockChangesReleaseIssueCall wrap *gomock.Call
type MockChangesReleaseIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangesReleaseIssueCall) Return(arg0 IssueReleased, arg1 error) *MockChangesReleaseIssueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangesReleaseIssueCall) Do(f func(context.Context, ReleaseIssue) (IssueReleased, error)) *MockChangesReleaseIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangesReleaseIssueCall) DoAndReturn(f func(context.Context, ReleaseIssue) (IssueReleased, error)) *MockChangesReleaseIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReopenIssue mocks base method.
func (m *MockChanges) ReopenIssue(arg0 context.Context, arg1 ReopenIssue) (IssueReopened, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReopenIssue", arg0, arg1)
	ret0, _ := ret[0].(IssueReopened)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReopenIssue indicates an expected call of ReopenIssue.
func (mr *MockChangesMockRecorder) ReopenIssue(arg0, arg1 any) *MockChangesReopenIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReopenIssue", reflect.TypeOf((*MockChanges)(nil).ReopenIssue), arg0, arg1)
	return &MockChangesReopenIssueCall{Call: call}
}

// MockChangesReopenIssueCall wrap *gomock.Call
type MockChangesReopenIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangesReopenIssueCall) Return(arg0 IssueReopened, arg1 error) *MockChangesReopenIssueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangesReopenIssueCall) Do(f func(context.Context, ReopenIssue) (IssueReopened, error)) *MockChangesReopenIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangesReopenIssueCall) DoAndReturn(f func(context.Context, ReopenIssue) (IssueReopened, error)) *MockChangesReopenIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockIssueReader is a mock of IssueReader interface.
type MockIssueReader struct {
	ctrl     *gomock.Controller
	recorder *MockIssueReaderMockRecorder
	isgomock struct{}
}

// MockIssueReaderMockRecorder is the mock recorder for MockIssueReader.
type MockIssueReaderMockRecorder struct {
	mock *MockIssueReader
}

// NewMockIssueReader creates a new mock instance.
func NewMockIssueReader(ctrl *gomock.Controller) *MockIssueReader {
	mock := &MockIssueReader{ctrl: ctrl}
	mock.recorder = &MockIssueReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueReader) EXPECT() *MockIssueReaderMockRecorder {
	return m.recorder
}

// ListActionableCheckpoints mocks base method.
func (m *MockIssueReader) ListActionableCheckpoints(arg0 context.Context) ([]issue.CheckpointView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActionableCheckpoints", arg0)
	ret0, _ := ret[0].([]issue.CheckpointView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActionableCheckpoints indicates an expected call of ListActionableCheckpoints.
func (mr *MockIssueReaderMockRecorder) ListActionableCheckpoints(arg0 any) *MockIssueReaderListActionableCheckpointsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActionableCheckpoints", reflect.TypeOf((*MockIssueReader)(nil).ListActionableCheckpoints), arg0)
	return &MockIssueReaderListActionableCheckpointsCall{Call: call}
}

// MockIssueReaderListActionableCheckpointsCall wrap *gomock.Call
type MockIssueReaderListActionableCheckpointsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIssueReaderListActionableCheckpointsCall) Return(arg0 []issue.CheckpointView, arg1 error) *MockIssueReaderListActionableCheckpointsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIssueReaderListActionableCheckpointsCall) Do(f func(context.Context) ([]issue.CheckpointView, error)) *MockIssueReaderListActionableCheckpointsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIssueReaderListActionableCheckpointsCall) DoAndReturn(f func(context.Context) ([]issue.CheckpointView, error)) *MockIssueReaderListActionableCheckpointsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListBlockedIssues mocks base method.
func (m *MockIssueReader) ListBlockedIssues(arg0 context.Context, arg1 issue.ListBlockedRequest) ([]issue.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBlockedIssues", arg0, arg1)
	ret0, _ := ret[0].([]issue.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlockedIssues indicates an expected call of ListBlockedIssues.
func (mr *MockIssueReaderMockRecorder) ListBlockedIssues(arg0, arg1 any) *MockIssueReaderListBlockedIssuesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlockedIssues", reflect.TypeOf((*MockIssueReader)(nil).ListBlockedIssues), arg0, arg1)
	return &MockIssueReaderListBlockedIssuesCall{Call: call}
}

// MockIssueReaderListBlockedIssuesCall wrap *gomock.Call
type MockIssueReaderListBlockedIssuesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIssueReaderListBlockedIssuesCall) Return(arg0 []issue.Summary, arg1 error) *MockIssueReaderListBlockedIssuesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIssueReaderListBlockedIssuesCall) Do(f func(context.Context, issue.ListBlockedRequest) ([]issue.Summary, error)) *MockIssueReaderListBlockedIssuesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIssueReaderListBlockedIssuesCall) DoAndReturn(f func(context.Context, issue.ListBlockedRequest) ([]issue.Summary, error)) *MockIssueReaderListBlockedIssuesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListReadyIssues mocks base method.
func (m *MockIssueReader) ListReadyIssues(arg0 context.Context, arg1 issue.ListReadyRequest) ([]issue.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReadyIssues", arg0, arg1)
	ret0, _ := ret[0].([]issue.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReadyIssues indicates an expected call of ListReadyIssues.
func (mr *MockIssueReaderMockRecorder) ListReadyIssues(arg0, arg1 any) *MockIssueReaderListReadyIssuesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReadyIssues", reflect.TypeOf((*MockIssueReader)(nil).ListReadyIssues), arg0, arg1)
	return &MockIssueReaderListReadyIssuesCall{Call: call}
}

// MockIssueReaderListReadyIssuesCall wrap *gomock.Call
type MockIssueReaderListReadyIssuesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIssueReaderListReadyIssuesCall) Return(arg0 []issue.Summary, arg1 error) *MockIssueReaderListReadyIssuesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIssueReaderListReadyIssuesCall) Do(f func(context.Context, issue.ListReadyRequest) ([]issue.Summary, error)) *MockIssueReaderListReadyIssuesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIssueReaderListReadyIssuesCall) DoAndReturn(f func(context.Context, issue.ListReadyRequest) ([]issue.Summary, error)) *MockIssueReaderListReadyIssuesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReadIssue mocks base method.
func (m *MockIssueReader) ReadIssue(arg0 context.Context, arg1 issue.ReadRequest) (issue.View, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadIssue", arg0, arg1)
	ret0, _ := ret[0].(issue.View)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadIssue indicates an expected call of ReadIssue.
func (mr *MockIssueReaderMockRecorder) ReadIssue(arg0, arg1 any) *MockIssueReaderReadIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadIssue", reflect.TypeOf((*MockIssueReader)(nil).ReadIssue), arg0, arg1)
	return &MockIssueReaderReadIssueCall{Call: call}
}

// MockIssueReaderReadIssueCall wrap *gomock.Call
type MockIssueReaderReadIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIssueReaderReadIssueCall) Return(arg0 issue.View, arg1 error) *MockIssueReaderReadIssueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIssueReaderReadIssueCall) Do(f func(context.Context, issue.ReadRequest) (issue.View, error)) *MockIssueReaderReadIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIssueReaderReadIssueCall) DoAndReturn(f func(context.Context, issue.ReadRequest) (issue.View, error)) *MockIssueReaderReadIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
