// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/configuration (interfaces: Store,Repository)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package configuration -typed -write_package_comment=false . Store,Repository
//

package configuration

import (
	context "context"
	reflect "reflect"

	board "go.abhg.dev/cardamom/internal/board"
	project "go.abhg.dev/cardamom/internal/project"
	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// ReadStoreConfiguration mocks base method.
func (m *MockStore) ReadStoreConfiguration(arg0 context.Context) (Overrides, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadStoreConfiguration", arg0)
	ret0, _ := ret[0].(Overrides)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadStoreConfiguration indicates an expected call of ReadStoreConfiguration.
func (mr *MockStoreMockRecorder) ReadStoreConfiguration(arg0 any) *MockStoreReadStoreConfigurationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadStoreConfiguration", reflect.TypeOf((*MockStore)(nil).ReadStoreConfiguration), arg0)
	return &MockStoreReadStoreConfigurationCall{Call: call}
}

// MockStoreReadStoreConfigurationCall wrap *gomock.Call
type MockStoreReadStoreConfigurationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreReadStoreConfigurationCall) Return(arg0 Overrides, arg1 error) *MockStoreReadStoreConfigurationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreReadStoreConfigurationCall) Do(f func(context.Context) (Overrides, error)) *MockStoreReadStoreConfigurationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreReadStoreConfigurationCall) DoAndReturn(f func(context.Context) (Overrides, error)) *MockStoreReadStoreConfigurationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateStoreConfiguration mocks base method.
func (m *MockStore) UpdateStoreConfiguration(arg0 context.Context, arg1 Patch) (Overrides, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStoreConfiguration", arg0, arg1)
	ret0, _ := ret[0].(Overrides)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStoreConfiguration indicates an expected call of UpdateStoreConfiguration.
func (mr *MockStoreMockRecorder) UpdateStoreConfiguration(arg0, arg1 any) *MockStoreUpdateStoreConfigurationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStoreConfiguration", reflect.TypeOf((*MockStore)(nil).UpdateStoreConfiguration), arg0, arg1)
	return &MockStoreUpdateStoreConfigurationCall{Call: call}
}

// MockStoreUpdateStoreConfigurationCall wrap *gomock.Call
type MockStoreUpdateStoreConfigurationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreUpdateStoreConfigurationCall) Return(arg0 Overrides, arg1 error) *MockStoreUpdateStoreConfigurationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreUpdateStoreConfigurationCall) Do(f func(context.Context, Patch) (Overrides, error)) *MockStoreUpdateStoreConfigurationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreUpdateStoreConfigurationCall) DoAndReturn(f func(context.Context, Patch) (Overrides, error)) *MockStoreUpdateStoreConfigurationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ReadConfigurationLayers mocks base method.
func (m *MockRepository) ReadConfigurationLayers(arg0 context.Context, arg1 board.ID) (DatabaseLayers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadConfigurationLayers", arg0, arg1)
	ret0, _ := ret[0].(DatabaseLayers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadConfigurationLayers indicates an expected call of ReadConfigurationLayers.
func (mr *MockRepositoryMockRecorder) ReadConfigurationLayers(arg0, arg1 any) *MockRepositoryReadConfigurationLayersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadConfigurationLayers", reflect.TypeOf((*MockRepository)(nil).ReadConfigurationLayers), arg0, arg1)
	return &MockRepositoryReadConfigurationLayersCall{Call: call}
}

// MockRepositoryReadConfigurationLayersCall wrap *gomock.Call
type MockRepositoryReadConfigurationLayersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryReadConfigurationLayersCall) Return(arg0 DatabaseLayers, arg1 error) *MockRepositoryReadConfigurationLayersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryReadConfigurationLayersCall) Do(f func(context.Context, board.ID) (DatabaseLayers, error)) *MockRepositoryReadConfigurationLayersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryReadConfigurationLayersCall) DoAndReturn(f func(context.Context, board.ID) (DatabaseLayers, error)) *MockRepositoryReadConfigurationLayersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateBoardConfiguration mocks base method.
func (m *MockRepository) UpdateBoardConfiguration(arg0 context.Context, arg1 board.ID, arg2 Patch) (Overrides, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBoardConfiguration", arg0, arg1, arg2)
	ret0, _ := ret[0].(Overrides)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBoardConfiguration indicates an expected call of UpdateBoardConfiguration.
func (mr *MockRepositoryMockRecorder) UpdateBoardConfiguration(arg0, arg1, arg2 any) *MockRepositoryUpdateBoardConfigurationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBoardConfiguration", reflect.TypeOf((*MockRepository)(nil).UpdateBoardConfiguration), arg0, arg1, arg2)
	return &MockRepositoryUpdateBoardConfigurationCall{Call: call}
}

// MockRepositoryUpdateBoardConfigurationCall wrap *gomock.Call
type MockRepositoryUpdateBoardConfigurationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpdateBoardConfigurationCall) Return(arg0 Overrides, arg1 error) *MockRepositoryUpdateBoardConfigurationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpdateBoardConfigurationCall) Do(f func(context.Context, board.ID, Patch) (Overrides, error)) *MockRepositoryUpdateBoardConfigurationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpdateBoardConfigurationCall) DoAndReturn(f func(context.Context, board.ID, Patch) (Overrides, error)) *MockRepositoryUpdateBoardConfigurationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// UpdateProjectConfiguration mocks base method.
func (m *MockRepository) UpdateProjectConfiguration(arg0 context.Context, arg1 project.ID, arg2 Patch) (Overrides, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProjectConfiguration", arg0, arg1, arg2)
	ret0, _ := ret[0].(Overrides)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProjectConfiguration indicates an expected call of UpdateProjectConfiguration.
func (mr *MockRepositoryMockRecorder) UpdateProjectConfiguration(arg0, arg1, arg2 any) *MockRepositoryUpdateProjectConfigurationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProjectConfiguration", reflect.TypeOf((*MockRepository)(nil).UpdateProjectConfiguration), arg0, arg1, arg2)
	return &MockRepositoryUpdateProjectConfigurationCall{Call: call}
}

// MockRepositoryUpdateProjectConfigurationCall wrap *gomock.Call
type MockRepositoryUpdateProjectConfigurationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryUpdateProjectConfigurationCall) Return(arg0 Overrides, arg1 error) *MockRepositoryUpdateProjectConfigurationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryUpdateProjectConfigurationCall) Do(f func(context.Context, project.ID, Patch) (Overrides, error)) *MockRepositoryUpdateProjectConfigurationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryUpdateProjectConfigurationCall) DoAndReturn(f func(context.Context, project.ID, Patch) (Overrides, error)) *MockRepositoryUpdateProjectConfigurationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
