// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/web/executionconnect (interfaces: BoardExecutor,BoardExecutorFactory)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package executionconnect -typed -write_package_comment=false . BoardExecutor,BoardExecutorFactory
//

package executionconnect

import (
	context "context"
	reflect "reflect"

	board "go.abhg.dev/cardamom/internal/board"
	issue "go.abhg.dev/cardamom/internal/issue"
	execution "go.abhg.dev/cardamom/internal/issue/execution"
	gomock "go.uber.org/mock/gomock"
)

// MockBoardExecutor is a mock of BoardExecutor interface.
type MockBoardExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockBoardExecutorMockRecorder
	isgomock struct{}
}

// MockBoardExecutorMockRecorder is the mock recorder for MockBoardExecutor.
type MockBoardExecutorMockRecorder struct {
	mock *MockBoardExecutor
}

// NewMockBoardExecutor creates a new mock instance.
func NewMockBoardExecutor(ctrl *gomock.Controller) *MockBoardExecutor {
	mock := &MockBoardExecutor{ctrl: ctrl}
	mock.recorder = &MockBoardExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardExecutor) EXPECT() *MockBoardExecutorMockRecorder {
	return m.recorder
}

// CancelIssues mocks base method.
func (m *MockBoardExecutor) CancelIssues(arg0 context.Context, arg1 issue.Invocation, arg2 execution.CancelIssuesRequest) (execution.CancelIssuesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelIssues", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.CancelIssuesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelIssues indicates an expected call of CancelIssues.
func (mr *MockBoardExecutorMockRecorder) CancelIssues(arg0, arg1, arg2 any) *MockBoardExecutorCancelIssuesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelIssues", reflect.TypeOf((*MockBoardExecutor)(nil).CancelIssues), arg0, arg1, arg2)
	return &MockBoardExecutorCancelIssuesCall{Call: call}
}

// MockBoardExecutorCancelIssuesCall wrap *gomock.Call
type MockBoardExecutorCancelIssuesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardExecutorCancelIssuesCall) Return(arg0 execution.CancelIssuesResult, arg1 error) *MockBoardExecutorCancelIssuesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardExecutorCancelIssuesCall) Do(f func(context.Context, issue.Invocation, execution.CancelIssuesRequest) (execution.CancelIssuesResult, error)) *MockBoardExecutorCancelIssuesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardExecutorCancelIssuesCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.CancelIssuesRequest) (execution.CancelIssuesResult, error)) *MockBoardExecutorCancelIssuesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ClaimIssue mocks base method.
func (m *MockBoardExecutor) ClaimIssue(arg0 context.Context, arg1 issue.Invocation, arg2 execution.ClaimIssueRequest) (execution.ClaimIssueResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimIssue", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.ClaimIssueResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimIssue indicates an expected call of ClaimIssue.
func (mr *MockBoardExecutorMockRecorder) ClaimIssue(arg0, arg1, arg2 any) *MockBoardExecutorClaimIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimIssue", reflect.TypeOf((*MockBoardExecutor)(nil).ClaimIssue), arg0, arg1, arg2)
	return &MockBoardExecutorClaimIssueCall{Call: call}
}

// MockBoardExecutorClaimIssueCall wrap *gomock.Call
type MockBoardExecutorClaimIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardExecutorClaimIssueCall) Return(arg0 execution.ClaimIssueResult, arg1 error) *MockBoardExecutorClaimIssueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardExecutorClaimIssueCall) Do(f func(context.Context, issue.Invocation, execution.ClaimIssueRequest) (execution.ClaimIssueResult, error)) *MockBoardExecutorClaimIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardExecutorClaimIssueCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.ClaimIssueRequest) (execution.ClaimIssueResult, error)) *MockBoardExecutorClaimIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ClaimNext mocks base method.
func (m *MockBoardExecutor) ClaimNext(arg0 context.Context, arg1 issue.Invocation, arg2 execution.ClaimNextRequest) (execution.ClaimIssueResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClaimNext", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.ClaimIssueResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClaimNext indicates an expected call of ClaimNext.
func (mr *MockBoardExecutorMockRecorder) ClaimNext(arg0, arg1, arg2 any) *MockBoardExecutorClaimNextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClaimNext", reflect.TypeOf((*MockBoardExecutor)(nil).ClaimNext), arg0, arg1, arg2)
	return &MockBoardExecutorClaimNextCall{Call: call}
}

// MockBoardExecutorClaimNextCall wrap *gomock.Call
type MockBoardExecutorClaimNextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardExecutorClaimNextCall) Return(arg0 execution.ClaimIssueResult, arg1 error) *MockBoardExecutorClaimNextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardExecutorClaimNextCall) Do(f func(context.Context, issue.Invocation, execution.ClaimNextRequest) (execution.ClaimIssueResult, error)) *MockBoardExecutorClaimNextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardExecutorClaimNextCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.ClaimNextRequest) (execution.ClaimIssueResult, error)) *MockBoardExecutorClaimNextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CloseIssues mocks base method.
func (m *MockBoardExecutor) CloseIssues(arg0 context.Context, arg1 issue.Invocation, arg2 execution.CloseIssuesRequest) (execution.CloseIssuesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseIssues", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.CloseIssuesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseIssues indicates an expected call of CloseIssues.
func (mr *MockBoardExecutorMockRecorder) CloseIssues(arg0, arg1, arg2 any) *MockBoardExecutorCloseIssuesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseIssues", reflect.TypeOf((*MockBoardExecutor)(nil).CloseIssues), arg0, arg1, arg2)
	return &MockBoardExecutorCloseIssuesCall{Call: call}
}

// MockBoardExecutorCloseIssuesCall wrap *gomock.Call
type MockBoardExecutorCloseIssuesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardExecutorCloseIssuesCall) Return(arg0 execution.CloseIssuesResult, arg1 error) *MockBoardExecutorCloseIssuesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardExecutorCloseIssuesCall) Do(f func(context.Context, issue.Invocation, execution.CloseIssuesRequest) (execution.CloseIssuesResult, error)) *MockBoardExecutorCloseIssuesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardExecutorCloseIssuesCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.CloseIssuesRequest) (execution.CloseIssuesResult, error)) *MockBoardExecutorCloseIssuesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListBlockedIssues mocks base method.
func (m *MockBoardExecutor) ListBlockedIssues(arg0 context.Context, arg1 issue.ListBlockedRequest) ([]issue.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBlockedIssues", arg0, arg1)
	ret0, _ := ret[0].([]issue.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBlockedIssues indicates an expected call of ListBlockedIssues.
func (mr *MockBoardExecutorMockRecorder) ListBlockedIssues(arg0, arg1 any) *MockBoardExecutorListBlockedIssuesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBlockedIssues", reflect.TypeOf((*MockBoardExecutor)(nil).ListBlockedIssues), arg0, arg1)
	return &MockBoardExecutorListBlockedIssuesCall{Call: call}
}

// MockBoardExecutorListBlockedIssuesCall wrap *gomock.Call
type MockBoardExecutorListBlockedIssuesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardExecutorListBlockedIssuesCall) Return(arg0 []issue.Summary, arg1 error) *MockBoardExecutorListBlockedIssuesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardExecutorListBlockedIssuesCall) Do(f func(context.Context, issue.ListBlockedRequest) ([]issue.Summary, error)) *MockBoardExecutorListBlockedIssuesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardExecutorListBlockedIssuesCall) DoAndReturn(f func(context.Context, issue.ListBlockedRequest) ([]issue.Summary, error)) *MockBoardExecutorListBlockedIssuesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListReadyIssues mocks base method.
func (m *MockBoardExecutor) ListReadyIssues(arg0 context.Context, arg1 issue.ListReadyRequest) ([]issue.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReadyIssues", arg0, arg1)
	ret0, _ := ret[0].([]issue.Summary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReadyIssues indicates an expected call of ListReadyIssues.
func (mr *MockBoardExecutorMockRecorder) ListReadyIssues(arg0, arg1 any) *MockBoardExecutorListReadyIssuesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReadyIssues", reflect.TypeOf((*MockBoardExecutor)(nil).ListReadyIssues), arg0, arg1)
	return &MockBoardExecutorListReadyIssuesCall{Call: call}
}

// MockBoardExecutorListReadyIssuesCall wrap *gomock.Call
type MockBoardExecutorListReadyIssuesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardExecutorListReadyIssuesCall) Return(arg0 []issue.Summary, arg1 error) *MockBoardExecutorListReadyIssuesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardExecutorListReadyIssuesCall) Do(f func(context.Context, issue.ListReadyRequest) ([]issue.Summary, error)) *MockBoardExecutorListReadyIssuesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardExecutorListReadyIssuesCall) DoAndReturn(f func(context.Context, issue.ListReadyRequest) ([]issue.Summary, error)) *MockBoardExecutorListReadyIssuesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReleaseIssue mocks base method.
func (m *MockBoardExecutor) ReleaseIssue(arg0 context.Context, arg1 issue.Invocation, arg2 execution.ReleaseIssueRequest) (execution.ReleaseIssueResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseIssue", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.ReleaseIssueResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReleaseIssue indicates an expected call of ReleaseIssue.
func (mr *MockBoardExecutorMockRecorder) ReleaseIssue(arg0, arg1, arg2 any) *MockBoardExecutorReleaseIssueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseIssue", reflect.TypeOf((*MockBoardExecutor)(nil).ReleaseIssue), arg0, arg1, arg2)
	return &MockBoardExecutorReleaseIssueCall{Call: call}
}

// MockBoardExecutorReleaseIssueCall wrap *gomock.Call
type MockBoardExecutorReleaseIssueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardExecutorReleaseIssueCall) Return(arg0 execution.ReleaseIssueResult, arg1 error) *MockBoardExecutorReleaseIssueCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardExecutorReleaseIssueCall) Do(f func(context.Context, issue.Invocation, execution.ReleaseIssueRequest) (execution.ReleaseIssueResult, error)) *MockBoardExecutorReleaseIssueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardExecutorReleaseIssueCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.ReleaseIssueRequest) (execution.ReleaseIssueResult, error)) *MockBoardExecutorReleaseIssueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ReopenIssues mocks base method.
func (m *MockBoardExecutor) ReopenIssues(arg0 context.Context, arg1 issue.Invocation, arg2 execution.ReopenIssuesRequest) (execution.ReopenIssuesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReopenIssues", arg0, arg1, arg2)
	ret0, _ := ret[0].(execution.ReopenIssuesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReopenIssues indicates an expected call of ReopenIssues.
func (mr *MockBoardExecutorMockRecorder) ReopenIssues(arg0, arg1, arg2 any) *MockBoardExecutorReopenIssuesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReopenIssues", reflect.TypeOf((*MockBoardExecutor)(nil).ReopenIssues), arg0, arg1, arg2)
	return &MockBoardExecutorReopenIssuesCall{Call: call}
}

// MockBoardExecutorReopenIssuesCall wrap *gomock.Call
type MockBoardExecutorReopenIssuesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardExecutorReopenIssuesCall) Return(arg0 execution.ReopenIssuesResult, arg1 error) *MockBoardExecutorReopenIssuesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardExecutorReopenIssuesCall) Do(f func(context.Context, issue.Invocation, execution.ReopenIssuesRequest) (execution.ReopenIssuesResult, error)) *MockBoardExecutorReopenIssuesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardExecutorReopenIssuesCall) DoAndReturn(f func(context.Context, issue.Invocation, execution.ReopenIssuesRequest) (execution.ReopenIssuesResult, error)) *MockBoardExecutorReopenIssuesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockBoardExecutorFactory is a mock of BoardExecutorFactory interface.
type MockBoardExecutorFactory struct {
	ctrl     *gomock.Controller
	recorder *MockBoardExecutorFactoryMockRecorder
	isgomock struct{}
}

// MockBoardExecutorFactoryMockRecorder is the mock recorder for MockBoardExecutorFactory.
type MockBoardExecutorFactoryMockRecorder struct {
	mock *MockBoardExecutorFactory
}

// NewMockBoardExecutorFactory creates a new mock instance.
func NewMockBoardExecutorFactory(ctrl *gomock.Controller) *MockBoardExecutorFactory {
	mock := &MockBoardExecutorFactory{ctrl: ctrl}
	mock.recorder = &MockBoardExecutorFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardExecutorFactory) EXPECT() *MockBoardExecutorFactoryMockRecorder {
	return m.recorder
}

// Executor mocks base method.
func (m *MockBoardExecutorFactory) Executor(arg0 board.ID) (BoardExecutor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Executor", arg0)
	ret0, _ := ret[0].(BoardExecutor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Executor indicates an expected call of Executor.
func (mr *MockBoardExecutorFactoryMockRecorder) Executor(arg0 any) *MockBoardExecutorFactoryExecutorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Executor", reflect.TypeOf((*MockBoardExecutorFactory)(nil).Executor), arg0)
	return &MockBoardExecutorFactoryExecutorCall{Call: call}
}

// MockBoardExecutorFactoryExecutorCall wrap *gomock.Call
type MockBoardExecutorFactoryExecutorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardExecutorFactoryExecutorCall) Return(arg0 BoardExecutor, arg1 error) *MockBoardExecutorFactoryExecutorCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardExecutorFactoryExecutorCall) Do(f func(board.ID) (BoardExecutor, error)) *MockBoardExecutorFactoryExecutorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardExecutorFactoryExecutorCall) DoAndReturn(f func(board.ID) (BoardExecutor, error)) *MockBoardExecutorFactoryExecutorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
