// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/attachment (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination mock_repository_test.go -package attachmentconnect -typed -write_package_comment=false go.abhg.dev/cardamom/internal/attachment Repository
//

package attachmentconnect

import (
	context "context"
	reflect "reflect"

	attachment "go.abhg.dev/cardamom/internal/attachment"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AbortUpload mocks base method.
func (m *MockRepository) AbortUpload(arg0 context.Context, arg1 attachment.AbortUploadRequest) (attachment.Upload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortUpload", arg0, arg1)
	ret0, _ := ret[0].(attachment.Upload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AbortUpload indicates an expected call of AbortUpload.
func (mr *MockRepositoryMockRecorder) AbortUpload(arg0, arg1 any) *MockRepositoryAbortUploadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortUpload", reflect.TypeOf((*MockRepository)(nil).AbortUpload), arg0, arg1)
	return &MockRepositoryAbortUploadCall{Call: call}
}

// MockRepositoryAbortUploadCall wrap *gomock.Call
type MockRepositoryAbortUploadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryAbortUploadCall) Return(arg0 attachment.Upload, arg1 error) *MockRepositoryAbortUploadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryAbortUploadCall) Do(f func(context.Context, attachment.AbortUploadRequest) (attachment.Upload, error)) *MockRepositoryAbortUploadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryAbortUploadCall) DoAndReturn(f func(context.Context, attachment.AbortUploadRequest) (attachment.Upload, error)) *MockRepositoryAbortUploadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BeginUpload mocks base method.
func (m *MockRepository) BeginUpload(arg0 context.Context, arg1 attachment.BeginUploadAdmission) (attachment.Upload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginUpload", arg0, arg1)
	ret0, _ := ret[0].(attachment.Upload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginUpload indicates an expected call of BeginUpload.
func (mr *MockRepositoryMockRecorder) BeginUpload(arg0, arg1 any) *MockRepositoryBeginUploadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginUpload", reflect.TypeOf((*MockRepository)(nil).BeginUpload), arg0, arg1)
	return &MockRepositoryBeginUploadCall{Call: call}
}

// MockRepositoryBeginUploadCall wrap *gomock.Call
type MockRepositoryBeginUploadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryBeginUploadCall) Return(arg0 attachment.Upload, arg1 error) *MockRepositoryBeginUploadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryBeginUploadCall) Do(f func(context.Context, attachment.BeginUploadAdmission) (attachment.Upload, error)) *MockRepositoryBeginUploadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryBeginUploadCall) DoAndReturn(f func(context.Context, attachment.BeginUploadAdmission) (attachment.Upload, error)) *MockRepositoryBeginUploadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CollectAttachments mocks base method.
func (m *MockRepository) CollectAttachments(arg0 context.Context, arg1 attachment.CollectRequest) (attachment.CollectionResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectAttachments", arg0, arg1)
	ret0, _ := ret[0].(attachment.CollectionResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectAttachments indicates an expected call of CollectAttachments.
func (mr *MockRepositoryMockRecorder) CollectAttachments(arg0, arg1 any) *MockRepositoryCollectAttachmentsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectAttachments", reflect.TypeOf((*MockRepository)(nil).CollectAttachments), arg0, arg1)
	return &MockRepositoryCollectAttachmentsCall{Call: call}
}

// MockRepositoryCollectAttachmentsCall wrap *gomock.Call
type MockRepositoryCollectAttachmentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCollectAttachmentsCall) Return(arg0 attachment.CollectionResult, arg1 error) *MockRepositoryCollectAttachmentsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCollectAttachmentsCall) Do(f func(context.Context, attachment.CollectRequest) (attachment.CollectionResult, error)) *MockRepositoryCollectAttachmentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCollectAttachmentsCall) DoAndReturn(f func(context.Context, attachment.CollectRequest) (attachment.CollectionResult, error)) *MockRepositoryCollectAttachmentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CommitUpload mocks base method.
func (m *MockRepository) CommitUpload(arg0 context.Context, arg1 attachment.CommitUploadRequest) (attachment.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitUpload", arg0, arg1)
	ret0, _ := ret[0].(attachment.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitUpload indicates an expected call of CommitUpload.
func (mr *MockRepositoryMockRecorder) CommitUpload(arg0, arg1 any) *MockRepositoryCommitUploadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitUpload", reflect.TypeOf((*MockRepository)(nil).CommitUpload), arg0, arg1)
	return &MockRepositoryCommitUploadCall{Call: call}
}

// MockRepositoryCommitUploadCall wrap *gomock.Call
type MockRepositoryCommitUploadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryCommitUploadCall) Return(arg0 attachment.Attachment, arg1 error) *MockRepositoryCommitUploadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryCommitUploadCall) Do(f func(context.Context, attachment.CommitUploadRequest) (attachment.Attachment, error)) *MockRepositoryCommitUploadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryCommitUploadCall) DoAndReturn(f func(context.Context, attachment.CommitUploadRequest) (attachment.Attachment, error)) *MockRepositoryCommitUploadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetAttachment mocks base method.
func (m *MockRepository) GetAttachment(arg0 context.Context, arg1 attachment.GetRequest) (attachment.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachment", arg0, arg1)
	ret0, _ := ret[0].(attachment.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachment indicates an expected call of GetAttachment.
func (mr *MockRepositoryMockRecorder) GetAttachment(arg0, arg1 any) *MockRepositoryGetAttachmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachment", reflect.TypeOf((*MockRepository)(nil).GetAttachment), arg0, arg1)
	return &MockRepositoryGetAttachmentCall{Call: call}
}

// MockRepositoryGetAttachmentCall wrap *gomock.Call
type MockRepositoryGetAttachmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetAttachmentCall) Return(arg0 attachment.Attachment, arg1 error) *MockRepositoryGetAttachmentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetAttachmentCall) Do(f func(context.Context, attachment.GetRequest) (attachment.Attachment, error)) *MockRepositoryGetAttachmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetAttachmentCall) DoAndReturn(f func(context.Context, attachment.GetRequest) (attachment.Attachment, error)) *MockRepositoryGetAttachmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetUpload mocks base method.
func (m *MockRepository) GetUpload(arg0 context.Context, arg1 attachment.GetUploadRequest) (attachment.Upload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpload", arg0, arg1)
	ret0, _ := ret[0].(attachment.Upload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUpload indicates an expected call of GetUpload.
func (mr *MockRepositoryMockRecorder) GetUpload(arg0, arg1 any) *MockRepositoryGetUploadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpload", reflect.TypeOf((*MockRepository)(nil).GetUpload), arg0, arg1)
	return &MockRepositoryGetUploadCall{Call: call}
}

// MockRepositoryGetUploadCall wrap *gomock.Call
type MockRepositoryGetUploadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryGetUploadCall) Return(arg0 attachment.Upload, arg1 error) *MockRepositoryGetUploadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryGetUploadCall) Do(f func(context.Context, attachment.GetUploadRequest) (attachment.Upload, error)) *MockRepositoryGetUploadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryGetUploadCall) DoAndReturn(f func(context.Context, attachment.GetUploadRequest) (attachment.Upload, error)) *MockRepositoryGetUploadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListAttachments mocks base method.
func (m *MockRepository) ListAttachments(arg0 context.Context, arg1 attachment.ListRequest) (attachment.Page, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttachments", arg0, arg1)
	ret0, _ := ret[0].(attachment.Page)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttachments indicates an expected call of ListAttachments.
func (mr *MockRepositoryMockRecorder) ListAttachments(arg0, arg1 any) *MockRepositoryListAttachmentsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttachments", reflect.TypeOf((*MockRepository)(nil).ListAttachments), arg0, arg1)
	return &MockRepositoryListAttachmentsCall{Call: call}
}

// MockRepositoryListAttachmentsCall wrap *gomock.Call
type MockRepositoryListAttachmentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryListAttachmentsCall) Return(arg0 attachment.Page, arg1 error) *MockRepositoryListAttachmentsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryListAttachmentsCall) Do(f func(context.Context, attachment.ListRequest) (attachment.Page, error)) *MockRepositoryListAttachmentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryListAttachmentsCall) DoAndReturn(f func(context.Context, attachment.ListRequest) (attachment.Page, error)) *MockRepositoryListAttachmentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// OpenAttachmentContent mocks base method.
func (m *MockRepository) OpenAttachmentContent(arg0 context.Context, arg1 attachment.OpenContentRequest) (attachment.OpenedContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenAttachmentContent", arg0, arg1)
	ret0, _ := ret[0].(attachment.OpenedContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenAttachmentContent indicates an expected call of OpenAttachmentContent.
func (mr *MockRepositoryMockRecorder) OpenAttachmentContent(arg0, arg1 any) *MockRepositoryOpenAttachmentContentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenAttachmentContent", reflect.TypeOf((*MockRepository)(nil).OpenAttachmentContent), arg0, arg1)
	return &MockRepositoryOpenAttachmentContentCall{Call: call}
}

// MockRepositoryOpenAttachmentContentCall wrap *gomock.Call
type MockRepositoryOpenAttachmentContentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryOpenAttachmentContentCall) Return(arg0 attachment.OpenedContent, arg1 error) *MockRepositoryOpenAttachmentContentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryOpenAttachmentContentCall) Do(f func(context.Context, attachment.OpenContentRequest) (attachment.OpenedContent, error)) *MockRepositoryOpenAttachmentContentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryOpenAttachmentContentCall) DoAndReturn(f func(context.Context, attachment.OpenContentRequest) (attachment.OpenedContent, error)) *MockRepositoryOpenAttachmentContentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveAttachment mocks base method.
func (m *MockRepository) RemoveAttachment(arg0 context.Context, arg1 attachment.RemoveRequest) (attachment.Attachment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAttachment", arg0, arg1)
	ret0, _ := ret[0].(attachment.Attachment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveAttachment indicates an expected call of RemoveAttachment.
func (mr *MockRepositoryMockRecorder) RemoveAttachment(arg0, arg1 any) *MockRepositoryRemoveAttachmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAttachment", reflect.TypeOf((*MockRepository)(nil).RemoveAttachment), arg0, arg1)
	return &MockRepositoryRemoveAttachmentCall{Call: call}
}

// MockRepositoryRemoveAttachmentCall wrap *gomock.Call
type MockRepositoryRemoveAttachmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryRemoveAttachmentCall) Return(arg0 attachment.Attachment, arg1 error) *MockRepositoryRemoveAttachmentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryRemoveAttachmentCall) Do(f func(context.Context, attachment.RemoveRequest) (attachment.Attachment, error)) *MockRepositoryRemoveAttachmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryRemoveAttachmentCall) DoAndReturn(f func(context.Context, attachment.RemoveRequest) (attachment.Attachment, error)) *MockRepositoryRemoveAttachmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResolveAttachments mocks base method.
func (m *MockRepository) ResolveAttachments(arg0 context.Context, arg1 attachment.ResolveRequest) ([]attachment.Resolution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveAttachments", arg0, arg1)
	ret0, _ := ret[0].([]attachment.Resolution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveAttachments indicates an expected call of ResolveAttachments.
func (mr *MockRepositoryMockRecorder) ResolveAttachments(arg0, arg1 any) *MockRepositoryResolveAttachmentsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveAttachments", reflect.TypeOf((*MockRepository)(nil).ResolveAttachments), arg0, arg1)
	return &MockRepositoryResolveAttachmentsCall{Call: call}
}

// MockRepositoryResolveAttachmentsCall wrap *gomock.Call
type MockRepositoryResolveAttachmentsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryResolveAttachmentsCall) Return(arg0 []attachment.Resolution, arg1 error) *MockRepositoryResolveAttachmentsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryResolveAttachmentsCall) Do(f func(context.Context, attachment.ResolveRequest) ([]attachment.Resolution, error)) *MockRepositoryResolveAttachmentsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryResolveAttachmentsCall) DoAndReturn(f func(context.Context, attachment.ResolveRequest) ([]attachment.Resolution, error)) *MockRepositoryResolveAttachmentsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// VerifyAttachment mocks base method.
func (m *MockRepository) VerifyAttachment(arg0 context.Context, arg1 attachment.VerifyRequest) (attachment.Verification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAttachment", arg0, arg1)
	ret0, _ := ret[0].(attachment.Verification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAttachment indicates an expected call of VerifyAttachment.
func (mr *MockRepositoryMockRecorder) VerifyAttachment(arg0, arg1 any) *MockRepositoryVerifyAttachmentCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAttachment", reflect.TypeOf((*MockRepository)(nil).VerifyAttachment), arg0, arg1)
	return &MockRepositoryVerifyAttachmentCall{Call: call}
}

// MockRepositoryVerifyAttachmentCall wrap *gomock.Call
type MockRepositoryVerifyAttachmentCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryVerifyAttachmentCall) Return(arg0 attachment.Verification, arg1 error) *MockRepositoryVerifyAttachmentCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryVerifyAttachmentCall) Do(f func(context.Context, attachment.VerifyRequest) (attachment.Verification, error)) *MockRepositoryVerifyAttachmentCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryVerifyAttachmentCall) DoAndReturn(f func(context.Context, attachment.VerifyRequest) (attachment.Verification, error)) *MockRepositoryVerifyAttachmentCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// WriteChunk mocks base method.
func (m *MockRepository) WriteChunk(arg0 context.Context, arg1 attachment.WriteChunkRequest) (attachment.Upload, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteChunk", arg0, arg1)
	ret0, _ := ret[0].(attachment.Upload)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteChunk indicates an expected call of WriteChunk.
func (mr *MockRepositoryMockRecorder) WriteChunk(arg0, arg1 any) *MockRepositoryWriteChunkCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteChunk", reflect.TypeOf((*MockRepository)(nil).WriteChunk), arg0, arg1)
	return &MockRepositoryWriteChunkCall{Call: call}
}

// MockRepositoryWriteChunkCall wrap *gomock.Call
type MockRepositoryWriteChunkCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRepositoryWriteChunkCall) Return(arg0 attachment.Upload, arg1 error) *MockRepositoryWriteChunkCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRepositoryWriteChunkCall) Do(f func(context.Context, attachment.WriteChunkRequest) (attachment.Upload, error)) *MockRepositoryWriteChunkCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRepositoryWriteChunkCall) DoAndReturn(f func(context.Context, attachment.WriteChunkRequest) (attachment.Upload, error)) *MockRepositoryWriteChunkCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
