// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/backup (interfaces: StoreConfiguration)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package backup -typed -write_package_comment=false . StoreConfiguration
//

package backup

import (
	context "context"
	reflect "reflect"

	configuration "go.abhg.dev/cardamom/internal/configuration"
	gomock "go.uber.org/mock/gomock"
)

// MockStoreConfiguration is a mock of StoreConfiguration interface.
type MockStoreConfiguration struct {
	ctrl     *gomock.Controller
	recorder *MockStoreConfigurationMockRecorder
	isgomock struct{}
}

// MockStoreConfigurationMockRecorder is the mock recorder for MockStoreConfiguration.
type MockStoreConfigurationMockRecorder struct {
	mock *MockStoreConfiguration
}

// NewMockStoreConfiguration creates a new mock instance.
func NewMockStoreConfiguration(ctrl *gomock.Controller) *MockStoreConfiguration {
	mock := &MockStoreConfiguration{ctrl: ctrl}
	mock.recorder = &MockStoreConfigurationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoreConfiguration) EXPECT() *MockStoreConfigurationMockRecorder {
	return m.recorder
}

// ReadStoreConfiguration mocks base method.
func (m *MockStoreConfiguration) ReadStoreConfiguration(arg0 context.Context) (configuration.Overrides, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadStoreConfiguration", arg0)
	ret0, _ := ret[0].(configuration.Overrides)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadStoreConfiguration indicates an expected call of ReadStoreConfiguration.
func (mr *MockStoreConfigurationMockRecorder) ReadStoreConfiguration(arg0 any) *MockStoreConfigurationReadStoreConfigurationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadStoreConfiguration", reflect.TypeOf((*MockStoreConfiguration)(nil).ReadStoreConfiguration), arg0)
	return &MockStoreConfigurationReadStoreConfigurationCall{Call: call}
}

// MockStoreConfigurationReadStoreConfigurationCall wrap *gomock.Call
type MockStoreConfigurationReadStoreConfigurationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStoreConfigurationReadStoreConfigurationCall) Return(arg0 configuration.Overrides, arg1 error) *MockStoreConfigurationReadStoreConfigurationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStoreConfigurationReadStoreConfigurationCall) Do(f func(context.Context) (configuration.Overrides, error)) *MockStoreConfigurationReadStoreConfigurationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStoreConfigurationReadStoreConfigurationCall) DoAndReturn(f func(context.Context) (configuration.Overrides, error)) *MockStoreConfigurationReadStoreConfigurationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
