// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/web/mailconnect (interfaces: Operations)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package mailconnect -typed -write_package_comment=false . Operations
//

package mailconnect

import (
	context "context"
	reflect "reflect"

	mail "go.abhg.dev/cardamom/internal/mail"
	gomock "go.uber.org/mock/gomock"
)

// MockOperations is a mock of Operations interface.
type MockOperations struct {
	ctrl     *gomock.Controller
	recorder *MockOperationsMockRecorder
	isgomock struct{}
}

// MockOperationsMockRecorder is the mock recorder for MockOperations.
type MockOperationsMockRecorder struct {
	mock *MockOperations
}

// NewMockOperations creates a new mock instance.
func NewMockOperations(ctrl *gomock.Controller) *MockOperations {
	mock := &MockOperations{ctrl: ctrl}
	mock.recorder = &MockOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperations) EXPECT() *MockOperationsMockRecorder {
	return m.recorder
}

// Clear mocks base method.
func (m *MockOperations) Clear(arg0 context.Context, arg1 mail.MailboxRequest) (mail.ClearResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clear", arg0, arg1)
	ret0, _ := ret[0].(mail.ClearResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clear indicates an expected call of Clear.
func (mr *MockOperationsMockRecorder) Clear(arg0, arg1 any) *MockOperationsClearCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockOperations)(nil).Clear), arg0, arg1)
	return &MockOperationsClearCall{Call: call}
}

// MockOperationsClearCall wrap *gomock.Call
type MockOperationsClearCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationsClearCall) Return(arg0 mail.ClearResult, arg1 error) *MockOperationsClearCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationsClearCall) Do(f func(context.Context, mail.MailboxRequest) (mail.ClearResult, error)) *MockOperationsClearCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationsClearCall) DoAndReturn(f func(context.Context, mail.MailboxRequest) (mail.ClearResult, error)) *MockOperationsClearCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListSubscriptions mocks base method.
func (m *MockOperations) ListSubscriptions(arg0 context.Context) ([]mail.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubscriptions", arg0)
	ret0, _ := ret[0].([]mail.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubscriptions indicates an expected call of ListSubscriptions.
func (mr *MockOperationsMockRecorder) ListSubscriptions(arg0 any) *MockOperationsListSubscriptionsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubscriptions", reflect.TypeOf((*MockOperations)(nil).ListSubscriptions), arg0)
	return &MockOperationsListSubscriptionsCall{Call: call}
}

// MockOperationsListSubscriptionsCall wrap *gomock.Call
type MockOperationsListSubscriptionsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationsListSubscriptionsCall) Return(arg0 []mail.Subscription, arg1 error) *MockOperationsListSubscriptionsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationsListSubscriptionsCall) Do(f func(context.Context) ([]mail.Subscription, error)) *MockOperationsListSubscriptionsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationsListSubscriptionsCall) DoAndReturn(f func(context.Context) ([]mail.Subscription, error)) *MockOperationsListSubscriptionsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Peek mocks base method.
func (m *MockOperations) Peek(arg0 context.Context, arg1 mail.MailboxRequest) ([]mail.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Peek", arg0, arg1)
	ret0, _ := ret[0].([]mail.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Peek indicates an expected call of Peek.
func (mr *MockOperationsMockRecorder) Peek(arg0, arg1 any) *MockOperationsPeekCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Peek", reflect.TypeOf((*MockOperations)(nil).Peek), arg0, arg1)
	return &MockOperationsPeekCall{Call: call}
}

// MockOperationsPeekCall wrap *gomock.Call
type MockOperationsPeekCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationsPeekCall) Return(arg0 []mail.Message, arg1 error) *MockOperationsPeekCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationsPeekCall) Do(f func(context.Context, mail.MailboxRequest) ([]mail.Message, error)) *MockOperationsPeekCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationsPeekCall) DoAndReturn(f func(context.Context, mail.MailboxRequest) ([]mail.Message, error)) *MockOperationsPeekCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Publish mocks base method.
func (m *MockOperations) Publish(arg0 context.Context, arg1 mail.PublishRequest) ([]mail.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1)
	ret0, _ := ret[0].([]mail.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockOperationsMockRecorder) Publish(arg0, arg1 any) *MockOperationsPublishCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockOperations)(nil).Publish), arg0, arg1)
	return &MockOperationsPublishCall{Call: call}
}

// MockOperationsPublishCall wrap *gomock.Call
type MockOperationsPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationsPublishCall) Return(arg0 []mail.Message, arg1 error) *MockOperationsPublishCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationsPublishCall) Do(f func(context.Context, mail.PublishRequest) ([]mail.Message, error)) *MockOperationsPublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationsPublishCall) DoAndReturn(f func(context.Context, mail.PublishRequest) ([]mail.Message, error)) *MockOperationsPublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Receive mocks base method.
func (m *MockOperations) Receive(arg0 context.Context, arg1 mail.MailboxRequest) ([]mail.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Receive", arg0, arg1)
	ret0, _ := ret[0].([]mail.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Receive indicates an expected call of Receive.
func (mr *MockOperationsMockRecorder) Receive(arg0, arg1 any) *MockOperationsReceiveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Receive", reflect.TypeOf((*MockOperations)(nil).Receive), arg0, arg1)
	return &MockOperationsReceiveCall{Call: call}
}

// MockOperationsReceiveCall wrap *gomock.Call
type MockOperationsReceiveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationsReceiveCall) Return(arg0 []mail.Message, arg1 error) *MockOperationsReceiveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationsReceiveCall) Do(f func(context.Context, mail.MailboxRequest) ([]mail.Message, error)) *MockOperationsReceiveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationsReceiveCall) DoAndReturn(f func(context.Context, mail.MailboxRequest) ([]mail.Message, error)) *MockOperationsReceiveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveSubscription mocks base method.
func (m *MockOperations) RemoveSubscription(arg0 context.Context, arg1 mail.SubscriptionRemovalRequest) (mail.SubscriptionRemoval, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSubscription", arg0, arg1)
	ret0, _ := ret[0].(mail.SubscriptionRemoval)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveSubscription indicates an expected call of RemoveSubscription.
func (mr *MockOperationsMockRecorder) RemoveSubscription(arg0, arg1 any) *MockOperationsRemoveSubscriptionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSubscription", reflect.TypeOf((*MockOperations)(nil).RemoveSubscription), arg0, arg1)
	return &MockOperationsRemoveSubscriptionCall{Call: call}
}

// MockOperationsRemoveSubscriptionCall wrap *gomock.Call
type MockOperationsRemoveSubscriptionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationsRemoveSubscriptionCall) Return(arg0 mail.SubscriptionRemoval, arg1 error) *MockOperationsRemoveSubscriptionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationsRemoveSubscriptionCall) Do(f func(context.Context, mail.SubscriptionRemovalRequest) (mail.SubscriptionRemoval, error)) *MockOperationsRemoveSubscriptionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationsRemoveSubscriptionCall) DoAndReturn(f func(context.Context, mail.SubscriptionRemovalRequest) (mail.SubscriptionRemoval, error)) *MockOperationsRemoveSubscriptionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Send mocks base method.
func (m *MockOperations) Send(arg0 context.Context, arg1 mail.SendRequest) (mail.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0, arg1)
	ret0, _ := ret[0].(mail.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockOperationsMockRecorder) Send(arg0, arg1 any) *MockOperationsSendCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockOperations)(nil).Send), arg0, arg1)
	return &MockOperationsSendCall{Call: call}
}

// MockOperationsSendCall wrap *gomock.Call
type MockOperationsSendCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationsSendCall) Return(arg0 mail.Message, arg1 error) *MockOperationsSendCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationsSendCall) Do(f func(context.Context, mail.SendRequest) (mail.Message, error)) *MockOperationsSendCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationsSendCall) DoAndReturn(f func(context.Context, mail.SendRequest) (mail.Message, error)) *MockOperationsSendCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Subscribe mocks base method.
func (m *MockOperations) Subscribe(arg0 context.Context, arg1 mail.SubscriptionRequest) (mail.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", arg0, arg1)
	ret0, _ := ret[0].(mail.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockOperationsMockRecorder) Subscribe(arg0, arg1 any) *MockOperationsSubscribeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockOperations)(nil).Subscribe), arg0, arg1)
	return &MockOperationsSubscribeCall{Call: call}
}

// MockOperationsSubscribeCall wrap *gomock.Call
type MockOperationsSubscribeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationsSubscribeCall) Return(arg0 mail.Subscription, arg1 error) *MockOperationsSubscribeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationsSubscribeCall) Do(f func(context.Context, mail.SubscriptionRequest) (mail.Subscription, error)) *MockOperationsSubscribeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationsSubscribeCall) DoAndReturn(f func(context.Context, mail.SubscriptionRequest) (mail.Subscription, error)) *MockOperationsSubscribeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
