// Code generated by the migration authoring workflow. DO NOT EDIT.

package store

import "github.com/pressly/goose/v3"

// goMigrations is the complete data-only migration registry used during
// package initialization. Schema changes remain in SQL so the migration
// directory stays authoritative for sqlc.
var goMigrations = []*goose.Migration{}
