// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/repository/store (interfaces: readTransaction,changeTransaction)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package store -typed -write_package_comment=false -mock_names readTransaction=MockReadTransaction,changeTransaction=MockChangeTransaction . readTransaction,changeTransaction
//

package store

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockReadTransaction is a mock of readTransaction interface.
type MockReadTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockReadTransactionMockRecorder
	isgomock struct{}
}

// MockReadTransactionMockRecorder is the mock recorder for MockReadTransaction.
type MockReadTransactionMockRecorder struct {
	mock *MockReadTransaction
}

// NewMockReadTransaction creates a new mock instance.
func NewMockReadTransaction(ctrl *gomock.Controller) *MockReadTransaction {
	mock := &MockReadTransaction{ctrl: ctrl}
	mock.recorder = &MockReadTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadTransaction) EXPECT() *MockReadTransactionMockRecorder {
	return m.recorder
}

// ExecContext mocks base method.
func (m *MockReadTransaction) ExecContext(arg0 context.Context, arg1 string, arg2 ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecContext", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecContext indicates an expected call of ExecContext.
func (mr *MockReadTransactionMockRecorder) ExecContext(arg0, arg1 any, arg2 ...any) *MockReadTransactionExecContextCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecContext", reflect.TypeOf((*MockReadTransaction)(nil).ExecContext), varargs...)
	return &MockReadTransactionExecContextCall{Call: call}
}

// MockReadTransactionExecContextCall wrap *gomock.Call
type MockReadTransactionExecContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReadTransactionExecContextCall) Return(arg0 sql.Result, arg1 error) *MockReadTransactionExecContextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReadTransactionExecContextCall) Do(f func(context.Context, string, ...any) (sql.Result, error)) *MockReadTransactionExecContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReadTransactionExecContextCall) DoAndReturn(f func(context.Context, string, ...any) (sql.Result, error)) *MockReadTransactionExecContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PrepareContext mocks base method.
func (m *MockReadTransaction) PrepareContext(arg0 context.Context, arg1 string) (*sql.Stmt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareContext", arg0, arg1)
	ret0, _ := ret[0].(*sql.Stmt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareContext indicates an expected call of PrepareContext.
func (mr *MockReadTransactionMockRecorder) PrepareContext(arg0, arg1 any) *MockReadTransactionPrepareContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareContext", reflect.TypeOf((*MockReadTransaction)(nil).PrepareContext), arg0, arg1)
	return &MockReadTransactionPrepareContextCall{Call: call}
}

// MockReadTransactionPrepareContextCall wrap *gomock.Call
type MockReadTransactionPrepareContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReadTransactionPrepareContextCall) Return(arg0 *sql.Stmt, arg1 error) *MockReadTransactionPrepareContextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReadTransactionPrepareContextCall) Do(f func(context.Context, string) (*sql.Stmt, error)) *MockReadTransactionPrepareContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReadTransactionPrepareContextCall) DoAndReturn(f func(context.Context, string) (*sql.Stmt, error)) *MockReadTransactionPrepareContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// QueryContext mocks base method.
func (m *MockReadTransaction) QueryContext(arg0 context.Context, arg1 string, arg2 ...any) (*sql.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryContext", varargs...)
	ret0, _ := ret[0].(*sql.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryContext indicates an expected call of QueryContext.
func (mr *MockReadTransactionMockRecorder) QueryContext(arg0, arg1 any, arg2 ...any) *MockReadTransactionQueryContextCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryContext", reflect.TypeOf((*MockReadTransaction)(nil).QueryContext), varargs...)
	return &MockReadTransactionQueryContextCall{Call: call}
}

// MockReadTransactionQueryContextCall wrap *gomock.Call
type MockReadTransactionQueryContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReadTransactionQueryContextCall) Return(arg0 *sql.Rows, arg1 error) *MockReadTransactionQueryContextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReadTransactionQueryContextCall) Do(f func(context.Context, string, ...any) (*sql.Rows, error)) *MockReadTransactionQueryContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReadTransactionQueryContextCall) DoAndReturn(f func(context.Context, string, ...any) (*sql.Rows, error)) *MockReadTransactionQueryContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// QueryRowContext mocks base method.
func (m *MockReadTransaction) QueryRowContext(arg0 context.Context, arg1 string, arg2 ...any) *sql.Row {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRowContext", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// QueryRowContext indicates an expected call of QueryRowContext.
func (mr *MockReadTransactionMockRecorder) QueryRowContext(arg0, arg1 any, arg2 ...any) *MockReadTransactionQueryRowContextCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRowContext", reflect.TypeOf((*MockReadTransaction)(nil).QueryRowContext), varargs...)
	return &MockReadTransactionQueryRowContextCall{Call: call}
}

// MockReadTransactionQueryRowContextCall wrap *gomock.Call
type MockReadTransactionQueryRowContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReadTransactionQueryRowContextCall) Return(arg0 *sql.Row) *MockReadTransactionQueryRowContextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReadTransactionQueryRowContextCall) Do(f func(context.Context, string, ...any) *sql.Row) *MockReadTransactionQueryRowContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReadTransactionQueryRowContextCall) DoAndReturn(f func(context.Context, string, ...any) *sql.Row) *MockReadTransactionQueryRowContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Rollback mocks base method.
func (m *MockReadTransaction) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockReadTransactionMockRecorder) Rollback() *MockReadTransactionRollbackCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockReadTransaction)(nil).Rollback))
	return &MockReadTransactionRollbackCall{Call: call}
}

// MockReadTransactionRollbackCall wrap *gomock.Call
type MockReadTransactionRollbackCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReadTransactionRollbackCall) Return(arg0 error) *MockReadTransactionRollbackCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReadTransactionRollbackCall) Do(f func() error) *MockReadTransactionRollbackCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReadTransactionRollbackCall) DoAndReturn(f func() error) *MockReadTransactionRollbackCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockChangeTransaction is a mock of changeTransaction interface.
type MockChangeTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockChangeTransactionMockRecorder
	isgomock struct{}
}

// MockChangeTransactionMockRecorder is the mock recorder for MockChangeTransaction.
type MockChangeTransactionMockRecorder struct {
	mock *MockChangeTransaction
}

// NewMockChangeTransaction creates a new mock instance.
func NewMockChangeTransaction(ctrl *gomock.Controller) *MockChangeTransaction {
	mock := &MockChangeTransaction{ctrl: ctrl}
	mock.recorder = &MockChangeTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChangeTransaction) EXPECT() *MockChangeTransactionMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockChangeTransaction) Commit() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockChangeTransactionMockRecorder) Commit() *MockChangeTransactionCommitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockChangeTransaction)(nil).Commit))
	return &MockChangeTransactionCommitCall{Call: call}
}

// MockChangeTransactionCommitCall wrap *gomock.Call
type MockChangeTransactionCommitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangeTransactionCommitCall) Return(arg0 error) *MockChangeTransactionCommitCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangeTransactionCommitCall) Do(f func() error) *MockChangeTransactionCommitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangeTransactionCommitCall) DoAndReturn(f func() error) *MockChangeTransactionCommitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ExecContext mocks base method.
func (m *MockChangeTransaction) ExecContext(arg0 context.Context, arg1 string, arg2 ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecContext", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecContext indicates an expected call of ExecContext.
func (mr *MockChangeTransactionMockRecorder) ExecContext(arg0, arg1 any, arg2 ...any) *MockChangeTransactionExecContextCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecContext", reflect.TypeOf((*MockChangeTransaction)(nil).ExecContext), varargs...)
	return &MockChangeTransactionExecContextCall{Call: call}
}

// MockChangeTransactionExecContextCall wrap *gomock.Call
type MockChangeTransactionExecContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangeTransactionExecContextCall) Return(arg0 sql.Result, arg1 error) *MockChangeTransactionExecContextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangeTransactionExecContextCall) Do(f func(context.Context, string, ...any) (sql.Result, error)) *MockChangeTransactionExecContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangeTransactionExecContextCall) DoAndReturn(f func(context.Context, string, ...any) (sql.Result, error)) *MockChangeTransactionExecContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PrepareContext mocks base method.
func (m *MockChangeTransaction) PrepareContext(arg0 context.Context, arg1 string) (*sql.Stmt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareContext", arg0, arg1)
	ret0, _ := ret[0].(*sql.Stmt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareContext indicates an expected call of PrepareContext.
func (mr *MockChangeTransactionMockRecorder) PrepareContext(arg0, arg1 any) *MockChangeTransactionPrepareContextCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareContext", reflect.TypeOf((*MockChangeTransaction)(nil).PrepareContext), arg0, arg1)
	return &MockChangeTransactionPrepareContextCall{Call: call}
}

// MockChangeTransactionPrepareContextCall wrap *gomock.Call
type MockChangeTransactionPrepareContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangeTransactionPrepareContextCall) Return(arg0 *sql.Stmt, arg1 error) *MockChangeTransactionPrepareContextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangeTransactionPrepareContextCall) Do(f func(context.Context, string) (*sql.Stmt, error)) *MockChangeTransactionPrepareContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangeTransactionPrepareContextCall) DoAndReturn(f func(context.Context, string) (*sql.Stmt, error)) *MockChangeTransactionPrepareContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// QueryContext mocks base method.
func (m *MockChangeTransaction) QueryContext(arg0 context.Context, arg1 string, arg2 ...any) (*sql.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryContext", varargs...)
	ret0, _ := ret[0].(*sql.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryContext indicates an expected call of QueryContext.
func (mr *MockChangeTransactionMockRecorder) QueryContext(arg0, arg1 any, arg2 ...any) *MockChangeTransactionQueryContextCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryContext", reflect.TypeOf((*MockChangeTransaction)(nil).QueryContext), varargs...)
	return &MockChangeTransactionQueryContextCall{Call: call}
}

// MockChangeTransactionQueryContextCall wrap *gomock.Call
type MockChangeTransactionQueryContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangeTransactionQueryContextCall) Return(arg0 *sql.Rows, arg1 error) *MockChangeTransactionQueryContextCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangeTransactionQueryContextCall) Do(f func(context.Context, string, ...any) (*sql.Rows, error)) *MockChangeTransactionQueryContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangeTransactionQueryContextCall) DoAndReturn(f func(context.Context, string, ...any) (*sql.Rows, error)) *MockChangeTransactionQueryContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// QueryRowContext mocks base method.
func (m *MockChangeTransaction) QueryRowContext(arg0 context.Context, arg1 string, arg2 ...any) *sql.Row {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRowContext", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// QueryRowContext indicates an expected call of QueryRowContext.
func (mr *MockChangeTransactionMockRecorder) QueryRowContext(arg0, arg1 any, arg2 ...any) *MockChangeTransactionQueryRowContextCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRowContext", reflect.TypeOf((*MockChangeTransaction)(nil).QueryRowContext), varargs...)
	return &MockChangeTransactionQueryRowContextCall{Call: call}
}

// MockChangeTransactionQueryRowContextCall wrap *gomock.Call
type MockChangeTransactionQueryRowContextCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangeTransactionQueryRowContextCall) Return(arg0 *sql.Row) *MockChangeTransactionQueryRowContextCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangeTransactionQueryRowContextCall) Do(f func(context.Context, string, ...any) *sql.Row) *MockChangeTransactionQueryRowContextCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangeTransactionQueryRowContextCall) DoAndReturn(f func(context.Context, string, ...any) *sql.Row) *MockChangeTransactionQueryRowContextCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Rollback mocks base method.
func (m *MockChangeTransaction) Rollback() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback")
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockChangeTransactionMockRecorder) Rollback() *MockChangeTransactionRollbackCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockChangeTransaction)(nil).Rollback))
	return &MockChangeTransactionRollbackCall{Call: call}
}

// MockChangeTransactionRollbackCall wrap *gomock.Call
type MockChangeTransactionRollbackCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockChangeTransactionRollbackCall) Return(arg0 error) *MockChangeTransactionRollbackCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockChangeTransactionRollbackCall) Do(f func() error) *MockChangeTransactionRollbackCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockChangeTransactionRollbackCall) DoAndReturn(f func() error) *MockChangeTransactionRollbackCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
