// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

type Dep struct {
	ChildID  string
	ParentID string
}

type Issue struct {
	ID       string
	Title    string
	Type     string
	Status   string
	Priority int64
	Agent    *string
	Assignee *string
	Created  int64
	Updated  int64
	Closed   *int64
}
