// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbq

import (
	"context"
)

const getIssue = `-- name: GetIssue :one
SELECT id, title, type, status, priority, agent, assignee, created, updated, closed
FROM issues
WHERE id = ?
`

func (q *Queries) GetIssue(ctx context.Context, id string) (Issue, error) {
	row := q.db.QueryRowContext(ctx, getIssue, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Type,
		&i.Status,
		&i.Priority,
		&i.Agent,
		&i.Assignee,
		&i.Created,
		&i.Updated,
		&i.Closed,
	)
	return i, err
}
