// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/information (interfaces: Projects,Boards,Configurations,Readers,Reader)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package information -typed -write_package_comment=false . Projects,Boards,Configurations,Readers,Reader
//

package information

import (
	context "context"
	reflect "reflect"

	board "go.abhg.dev/cardamom/internal/board"
	configuration "go.abhg.dev/cardamom/internal/configuration"
	project "go.abhg.dev/cardamom/internal/project"
	gomock "go.uber.org/mock/gomock"
)

// MockProjects is a mock of Projects interface.
type MockProjects struct {
	ctrl     *gomock.Controller
	recorder *MockProjectsMockRecorder
	isgomock struct{}
}

// MockProjectsMockRecorder is the mock recorder for MockProjects.
type MockProjectsMockRecorder struct {
	mock *MockProjects
}

// NewMockProjects creates a new mock instance.
func NewMockProjects(ctrl *gomock.Controller) *MockProjects {
	mock := &MockProjects{ctrl: ctrl}
	mock.recorder = &MockProjectsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjects) EXPECT() *MockProjectsMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockProjects) Resolve(arg0 context.Context, arg1 *project.Selector) (*project.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", arg0, arg1)
	ret0, _ := ret[0].(*project.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockProjectsMockRecorder) Resolve(arg0, arg1 any) *MockProjectsResolveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockProjects)(nil).Resolve), arg0, arg1)
	return &MockProjectsResolveCall{Call: call}
}

// MockProjectsResolveCall wrap *gomock.Call
type MockProjectsResolveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProjectsResolveCall) Return(arg0 *project.State, arg1 error) *MockProjectsResolveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProjectsResolveCall) Do(f func(context.Context, *project.Selector) (*project.State, error)) *MockProjectsResolveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProjectsResolveCall) DoAndReturn(f func(context.Context, *project.Selector) (*project.State, error)) *MockProjectsResolveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockBoards is a mock of Boards interface.
type MockBoards struct {
	ctrl     *gomock.Controller
	recorder *MockBoardsMockRecorder
	isgomock struct{}
}

// MockBoardsMockRecorder is the mock recorder for MockBoards.
type MockBoardsMockRecorder struct {
	mock *MockBoards
}

// NewMockBoards creates a new mock instance.
func NewMockBoards(ctrl *gomock.Controller) *MockBoards {
	mock := &MockBoards{ctrl: ctrl}
	mock.recorder = &MockBoardsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoards) EXPECT() *MockBoardsMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockBoards) Get(arg0 context.Context, arg1 board.ID) (*board.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*board.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBoardsMockRecorder) Get(arg0, arg1 any) *MockBoardsGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBoards)(nil).Get), arg0, arg1)
	return &MockBoardsGetCall{Call: call}
}

// MockBoardsGetCall wrap *gomock.Call
type MockBoardsGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardsGetCall) Return(arg0 *board.State, arg1 error) *MockBoardsGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardsGetCall) Do(f func(context.Context, board.ID) (*board.State, error)) *MockBoardsGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardsGetCall) DoAndReturn(f func(context.Context, board.ID) (*board.State, error)) *MockBoardsGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockConfigurations is a mock of Configurations interface.
type MockConfigurations struct {
	ctrl     *gomock.Controller
	recorder *MockConfigurationsMockRecorder
	isgomock struct{}
}

// MockConfigurationsMockRecorder is the mock recorder for MockConfigurations.
type MockConfigurationsMockRecorder struct {
	mock *MockConfigurations
}

// NewMockConfigurations creates a new mock instance.
func NewMockConfigurations(ctrl *gomock.Controller) *MockConfigurations {
	mock := &MockConfigurations{ctrl: ctrl}
	mock.recorder = &MockConfigurationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigurations) EXPECT() *MockConfigurationsMockRecorder {
	return m.recorder
}

// ResolveConfiguration mocks base method.
func (m *MockConfigurations) ResolveConfiguration(arg0 context.Context, arg1 board.ID) (configuration.Configuration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveConfiguration", arg0, arg1)
	ret0, _ := ret[0].(configuration.Configuration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveConfiguration indicates an expected call of ResolveConfiguration.
func (mr *MockConfigurationsMockRecorder) ResolveConfiguration(arg0, arg1 any) *MockConfigurationsResolveConfigurationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveConfiguration", reflect.TypeOf((*MockConfigurations)(nil).ResolveConfiguration), arg0, arg1)
	return &MockConfigurationsResolveConfigurationCall{Call: call}
}

// MockConfigurationsResolveConfigurationCall wrap *gomock.Call
type MockConfigurationsResolveConfigurationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockConfigurationsResolveConfigurationCall) Return(arg0 configuration.Configuration, arg1 error) *MockConfigurationsResolveConfigurationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockConfigurationsResolveConfigurationCall) Do(f func(context.Context, board.ID) (configuration.Configuration, error)) *MockConfigurationsResolveConfigurationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockConfigurationsResolveConfigurationCall) DoAndReturn(f func(context.Context, board.ID) (configuration.Configuration, error)) *MockConfigurationsResolveConfigurationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockReaders is a mock of Readers interface.
type MockReaders struct {
	ctrl     *gomock.Controller
	recorder *MockReadersMockRecorder
	isgomock struct{}
}

// MockReadersMockRecorder is the mock recorder for MockReaders.
type MockReadersMockRecorder struct {
	mock *MockReaders
}

// NewMockReaders creates a new mock instance.
func NewMockReaders(ctrl *gomock.Controller) *MockReaders {
	mock := &MockReaders{ctrl: ctrl}
	mock.recorder = &MockReadersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReaders) EXPECT() *MockReadersMockRecorder {
	return m.recorder
}

// Reader mocks base method.
func (m *MockReaders) Reader(arg0 board.ID, arg1 configuration.Configuration) (Reader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reader", arg0, arg1)
	ret0, _ := ret[0].(Reader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Reader indicates an expected call of Reader.
func (mr *MockReadersMockRecorder) Reader(arg0, arg1 any) *MockReadersReaderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reader", reflect.TypeOf((*MockReaders)(nil).Reader), arg0, arg1)
	return &MockReadersReaderCall{Call: call}
}

// MockReadersReaderCall wrap *gomock.Call
type MockReadersReaderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReadersReaderCall) Return(arg0 Reader, arg1 error) *MockReadersReaderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReadersReaderCall) Do(f func(board.ID, configuration.Configuration) (Reader, error)) *MockReadersReaderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReadersReaderCall) DoAndReturn(f func(board.ID, configuration.Configuration) (Reader, error)) *MockReadersReaderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockReader) Read(arg0 context.Context) (Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", arg0)
	ret0, _ := ret[0].(Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockReaderMockRecorder) Read(arg0 any) *MockReaderReadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReader)(nil).Read), arg0)
	return &MockReaderReadCall{Call: call}
}

// MockReaderReadCall wrap *gomock.Call
type MockReaderReadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReaderReadCall) Return(arg0 Snapshot, arg1 error) *MockReaderReadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReaderReadCall) Do(f func(context.Context) (Snapshot, error)) *MockReaderReadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReaderReadCall) DoAndReturn(f func(context.Context) (Snapshot, error)) *MockReaderReadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
