// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/web/recordconnect (interfaces: BoardRecords,BoardRecordFactory)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package recordconnect -typed -write_package_comment=false . BoardRecords,BoardRecordFactory
//

package recordconnect

import (
	context "context"
	reflect "reflect"

	board "go.abhg.dev/cardamom/internal/board"
	issue "go.abhg.dev/cardamom/internal/issue"
	record "go.abhg.dev/cardamom/internal/issue/record"
	gomock "go.uber.org/mock/gomock"
)

// MockBoardRecords is a mock of BoardRecords interface.
type MockBoardRecords struct {
	ctrl     *gomock.Controller
	recorder *MockBoardRecordsMockRecorder
	isgomock struct{}
}

// MockBoardRecordsMockRecorder is the mock recorder for MockBoardRecords.
type MockBoardRecordsMockRecorder struct {
	mock *MockBoardRecords
}

// NewMockBoardRecords creates a new mock instance.
func NewMockBoardRecords(ctrl *gomock.Controller) *MockBoardRecords {
	mock := &MockBoardRecords{ctrl: ctrl}
	mock.recorder = &MockBoardRecordsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardRecords) EXPECT() *MockBoardRecordsMockRecorder {
	return m.recorder
}

// AddLogEntry mocks base method.
func (m *MockBoardRecords) AddLogEntry(arg0 context.Context, arg1 issue.Invocation, arg2 record.AddLogEntryRequest) (record.AddLogEntryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddLogEntry", arg0, arg1, arg2)
	ret0, _ := ret[0].(record.AddLogEntryResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddLogEntry indicates an expected call of AddLogEntry.
func (mr *MockBoardRecordsMockRecorder) AddLogEntry(arg0, arg1, arg2 any) *MockBoardRecordsAddLogEntryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLogEntry", reflect.TypeOf((*MockBoardRecords)(nil).AddLogEntry), arg0, arg1, arg2)
	return &MockBoardRecordsAddLogEntryCall{Call: call}
}

// MockBoardRecordsAddLogEntryCall wrap *gomock.Call
type MockBoardRecordsAddLogEntryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardRecordsAddLogEntryCall) Return(arg0 record.AddLogEntryResult, arg1 error) *MockBoardRecordsAddLogEntryCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardRecordsAddLogEntryCall) Do(f func(context.Context, issue.Invocation, record.AddLogEntryRequest) (record.AddLogEntryResult, error)) *MockBoardRecordsAddLogEntryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardRecordsAddLogEntryCall) DoAndReturn(f func(context.Context, issue.Invocation, record.AddLogEntryRequest) (record.AddLogEntryResult, error)) *MockBoardRecordsAddLogEntryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AppendState mocks base method.
func (m *MockBoardRecords) AppendState(arg0 context.Context, arg1 issue.Invocation, arg2 record.SetStateRequest) (record.StateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendState", arg0, arg1, arg2)
	ret0, _ := ret[0].(record.StateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppendState indicates an expected call of AppendState.
func (mr *MockBoardRecordsMockRecorder) AppendState(arg0, arg1, arg2 any) *MockBoardRecordsAppendStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendState", reflect.TypeOf((*MockBoardRecords)(nil).AppendState), arg0, arg1, arg2)
	return &MockBoardRecordsAppendStateCall{Call: call}
}

// MockBoardRecordsAppendStateCall wrap *gomock.Call
type MockBoardRecordsAppendStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardRecordsAppendStateCall) Return(arg0 record.StateResult, arg1 error) *MockBoardRecordsAppendStateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardRecordsAppendStateCall) Do(f func(context.Context, issue.Invocation, record.SetStateRequest) (record.StateResult, error)) *MockBoardRecordsAppendStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardRecordsAppendStateCall) DoAndReturn(f func(context.Context, issue.Invocation, record.SetStateRequest) (record.StateResult, error)) *MockBoardRecordsAppendStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ClearState mocks base method.
func (m *MockBoardRecords) ClearState(arg0 context.Context, arg1 issue.Invocation, arg2 record.ClearStateRequest) (record.StateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearState", arg0, arg1, arg2)
	ret0, _ := ret[0].(record.StateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearState indicates an expected call of ClearState.
func (mr *MockBoardRecordsMockRecorder) ClearState(arg0, arg1, arg2 any) *MockBoardRecordsClearStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearState", reflect.TypeOf((*MockBoardRecords)(nil).ClearState), arg0, arg1, arg2)
	return &MockBoardRecordsClearStateCall{Call: call}
}

// MockBoardRecordsClearStateCall wrap *gomock.Call
type MockBoardRecordsClearStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardRecordsClearStateCall) Return(arg0 record.StateResult, arg1 error) *MockBoardRecordsClearStateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardRecordsClearStateCall) Do(f func(context.Context, issue.Invocation, record.ClearStateRequest) (record.StateResult, error)) *MockBoardRecordsClearStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardRecordsClearStateCall) DoAndReturn(f func(context.Context, issue.Invocation, record.ClearStateRequest) (record.StateResult, error)) *MockBoardRecordsClearStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CommitState mocks base method.
func (m *MockBoardRecords) CommitState(arg0 context.Context, arg1 issue.Invocation, arg2 record.CommitStateRequest) (record.CommitStateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitState", arg0, arg1, arg2)
	ret0, _ := ret[0].(record.CommitStateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitState indicates an expected call of CommitState.
func (mr *MockBoardRecordsMockRecorder) CommitState(arg0, arg1, arg2 any) *MockBoardRecordsCommitStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitState", reflect.TypeOf((*MockBoardRecords)(nil).CommitState), arg0, arg1, arg2)
	return &MockBoardRecordsCommitStateCall{Call: call}
}

// MockBoardRecordsCommitStateCall wrap *gomock.Call
type MockBoardRecordsCommitStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardRecordsCommitStateCall) Return(arg0 record.CommitStateResult, arg1 error) *MockBoardRecordsCommitStateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardRecordsCommitStateCall) Do(f func(context.Context, issue.Invocation, record.CommitStateRequest) (record.CommitStateResult, error)) *MockBoardRecordsCommitStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardRecordsCommitStateCall) DoAndReturn(f func(context.Context, issue.Invocation, record.CommitStateRequest) (record.CommitStateResult, error)) *MockBoardRecordsCommitStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetResult mocks base method.
func (m *MockBoardRecords) GetResult(arg0 context.Context, arg1 record.GetResultRequest) (issue.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResult", arg0, arg1)
	ret0, _ := ret[0].(issue.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResult indicates an expected call of GetResult.
func (mr *MockBoardRecordsMockRecorder) GetResult(arg0, arg1 any) *MockBoardRecordsGetResultCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResult", reflect.TypeOf((*MockBoardRecords)(nil).GetResult), arg0, arg1)
	return &MockBoardRecordsGetResultCall{Call: call}
}

// MockBoardRecordsGetResultCall wrap *gomock.Call
type MockBoardRecordsGetResultCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardRecordsGetResultCall) Return(arg0 issue.Result, arg1 error) *MockBoardRecordsGetResultCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardRecordsGetResultCall) Do(f func(context.Context, record.GetResultRequest) (issue.Result, error)) *MockBoardRecordsGetResultCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardRecordsGetResultCall) DoAndReturn(f func(context.Context, record.GetResultRequest) (issue.Result, error)) *MockBoardRecordsGetResultCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetState mocks base method.
func (m *MockBoardRecords) GetState(arg0 context.Context, arg1 record.GetStateRequest) (record.GetStateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetState", arg0, arg1)
	ret0, _ := ret[0].(record.GetStateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetState indicates an expected call of GetState.
func (mr *MockBoardRecordsMockRecorder) GetState(arg0, arg1 any) *MockBoardRecordsGetStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetState", reflect.TypeOf((*MockBoardRecords)(nil).GetState), arg0, arg1)
	return &MockBoardRecordsGetStateCall{Call: call}
}

// MockBoardRecordsGetStateCall wrap *gomock.Call
type MockBoardRecordsGetStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardRecordsGetStateCall) Return(arg0 record.GetStateResult, arg1 error) *MockBoardRecordsGetStateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardRecordsGetStateCall) Do(f func(context.Context, record.GetStateRequest) (record.GetStateResult, error)) *MockBoardRecordsGetStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardRecordsGetStateCall) DoAndReturn(f func(context.Context, record.GetStateRequest) (record.GetStateResult, error)) *MockBoardRecordsGetStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListLogEntries mocks base method.
func (m *MockBoardRecords) ListLogEntries(arg0 context.Context, arg1 issue.LogListRequest) ([]issue.LogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLogEntries", arg0, arg1)
	ret0, _ := ret[0].([]issue.LogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListLogEntries indicates an expected call of ListLogEntries.
func (mr *MockBoardRecordsMockRecorder) ListLogEntries(arg0, arg1 any) *MockBoardRecordsListLogEntriesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLogEntries", reflect.TypeOf((*MockBoardRecords)(nil).ListLogEntries), arg0, arg1)
	return &MockBoardRecordsListLogEntriesCall{Call: call}
}

// MockBoardRecordsListLogEntriesCall wrap *gomock.Call
type MockBoardRecordsListLogEntriesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardRecordsListLogEntriesCall) Return(arg0 []issue.LogEntry, arg1 error) *MockBoardRecordsListLogEntriesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardRecordsListLogEntriesCall) Do(f func(context.Context, issue.LogListRequest) ([]issue.LogEntry, error)) *MockBoardRecordsListLogEntriesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardRecordsListLogEntriesCall) DoAndReturn(f func(context.Context, issue.LogListRequest) ([]issue.LogEntry, error)) *MockBoardRecordsListLogEntriesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetResult mocks base method.
func (m *MockBoardRecords) SetResult(arg0 context.Context, arg1 issue.Invocation, arg2 record.SetResultRequest) (record.SetResultResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetResult", arg0, arg1, arg2)
	ret0, _ := ret[0].(record.SetResultResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetResult indicates an expected call of SetResult.
func (mr *MockBoardRecordsMockRecorder) SetResult(arg0, arg1, arg2 any) *MockBoardRecordsSetResultCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetResult", reflect.TypeOf((*MockBoardRecords)(nil).SetResult), arg0, arg1, arg2)
	return &MockBoardRecordsSetResultCall{Call: call}
}

// MockBoardRecordsSetResultCall wrap *gomock.Call
type MockBoardRecordsSetResultCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardRecordsSetResultCall) Return(arg0 record.SetResultResult, arg1 error) *MockBoardRecordsSetResultCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardRecordsSetResultCall) Do(f func(context.Context, issue.Invocation, record.SetResultRequest) (record.SetResultResult, error)) *MockBoardRecordsSetResultCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardRecordsSetResultCall) DoAndReturn(f func(context.Context, issue.Invocation, record.SetResultRequest) (record.SetResultResult, error)) *MockBoardRecordsSetResultCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetState mocks base method.
func (m *MockBoardRecords) SetState(arg0 context.Context, arg1 issue.Invocation, arg2 record.SetStateRequest) (record.StateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetState", arg0, arg1, arg2)
	ret0, _ := ret[0].(record.StateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetState indicates an expected call of SetState.
func (mr *MockBoardRecordsMockRecorder) SetState(arg0, arg1, arg2 any) *MockBoardRecordsSetStateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetState", reflect.TypeOf((*MockBoardRecords)(nil).SetState), arg0, arg1, arg2)
	return &MockBoardRecordsSetStateCall{Call: call}
}

// MockBoardRecordsSetStateCall wrap *gomock.Call
type MockBoardRecordsSetStateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardRecordsSetStateCall) Return(arg0 record.StateResult, arg1 error) *MockBoardRecordsSetStateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardRecordsSetStateCall) Do(f func(context.Context, issue.Invocation, record.SetStateRequest) (record.StateResult, error)) *MockBoardRecordsSetStateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardRecordsSetStateCall) DoAndReturn(f func(context.Context, issue.Invocation, record.SetStateRequest) (record.StateResult, error)) *MockBoardRecordsSetStateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockBoardRecordFactory is a mock of BoardRecordFactory interface.
type MockBoardRecordFactory struct {
	ctrl     *gomock.Controller
	recorder *MockBoardRecordFactoryMockRecorder
	isgomock struct{}
}

// MockBoardRecordFactoryMockRecorder is the mock recorder for MockBoardRecordFactory.
type MockBoardRecordFactoryMockRecorder struct {
	mock *MockBoardRecordFactory
}

// NewMockBoardRecordFactory creates a new mock instance.
func NewMockBoardRecordFactory(ctrl *gomock.Controller) *MockBoardRecordFactory {
	mock := &MockBoardRecordFactory{ctrl: ctrl}
	mock.recorder = &MockBoardRecordFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBoardRecordFactory) EXPECT() *MockBoardRecordFactoryMockRecorder {
	return m.recorder
}

// Records mocks base method.
func (m *MockBoardRecordFactory) Records(arg0 board.ID) (BoardRecords, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Records", arg0)
	ret0, _ := ret[0].(BoardRecords)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Records indicates an expected call of Records.
func (mr *MockBoardRecordFactoryMockRecorder) Records(arg0 any) *MockBoardRecordFactoryRecordsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Records", reflect.TypeOf((*MockBoardRecordFactory)(nil).Records), arg0)
	return &MockBoardRecordFactoryRecordsCall{Call: call}
}

// MockBoardRecordFactoryRecordsCall wrap *gomock.Call
type MockBoardRecordFactoryRecordsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockBoardRecordFactoryRecordsCall) Return(arg0 BoardRecords, arg1 error) *MockBoardRecordFactoryRecordsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockBoardRecordFactoryRecordsCall) Do(f func(board.ID) (BoardRecords, error)) *MockBoardRecordFactoryRecordsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockBoardRecordFactoryRecordsCall) DoAndReturn(f func(board.ID) (BoardRecords, error)) *MockBoardRecordFactoryRecordsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
