// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/dump (interfaces: SnapshotReader,Publisher)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package dump -typed -write_package_comment=false . SnapshotReader,Publisher
//

package dump

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSnapshotReader is a mock of SnapshotReader interface.
type MockSnapshotReader struct {
	ctrl     *gomock.Controller
	recorder *MockSnapshotReaderMockRecorder
	isgomock struct{}
}

// MockSnapshotReaderMockRecorder is the mock recorder for MockSnapshotReader.
type MockSnapshotReaderMockRecorder struct {
	mock *MockSnapshotReader
}

// NewMockSnapshotReader creates a new mock instance.
func NewMockSnapshotReader(ctrl *gomock.Controller) *MockSnapshotReader {
	mock := &MockSnapshotReader{ctrl: ctrl}
	mock.recorder = &MockSnapshotReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnapshotReader) EXPECT() *MockSnapshotReaderMockRecorder {
	return m.recorder
}

// ReadDumpSnapshot mocks base method.
func (m *MockSnapshotReader) ReadDumpSnapshot(arg0 context.Context) (BoardSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDumpSnapshot", arg0)
	ret0, _ := ret[0].(BoardSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDumpSnapshot indicates an expected call of ReadDumpSnapshot.
func (mr *MockSnapshotReaderMockRecorder) ReadDumpSnapshot(arg0 any) *MockSnapshotReaderReadDumpSnapshotCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDumpSnapshot", reflect.TypeOf((*MockSnapshotReader)(nil).ReadDumpSnapshot), arg0)
	return &MockSnapshotReaderReadDumpSnapshotCall{Call: call}
}

// MockSnapshotReaderReadDumpSnapshotCall wrap *gomock.Call
type MockSnapshotReaderReadDumpSnapshotCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSnapshotReaderReadDumpSnapshotCall) Return(arg0 BoardSnapshot, arg1 error) *MockSnapshotReaderReadDumpSnapshotCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSnapshotReaderReadDumpSnapshotCall) Do(f func(context.Context) (BoardSnapshot, error)) *MockSnapshotReaderReadDumpSnapshotCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSnapshotReaderReadDumpSnapshotCall) DoAndReturn(f func(context.Context) (BoardSnapshot, error)) *MockSnapshotReaderReadDumpSnapshotCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockPublisher is a mock of Publisher interface.
type MockPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherMockRecorder
	isgomock struct{}
}

// MockPublisherMockRecorder is the mock recorder for MockPublisher.
type MockPublisherMockRecorder struct {
	mock *MockPublisher
}

// NewMockPublisher creates a new mock instance.
func NewMockPublisher(ctrl *gomock.Controller) *MockPublisher {
	mock := &MockPublisher{ctrl: ctrl}
	mock.recorder = &MockPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPublisher) EXPECT() *MockPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockPublisher) Publish(arg0 context.Context, arg1 Publication) (PublicationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1)
	ret0, _ := ret[0].(PublicationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockPublisherMockRecorder) Publish(arg0, arg1 any) *MockPublisherPublishCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockPublisher)(nil).Publish), arg0, arg1)
	return &MockPublisherPublishCall{Call: call}
}

// MockPublisherPublishCall wrap *gomock.Call
type MockPublisherPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPublisherPublishCall) Return(arg0 PublicationResult, arg1 error) *MockPublisherPublishCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPublisherPublishCall) Do(f func(context.Context, Publication) (PublicationResult, error)) *MockPublisherPublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPublisherPublishCall) DoAndReturn(f func(context.Context, Publication) (PublicationResult, error)) *MockPublisherPublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
