package dump

import (
	"bytes"
	"cmp"
	"fmt"
	"io"
	"net/url"
	"path"
	"regexp"
	"slices"
	"strings"
	"time"
)

var safeIssuePath = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]*$`)

// RenderedDump is a complete deterministic dump before filesystem publication.
type RenderedDump struct {
	// Provenance identifies the project and board represented by every file.
	Provenance Provenance

	// Revision is the canonical source revision represented by every file.
	Revision int64

	// Selection is the normalized issue selection represented by the dump.
	Selection Selection

	// IssueCount is the number of rendered issue pages.
	IssueCount int

	// Files contains the selected generated files ordered by path.
	Files []*GeneratedFile
}

// render produces the board entry point and one issue page for every selected
// issue.
func render(snapshot Snapshot) (RenderedDump, error) {
	if err := snapshot.Provenance.validate(); err != nil {
		return RenderedDump{}, err
	}
	issues := slices.Clone(snapshot.Issues)
	for _, issue := range issues {
		if !safeIssuePath.MatchString(issue.ID) || issue.ID == "." || issue.ID == ".." {
			return RenderedDump{}, fmt.Errorf("render issue %q: issue ID is not safe for a dump path", issue.ID)
		}
	}
	slices.SortFunc(issues, func(a, b Issue) int { return cmp.Compare(a.ID, b.ID) })

	view := renderView{
		snapshot: snapshot,
		issues:   issues,
		byID:     make(map[string]Issue, len(issues)),
	}
	for _, issue := range issues {
		view.byID[issue.ID] = issue
	}

	var files []*GeneratedFile
	if snapshot.Selection.Mode == SelectionWholeBoard {
		file, err := renderFile(snapshot.Provenance, "README.md", "board", view.boardPage())
		if err != nil {
			return RenderedDump{}, err
		}
		files = append(files, file)
	}
	for _, issue := range issues {
		file, err := renderFile(
			snapshot.Provenance,
			canonicalIssuePath(issue),
			"issue:"+issue.ID,
			view.issuePage(issue),
		)
		if err != nil {
			return RenderedDump{}, err
		}
		files = append(files, file)
	}
	slices.SortFunc(files, func(a, b *GeneratedFile) int {
		return cmp.Compare(a.Path(), b.Path())
	})

	return RenderedDump{
		Provenance: snapshot.Provenance,
		Revision:   snapshot.Revision,
		Selection:  normalizedRenderedSelection(snapshot.Selection),
		IssueCount: len(issues),
		Files:      files,
	}, nil
}

func renderFile(
	provenance Provenance,
	path string,
	identity string,
	body []byte,
) (*GeneratedFile, error) {
	content, err := encodeOwnedFile(provenance, identity, body)
	if err != nil {
		return nil, fmt.Errorf("render %q: %w", path, err)
	}
	return NewGeneratedFile(GeneratedFileConfig{
		Path: path, Identity: identity, Size: int64(len(content)),
		Open: func() (io.ReadCloser, error) {
			return io.NopCloser(bytes.NewReader(content)), nil
		},
	})
}

// renderView indexes one selected snapshot for deterministic cross-page
// navigation without changing the snapshot reader's contract.
type renderView struct {
	snapshot Snapshot
	issues   []Issue
	byID     map[string]Issue
}

func (v *renderView) boardPage() []byte {
	var out bytes.Buffer
	writeLine(&out, "# Cardamom board dump")
	writeLine(&out, "")
	writeLine(&out, "This file is generated by `card dump`.")
	writeLine(&out, "")
	writeLine(&out, "## Provenance")
	writeLine(&out, "")
	writeLine(&out, "| Field | Value |")
	writeLine(&out, "| --- | --- |")
	writeLine(&out, "| Board ID | "+code(v.snapshot.BoardID)+" |")
	writeLine(&out, fmt.Sprintf("| Canonical revision | %d |", v.snapshot.Revision))
	writeLine(&out, "| Selection | "+selectionText(v.snapshot.Selection)+" |")
	writeLine(&out, "")
	writeLine(&out, "## Board description")
	writeLine(&out, "")
	writeAuthored(&out, v.snapshot.Description, "No board description.")
	writeLine(&out, "## Lifecycle summary")
	writeLine(&out, "")
	counts := map[string]int{}
	for _, issue := range v.issues {
		counts[issue.Status]++
	}
	writeLine(&out, "| Status | Issues |")
	writeLine(&out, "| --- | ---: |")
	writeLine(&out, fmt.Sprintf("| Ready | %d |", counts["ready"]))
	writeLine(&out, fmt.Sprintf("| Blocked | %d |", counts["blocked"]))
	writeLine(&out, fmt.Sprintf("| In progress | %d |", counts["in_progress"]))
	writeLine(&out, fmt.Sprintf("| Waiting | %d |", counts["waiting"]))
	writeLine(&out, fmt.Sprintf("| Closed | %d |", counts["closed"]))
	writeLine(&out, fmt.Sprintf("| Cancelled | %d |", counts["cancelled"]))
	writeLine(&out, "")
	writeLine(&out, "## Containment")
	writeLine(&out, "")
	if len(v.issues) == 0 {
		writeLine(&out, "No issues.")
		writeLine(&out, "")
	} else {
		v.writeContainmentTree(&out)
	}
	writeLine(&out, "## Issue index")
	writeLine(&out, "")
	if len(v.issues) == 0 {
		writeLine(&out, "No issues.")
	} else {
		writeLine(&out, "| ID | Title | Type | Status | Priority | Assignee |")
		writeLine(&out, "| --- | --- | --- | --- | ---: | --- |")
		for _, issue := range v.issues {
			assignee := "-"
			if issue.Assignee != nil {
				assignee = escapeTable(*issue.Assignee)
			}
			writeLine(&out, fmt.Sprintf("| [%s](%s) | %s | %s | %s | %d | %s |",
				escapeText(issue.ID), canonicalIssuePath(issue), escapeTable(issue.Title),
				escapeTable(issue.Type), escapeTable(issue.Status), issue.Priority, assignee))
		}
	}
	return finishMarkdown(out.Bytes())
}

func (v *renderView) writeContainmentTree(out *bytes.Buffer) {
	parent := make(map[string]string)
	children := make(map[string][]Issue)
	for _, edge := range v.snapshot.Containment {
		if _, childSelected := v.byID[edge.ChildID]; !childSelected {
			continue
		}
		parent[edge.ChildID] = edge.ParentID
		if _, parentSelected := v.byID[edge.ParentID]; parentSelected {
			children[edge.ParentID] = append(children[edge.ParentID], v.byID[edge.ChildID])
		}
	}
	for id := range children {
		sortTreeIssues(children[id])
	}
	var roots []Issue
	for _, issue := range v.issues {
		if _, selected := v.byID[parent[issue.ID]]; !selected {
			roots = append(roots, issue)
		}
	}
	sortTreeIssues(roots)
	var writeNode func(Issue, int)
	writeNode = func(issue Issue, depth int) {
		annotation := ""
		if parentID := parent[issue.ID]; parentID != "" {
			if _, selected := v.byID[parentID]; !selected {
				annotation = " (external parent " + code(parentID) + ")"
			}
		}
		writeLine(out, strings.Repeat("  ", depth)+"- "+issueLink(issue, "")+annotation)
		for _, child := range children[issue.ID] {
			writeNode(child, depth+1)
		}
	}
	for _, root := range roots {
		writeNode(root, 0)
	}
	writeLine(out, "")
}

func (v *renderView) issuePage(issue Issue) []byte {
	var out bytes.Buffer
	if v.snapshot.Selection.Mode == SelectionWholeBoard {
		writeLine(&out, "[Board dump](../README.md)")
		writeLine(&out, "")
	}
	writeLine(&out, "# "+escapeText(issue.ID)+": "+escapeText(issue.Title))
	writeLine(&out, "")
	writeLine(&out, "| Field | Value |")
	writeLine(&out, "| --- | --- |")
	writeLine(&out, "| Type | "+escapeTable(issue.Type)+" |")
	writeLine(&out, "| Status | "+escapeTable(issue.Status)+" |")
	writeLine(&out, fmt.Sprintf("| Priority | %d |", issue.Priority))
	writeLine(&out, "| Assignee | "+optionalTable(issue.Assignee)+" |")
	writeLine(&out, "| Created | "+timestamp(issue.Created)+" |")
	writeLine(&out, "| Updated | "+timestamp(issue.Updated)+" |")
	writeLine(&out, "| Started | "+optionalTimestamp(issue.StartedAt)+" |")
	writeLine(&out, "| Closed | "+optionalTimestamp(issue.Closed)+" |")
	writeLine(&out, fmt.Sprintf("| Revision | %d |", issue.Revision))
	writeLine(&out, "| Labels | "+labelsText(issue.Labels)+" |")

	writeSection(&out, "Summary", issue.Summary, "None.")
	writeSection(&out, "Details", issue.Details, "None.")
	writeSection(&out, "Current state", issue.State, "None.")
	if issue.NextAction != nil {
		writeLine(&out, "**Next action**")
		writeLine(&out, "")
		writeAuthored(&out, issue.NextAction, "None.")
	}
	var result *string
	for _, item := range v.snapshot.Results {
		if item.IssueID == issue.ID {
			result = &item.Body
			break
		}
	}
	writeSection(&out, "Result", result, "None.")
	writeLine(&out, "## Graph context")
	writeLine(&out, "")
	v.writeRelation(&out, "Containment parent", issue.ID, relationContainmentParent)
	v.writeRelation(&out, "Containment children", issue.ID, relationContainmentChildren)
	v.writeRelation(&out, "Depends on", issue.ID, relationDependsOn)
	v.writeRelation(&out, "Blocks", issue.ID, relationBlocks)
	if v.snapshot.Selection.Descendants == IncludeDescendants {
		v.writeDescendantSummary(&out, issue.ID)
	}

	writeLine(&out, "## Log")
	writeLine(&out, "")
	logEntryCount := 0
	for _, logEntry := range v.snapshot.LogEntries {
		if logEntry.IssueID != issue.ID {
			continue
		}
		logEntryCount++
		if strings.HasPrefix(logEntry.ID.String(), "log_") {
			writeLine(&out, `<a id="`+logEntry.ID.String()+`"></a>`)
		}
		writeLine(&out, logEntryHeading(logEntry))
		writeLine(&out, "")
		body := logEntry.Body
		writeAuthored(&out, &body, "None.")
		if logEntry.NextAction != nil {
			writeLine(&out, "**Planned next action**")
			writeLine(&out, "")
			writeAuthored(&out, logEntry.NextAction, "None.")
		}
	}
	if logEntryCount == 0 {
		writeLine(&out, "No log entries.")
		writeLine(&out, "")
	}

	return finishMarkdown(out.Bytes())
}

func logEntryHeading(entry LogEntry) string {
	author := "unknown actor"
	if entry.Author != nil {
		author = escapeText(*entry.Author)
	}
	created := "unknown time"
	if entry.Created != nil {
		created = timestamp(*entry.Created)
	}
	if entry.Kind == "state_snapshot" {
		committer := author
		if entry.Committer != nil {
			committer = escapeText(*entry.Committer)
		}
		return fmt.Sprintf(
			"### State snapshot by %s, committed by %s at %s (log entry %s)",
			author,
			committer,
			created,
			entry.ID,
		)
	}
	return fmt.Sprintf(
		"### %s at %s (log entry %s)",
		author,
		created,
		entry.ID,
	)
}

// writeDescendantSummary makes a page a subtree entrypoint when the rendered
// selection includes containment descendants.
func (v *renderView) writeDescendantSummary(out *bytes.Buffer, rootID string) {
	children := make(map[string][]Issue)
	for _, edge := range v.snapshot.Containment {
		child, childSelected := v.byID[edge.ChildID]
		if _, parentSelected := v.byID[edge.ParentID]; childSelected && parentSelected {
			children[edge.ParentID] = append(children[edge.ParentID], child)
		}
	}
	if len(children[rootID]) == 0 {
		return
	}
	for parentID := range children {
		sortTreeIssues(children[parentID])
	}

	counts := map[string]int{}
	var countDescendants func(string)
	countDescendants = func(parentID string) {
		for _, child := range children[parentID] {
			counts[child.Status]++
			countDescendants(child.ID)
		}
	}
	countDescendants(rootID)
	writeLine(out, "## Descendant lifecycle summary")
	writeLine(out, "")
	writeLine(out, "| Status | Issues |")
	writeLine(out, "| --- | ---: |")
	writeLine(out, fmt.Sprintf("| Ready | %d |", counts["ready"]))
	writeLine(out, fmt.Sprintf("| Blocked | %d |", counts["blocked"]))
	writeLine(out, fmt.Sprintf("| In progress | %d |", counts["in_progress"]))
	writeLine(out, fmt.Sprintf("| Waiting | %d |", counts["waiting"]))
	writeLine(out, fmt.Sprintf("| Closed | %d |", counts["closed"]))
	writeLine(out, fmt.Sprintf("| Cancelled | %d |", counts["cancelled"]))
	writeLine(out, "")
	writeLine(out, "## Descendant containment tree")
	writeLine(out, "")
	var writeNode func(Issue, int)
	writeNode = func(descendant Issue, depth int) {
		writeLine(out, strings.Repeat("  ", depth)+"- "+issueLink(descendant, "../"))
		for _, child := range children[descendant.ID] {
			writeNode(child, depth+1)
		}
	}
	for _, child := range children[rootID] {
		writeNode(child, 0)
	}
	writeLine(out, "")
}

type relationKind int

const (
	relationContainmentParent relationKind = iota
	relationContainmentChildren
	relationDependsOn
	relationBlocks
)

func (v *renderView) writeRelation(out *bytes.Buffer, heading, issueID string, kind relationKind) {
	writeLine(out, "### "+heading)
	writeLine(out, "")
	var ids []string
	switch kind {
	case relationContainmentParent:
		for _, edge := range v.snapshot.Containment {
			if edge.ChildID == issueID {
				ids = append(ids, edge.ParentID)
			}
		}
	case relationContainmentChildren:
		for _, edge := range v.snapshot.Containment {
			if edge.ParentID == issueID {
				ids = append(ids, edge.ChildID)
			}
		}
	case relationDependsOn:
		for _, edge := range v.snapshot.Dependencies {
			if edge.ChildID == issueID {
				ids = append(ids, edge.ParentID)
			}
		}
	case relationBlocks:
		for _, edge := range v.snapshot.Dependencies {
			if edge.ParentID == issueID {
				ids = append(ids, edge.ChildID)
			}
		}
	}
	slices.Sort(ids)
	ids = slices.Compact(ids)
	if len(ids) == 0 {
		writeLine(out, "None.")
		writeLine(out, "")
		return
	}
	for _, id := range ids {
		if related, selected := v.byID[id]; selected {
			writeLine(out, "- "+issueLink(related, "../"))
		} else {
			writeLine(out, "- "+code(id)+" (not included in this dump)")
		}
	}
	writeLine(out, "")
}

func normalizedRenderedSelection(selection Selection) Selection {
	result := selection
	result.IssueIDs = slices.Clone(selection.IssueIDs)
	slices.Sort(result.IssueIDs)
	result.IssueIDs = slices.Compact(result.IssueIDs)
	return result
}

func selectionText(selection Selection) string {
	switch selection.Mode {
	case SelectionWholeBoard:
		return "whole-board"
	case SelectionIssues:
		values := make([]string, len(selection.IssueIDs))
		for index, id := range selection.IssueIDs {
			values[index] = code(id)
		}
		if selection.Descendants == IncludeDescendants {
			return "issues with descendants " + strings.Join(values, ", ")
		}
		return "named issues only " + strings.Join(values, ", ")
	default:
		return escapeTable(selection.Mode.String())
	}
}

func sortTreeIssues(issues []Issue) {
	slices.SortFunc(issues, func(a, b Issue) int {
		if order := cmp.Compare(a.Priority, b.Priority); order != 0 {
			return order
		}
		if order := cmp.Compare(a.Created, b.Created); order != 0 {
			return order
		}
		return cmp.Compare(a.ID, b.ID)
	})
}

func canonicalIssuePath(issue Issue) string {
	return path.Join("issues", url.PathEscape(issue.ID)+".md")
}

func issueLink(issue Issue, prefix string) string {
	return fmt.Sprintf("[%s: %s](%s%s)", escapeText(issue.ID), escapeText(issue.Title), prefix, canonicalIssuePath(issue))
}

func writeSection(out *bytes.Buffer, heading string, body *string, absent string) {
	writeLine(out, "## "+heading)
	writeLine(out, "")
	writeAuthored(out, body, absent)
}

func writeAuthored(out *bytes.Buffer, body *string, absent string) {
	if body == nil {
		writeLine(out, absent)
		writeLine(out, "")
		return
	}
	out.WriteString(*body)
	if !strings.HasSuffix(*body, "\n") {
		out.WriteByte('\n')
	}
	out.WriteByte('\n')
}

func writeLine(out *bytes.Buffer, line string) {
	out.WriteString(line)
	out.WriteByte('\n')
}

func finishMarkdown(body []byte) []byte {
	return append(bytes.TrimRight(body, "\n"), '\n')
}

func timestamp(unix int64) string {
	return time.Unix(unix, 0).UTC().Format(time.RFC3339)
}

func optionalTimestamp(value *int64) string {
	if value == nil {
		return "-"
	}
	return timestamp(*value)
}

func optionalTable(value *string) string {
	if value == nil {
		return "-"
	}
	return escapeTable(*value)
}

func labelsText(labels []string) string {
	if len(labels) == 0 {
		return "-"
	}
	values := slices.Clone(labels)
	slices.Sort(values)
	for index, value := range values {
		values[index] = code(value)
	}
	return strings.Join(values, ", ")
}

func code(value string) string {
	value = strings.NewReplacer("\r", `\r`, "\n", `\n`).Replace(value)
	longestRun := 0
	currentRun := 0
	for _, character := range value {
		if character == '`' {
			currentRun++
			longestRun = max(longestRun, currentRun)
		} else {
			currentRun = 0
		}
	}
	fence := strings.Repeat("`", longestRun+1)
	if longestRun > 0 || strings.HasPrefix(value, " ") || strings.HasSuffix(value, " ") {
		return fence + " " + value + " " + fence
	}
	return fence + value + fence
}

func escapeTable(value string) string {
	return escapeText(value)
}

func escapeText(value string) string {
	value = strings.ReplaceAll(value, "\r\n", "\n")
	var out strings.Builder
	for _, character := range value {
		if character == '\n' || character == '\r' {
			out.WriteString("<br>")
			continue
		}
		if strings.ContainsRune(`\\`+"`*_{}[]<>#|", character) {
			out.WriteByte('\\')
		}
		out.WriteRune(character)
	}
	return out.String()
}
