// Code generated by MockGen. DO NOT EDIT.
// Source: go.abhg.dev/cardamom/internal/web/leaseconnect (interfaces: Operations)
//
// Generated by this command:
//
//	mockgen -destination mocks_test.go -package leaseconnect -typed -write_package_comment=false . Operations
//

package leaseconnect

import (
	context "context"
	reflect "reflect"

	lease "go.abhg.dev/cardamom/internal/lease"
	gomock "go.uber.org/mock/gomock"
)

// MockOperations is a mock of Operations interface.
type MockOperations struct {
	ctrl     *gomock.Controller
	recorder *MockOperationsMockRecorder
	isgomock struct{}
}

// MockOperationsMockRecorder is the mock recorder for MockOperations.
type MockOperationsMockRecorder struct {
	mock *MockOperations
}

// NewMockOperations creates a new mock instance.
func NewMockOperations(ctrl *gomock.Controller) *MockOperations {
	mock := &MockOperations{ctrl: ctrl}
	mock.recorder = &MockOperationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperations) EXPECT() *MockOperationsMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockOperations) Acquire(arg0 context.Context, arg1 lease.AcquireRequest) (lease.Lease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", arg0, arg1)
	ret0, _ := ret[0].(lease.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockOperationsMockRecorder) Acquire(arg0, arg1 any) *MockOperationsAcquireCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockOperations)(nil).Acquire), arg0, arg1)
	return &MockOperationsAcquireCall{Call: call}
}

// MockOperationsAcquireCall wrap *gomock.Call
type MockOperationsAcquireCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationsAcquireCall) Return(arg0 lease.Lease, arg1 error) *MockOperationsAcquireCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationsAcquireCall) Do(f func(context.Context, lease.AcquireRequest) (lease.Lease, error)) *MockOperationsAcquireCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationsAcquireCall) DoAndReturn(f func(context.Context, lease.AcquireRequest) (lease.Lease, error)) *MockOperationsAcquireCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Get mocks base method.
func (m *MockOperations) Get(arg0 context.Context, arg1 lease.GetRequest) (lease.Lease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(lease.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockOperationsMockRecorder) Get(arg0, arg1 any) *MockOperationsGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockOperations)(nil).Get), arg0, arg1)
	return &MockOperationsGetCall{Call: call}
}

// MockOperationsGetCall wrap *gomock.Call
type MockOperationsGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationsGetCall) Return(arg0 lease.Lease, arg1 error) *MockOperationsGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationsGetCall) Do(f func(context.Context, lease.GetRequest) (lease.Lease, error)) *MockOperationsGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationsGetCall) DoAndReturn(f func(context.Context, lease.GetRequest) (lease.Lease, error)) *MockOperationsGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// List mocks base method.
func (m *MockOperations) List(arg0 context.Context) ([]lease.Lease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0)
	ret0, _ := ret[0].([]lease.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOperationsMockRecorder) List(arg0 any) *MockOperationsListCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOperations)(nil).List), arg0)
	return &MockOperationsListCall{Call: call}
}

// MockOperationsListCall wrap *gomock.Call
type MockOperationsListCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationsListCall) Return(arg0 []lease.Lease, arg1 error) *MockOperationsListCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationsListCall) Do(f func(context.Context) ([]lease.Lease, error)) *MockOperationsListCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationsListCall) DoAndReturn(f func(context.Context) ([]lease.Lease, error)) *MockOperationsListCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Release mocks base method.
func (m *MockOperations) Release(arg0 context.Context, arg1 lease.ReleaseRequest) (lease.Lease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", arg0, arg1)
	ret0, _ := ret[0].(lease.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Release indicates an expected call of Release.
func (mr *MockOperationsMockRecorder) Release(arg0, arg1 any) *MockOperationsReleaseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockOperations)(nil).Release), arg0, arg1)
	return &MockOperationsReleaseCall{Call: call}
}

// MockOperationsReleaseCall wrap *gomock.Call
type MockOperationsReleaseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationsReleaseCall) Return(arg0 lease.Lease, arg1 error) *MockOperationsReleaseCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationsReleaseCall) Do(f func(context.Context, lease.ReleaseRequest) (lease.Lease, error)) *MockOperationsReleaseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationsReleaseCall) DoAndReturn(f func(context.Context, lease.ReleaseRequest) (lease.Lease, error)) *MockOperationsReleaseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Renew mocks base method.
func (m *MockOperations) Renew(arg0 context.Context, arg1 lease.RenewRequest) (lease.Lease, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Renew", arg0, arg1)
	ret0, _ := ret[0].(lease.Lease)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Renew indicates an expected call of Renew.
func (mr *MockOperationsMockRecorder) Renew(arg0, arg1 any) *MockOperationsRenewCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Renew", reflect.TypeOf((*MockOperations)(nil).Renew), arg0, arg1)
	return &MockOperationsRenewCall{Call: call}
}

// MockOperationsRenewCall wrap *gomock.Call
type MockOperationsRenewCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationsRenewCall) Return(arg0 lease.Lease, arg1 error) *MockOperationsRenewCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationsRenewCall) Do(f func(context.Context, lease.RenewRequest) (lease.Lease, error)) *MockOperationsRenewCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationsRenewCall) DoAndReturn(f func(context.Context, lease.RenewRequest) (lease.Lease, error)) *MockOperationsRenewCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Revoke mocks base method.
func (m *MockOperations) Revoke(arg0 context.Context, arg1 lease.RevokeRequest) (lease.Revocation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", arg0, arg1)
	ret0, _ := ret[0].(lease.Revocation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MockOperationsMockRecorder) Revoke(arg0, arg1 any) *MockOperationsRevokeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockOperations)(nil).Revoke), arg0, arg1)
	return &MockOperationsRevokeCall{Call: call}
}

// MockOperationsRevokeCall wrap *gomock.Call
type MockOperationsRevokeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOperationsRevokeCall) Return(arg0 lease.Revocation, arg1 error) *MockOperationsRevokeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOperationsRevokeCall) Do(f func(context.Context, lease.RevokeRequest) (lease.Revocation, error)) *MockOperationsRevokeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOperationsRevokeCall) DoAndReturn(f func(context.Context, lease.RevokeRequest) (lease.Revocation, error)) *MockOperationsRevokeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
