name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Check out repository
      - uses: jdx/mise-action@v4
        with:
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: mise run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    # TODO: Add Windows testing when the suite is ready for that host.
    steps:
      - uses: actions/checkout@v6
        name: Check out repository
      - uses: jdx/mise-action@v4
        with:
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: mise run build
        shell: bash
      - name: Test
        run: mise run test --race

  ok:
    name: OK
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: always()
    steps:
      - run: exit 1
        if: >-
          needs.lint.result != 'success' ||
          needs.test.result != 'success'
      - run: exit 0
